### PR TITLE
Fix assigning IPs to Windows pods

### LINKED ISSUE #2721: New Windows nodes unable to assign IP to pods
**What happened?**
Upon creating a new cluster using the config below, the Windows nodes are unable to support any pods, with each new one scheduled reporting `pod does not have label vpc.amazonaws.com/PrivateIPv4Address`
<details>
  <summary>Cluster.yaml</summary>

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-west-2
  tags:
    eks-cluster: test-cluster

availabilityZones:
  - "eu-west-2a"
  - "eu-west-2b"
  - "eu-west-2c"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: mail
        namespace: test
        labels:
          app.kubernetes.io/name: mail
          app.kubernetes.io/part-of: test
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ses:SendEmail"
              - "ses:SendRawEmail"
            Resource: "*"

vpc:
  publicAccessCIDRs:
    - xx.xxx.xx.xx/32
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single

managedNodeGroups:
  - name: test-cluster-linux-ng1
    instanceType: t3.medium
    minSize: 1
    maxSize: 6
    privateNetworking: true

nodeGroups:
  - name: test-cluster-windows-ng1
    amiFamily: WindowsServer2019CoreContainer
    minSize: 1
    maxSize: 6
    privateNetworking: true
    instancesDistribution:
      instanceTypes: ["t3.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2

cloudWatch:
  clusterLogging:
    enableTypes:
      - audit
      - authenticator
```

</details>

On creation the logs look to have been successful (see below) and all linux workloads I've tried have worked. The issue surfaced when I recreated the cluster after updating eksctl to 0.29.2 from 0.28.0 using identical cluster config. I think it may be some problem surrounding the VPC controller but further than that I haven't been able to work out.

<details>
  <summary>eksctl logs</summary>

```
[ℹ]  eksctl version 0.29.2
[ℹ]  using region eu-west-2
[ℹ]  subnets for eu-west-2a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for eu-west-2b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for eu-west-2c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "test-cluster-windows-ng1" will use "ami-02f8f49e778ee1b40" [WindowsServer2019CoreContainer/1.17]
[ℹ]  using Kubernetes version 1.17
[ℹ]  creating EKS cluster "test-cluster" in "eu-west-2" region with managed nodes and un-managed nodes
[ℹ]  2 nodegroups (test-cluster-linux-ng1, test-cluster-windows-ng1) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-west-2 --cluster=test-cluster'
[ℹ]  Kubernetes API endpoint access will use provided values {publicAccess=true, privateAccess=true} for cluster "test-cluster" in "eu-west-2"
[ℹ]  2 sequential tasks: { create cluster control plane "test-cluster", 2 sequential sub-tasks: { 8 sequential sub-tasks: { tag cluster, update CloudWatch logging configuration, update cluster VPC endpoint access configuration, update public access CIDRs, install Windows VPC controller, associate IAM OIDC provider, 6 parallel sub-tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "siren/cluster-autoscaler", create serviceaccount "siren/cluster-autoscaler" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "siren/fluent", create serviceaccount "siren/fluent" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "siren/fluent-windows", create serviceaccount "siren/fluent-windows" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "siren/ebs-csi-controller-sa", create serviceaccount "siren/ebs-csi-controller-sa" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "test-cluster/a2c-cronjobs", create serviceaccount "test-cluster/a2c-cronjobs" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }, restart daemonset "kube-system/aws-node" }, 2 parallel sub-tasks: { create nodegroup "test-cluster-windows-ng1", create managed nodegroup "test-cluster-linux-ng1" } } }
[ℹ]  building cluster stack "eksctl-test-cluster-cluster"
[ℹ]  deploying stack "eksctl-test-cluster-cluster"
[✔]  tagged EKS cluster (eks-cluster=test-cluster)
[✔]  configured CloudWatch logging for cluster "test-cluster" in "eu-west-2" (enabled types: audit, authenticator & disabled types: api, controllerManager, scheduler)
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/vpc-resource-controller"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/vpc-resource-controller"
[ℹ]  replaced "kube-system:ServiceAccount/vpc-resource-controller"
[ℹ]  created "kube-system:Deployment.apps/vpc-resource-controller"
2020/10/07 16:18:40 [INFO] generate received request
2020/10/07 16:18:40 [INFO] received CSR
2020/10/07 16:18:40 [INFO] generating key: rsa-2048
2020/10/07 16:18:40 [INFO] encoded CSR
[ℹ]  created "CertificateSigningRequest.certificates.k8s.io/vpc-admission-webhook.kube-system"
[ℹ]  waiting for certificate to be available
[!]  certificate not yet available (event: ADDED)
[ℹ]  created "kube-system:secret/vpc-admission-webhook-certs"
[ℹ]  created "kube-system:Service/vpc-admission-webhook"
[ℹ]  created "kube-system:Deployment.apps/vpc-admission-webhook"
[ℹ]  created "kube-system:MutatingWebhookConfiguration.admissionregistration.k8s.io/vpc-admission-webhook-cfg"
[ℹ]  building iamserviceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windows"
[[building iamserviceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windo-windows"
[building iamserviceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windo-windows"
["ing ia"ing i[ng iamserviceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windo-windows"
m
d
viceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windo-windo-windows"
"ceaccount"ceaccount stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windo-windo-windo[ℹ]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-kube-system-aws-node"
[0m�]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent"
[ℹ]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-siren-fluent-windows"
[ℹ]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-a2c-trans-csi-controller-sa"
[ℹ]  deploying stack "eksctl-test-cluster-addon-iamserviceaccount-siren-ebs-csi-controller-sa"
[ℹ]  serviceaccount "kube-system/aws-node" already exists
[ℹ]  updated serviceaccount "kube-system/aws-node"
[ℹ]  created namespace "siren"
[ℹ]  created serviceaccount "siren/fluent-windows"
[ℹ]  created namespace "test-cluster"
[ℹ]  created serviceaccount "test-cluster/a2c-cronjobs"
[ℹ]  created serviceaccount "siren/cluster-autoscaler"
[ℹ]  created serviceaccount "siren/ebs-csi-controller-sa"
[ℹ]  created serviceaccount "siren/fluent"
[ℹ]  daemonset "kube-system/aws-node" restarted
[ℹ]  building nodegroup stack "eksctl-test-cluster-nodegroup-test-cluster-windows-ng1"
[ℹ]  building nodegroup stack "eksctl-test-cluster-nodegroup-test-cluster-windows-ng1"
"
[ℹ]  deploying stack "eksctl-test-cluster-nodegroup-test-cluster-linux-ng1"
[ℹ]  deploying stack "eksctl-test-cluster-nodegroup-test-cluster-windows-ng1"
[ℹ]  waiting for the control plane availability...
[✔]  saved kubeconfig as "C:\\Users\\sgregory/.kube/config"
[ℹ]  no tasks
[✔]  all EKS cluster resources for "test-cluster" have been created
[ℹ]  adding identity "arn:aws:iam::516651820982:role/eksctl-test-cluster-nodegroup-a2-NodeInstanceRole-AY7W6XSFQT44" to auth ConfigMap
[ℹ]  nodegroup "test-cluster-windows-ng1" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "test-cluster-windows-ng1"
[ℹ]  nodegroup "test-cluster-windows-ng1" has 1 node(s)
[ℹ]  node "ip-192-168-96-254.eu-west-2.compute.internal" is ready
[ℹ]  nodegroup "test-cluster-linux-ng1" has 1 node(s)
[ℹ]  node "ip-192-168-146-94.eu-west-2.compute.internal" is ready
[ℹ]  waiting for at least 1 node(s) to become ready in "test-cluster-linux-ng1"
[ℹ]  nodegroup "test-cluster-linux-ng1" has 1 node(s)
[ℹ]  node "ip-192-168-146-94.eu-west-2.compute.internal" is ready
[ℹ]  kubectl command should work with "C:\\Users\\sgregory/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "test-cluster" in "eu-west-2" region is ready
```

</details>

**What you expected to happen?**
I expected for the cluster to create successfully and be able to support the windows workloads that had been working previously using the same configuration.

**How to reproduce it?**
1. Run `eksctl create cluster -f .\cluster.yaml --install-vpc-controllers` using the configuration above.
2. Apply a deployment that should create windows pods. I've been primarily using a custom one that I can't share, however the eks iis example produces the same failing results (https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#windows-sample-application).
3. Observe that the windows pods are stuck at the `ContainerCreating` stage and the events for the pod show the message `pod does not have label vpc.amazonaws.com/PrivateIPv4Address`.

**Versions**
Please paste in the output of these commands:
**$ eksctl version: 0.29.2**
**$ kubectl version:**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

If any other information would help get to the root of the issue then let me know and I can get them.

### PR DESCRIPTION
**Pull request by cPu1**
### Description

The VPC controller requires a subset of the IAM policies of the VPC CNI plugin to work. In a cluster with no OIDC provider, the policies required by the CNI plugin are attached to the node role, so the VPC resource controller ends up using it. When a cluster has an OIDC provider (`iam.withOIDC`), however, eksctl uses IRSA for the VPC CNI plugin, causing the VPC controller to be unable to access AWS APIs.

This PR makes the VPC controller use IRSA if an OIDC provider is associated with the cluster, attaching only the policies required by the VPC controller instead of using the more permissive `AmazonEKS_CNI_Policy` managed policy.

Fixes #2721 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/cfn/manager/iam.go [hunk 1]
```diff
@@ -18,7 +21,7 @@ func (c *StackCollection) makeIAMServiceAccountStackName(namespace, name string)
 }
 
 // createIAMServiceAccountTask creates the iamserviceaccount in CloudFormation
-func (c *StackCollection) createIAMServiceAccountTask(errs chan error, spec *api.ClusterIAMServiceAccount, oidc *iamoidc.OpenIDConnectManager) error {
+func (c *StackCollection) createIAMServiceAccountTask(errs chan error, spec *api.ClusterIAMServiceAccount, oidc *iamoidc.OpenIDConnectManager, replaceIfExists bool) error {
```
Comment (michaelbeaumont) [inline pkg/cfn/manager/iam.go:24]: nitpicky but can this be called `replaceExistingRole`? Took me slightly more than Ctrl-F ing to find where that variable from `NewTasksToCreateIAMServiceAccounts` was actually used

File: pkg/cfn/manager/iam.go [hunk 2]
```diff
@@ -31,7 +34,22 @@ func (c *StackCollection) createIAMServiceAccountTask(errs chan error, spec *api
 	}
 	spec.Tags[api.IAMServiceAccountNameTag] = spec.NameString()
 
-	return c.CreateStack(name, stack, spec.Tags, nil, errs)
+	if err := c.CreateStack(name, stack, spec.Tags, nil, errs); err != nil {
+		if !replaceIfExists {
+			return err
```
Comment (michaelbeaumont) [inline pkg/cfn/manager/iam.go:39]: what are the consequences of returning an `AlreadyExists` error here? can `eksctl` not continue on in that case?

Comment (cPu1) [reply pkg/cfn/manager/iam.go:39]: >can eksctl not continue on in that case?

Yes, if `replaceExistingRole`/`replaceIfExists` isn't set, eksctl should not continue. 

The `replaceExistingRole` variable determines if the caller expects the role may already exist, and to replace it if it does. Right now, only the VPC resource controller needs this operation to be idempotent. For other operations like `create iamserviceaccount`, eksctl should not continue and abort with that error.

File: pkg/cfn/manager/iam.go (hunk 1 above)
Comment (cPu1) [reply pkg/cfn/manager/iam.go:24]: Well spotted.

File: pkg/addons/vpc_controller.go [hunk 3]
```diff
@@ -209,9 +212,52 @@ func (v *VPCController) createCertSecrets(key, cert []byte) error {
...
+	if err != nil {
+		return err
+	}
+	if irsaEnabled {
+		sa := &api.ClusterIAMServiceAccount{
+			ClusterIAMMeta: api.ClusterIAMMeta{
+				Name:      vpcControllerName,
+				Namespace: vpcControllerNamespace,
+			},
+			AttachPolicy: map[string]interface{}{
```
Comment (michaelbeaumont) [inline pkg/addons/vpc_controller.go:225]: could this be its own var/function like in `pkg/cfn/builder`?

File: pkg/addons/irsa_helper.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	"github.com/pkg/errors"
+	api "github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5"
+	iamoidc "github.com/weaveworks/eksctl/pkg/iam/oidc"
+	"github.com/weaveworks/eksctl/pkg/kubernetes"
+	"github.com/weaveworks/eksctl/pkg/utils/tasks"
+)
+
+type serviceAccountCreator interface {
+	NewTasksToCreateIAMServiceAccounts(serviceAccounts []*api.ClusterIAMServiceAccount, oidc *iamoidc.OpenIDConnectManager, clientSetGetter kubernetes.ClientSetGetter, replaceExistingRole bool) *tasks.TaskTree
+}
```
Comment (Callisto13) [inline pkg/addons/irsa_helper.go:16]: Can I ask why we have this little interface here?

It took me fractionally longer to parse the composition than if stackcollection (or stackmanager, whatever it is) were simply called from the helper struct on line 51.

Comment (cPu1) [reply pkg/addons/irsa_helper.go:16]: Because `irsaHelper` only needs this method and not the entire `StackCollection`. This makes testing the `VPCController` and `IRSAHelper` easier. It's somewhat similar to saying why, e.g, `ioutil.ReadAll` takes an `io.Reader` and not an `os.File` or  a `net.TCPConn`.

Comment (Callisto13) [reply pkg/addons/irsa_helper.go:16]: Oh I couldn't find tests in this PR (I did assume that to start), are they still coming?

Comment (cPu1) [reply pkg/addons/irsa_helper.go:16]: I meant that as a general comment. I haven't added tests as the bulk of the logic is making Kubernetes and AWS calls.

File: pkg/addons/vpc_controller.go (hunk 3 above)
Comment (cPu1) [reply pkg/addons/vpc_controller.go]: Makes sense :+1:

File: pkg/cfn/manager/iam.go [hunk 5]
```diff
@@ -31,7 +34,22 @@ func (c *StackCollection) createIAMServiceAccountTask(errs chan error, spec *api
...
+		}
+		var awsErr awserr.Error
+		if errors.As(err, &awsErr) && awsErr.Code() == cfn.ErrCodeAlreadyExistsException {
+			logger.Debug("CFN stack for IRSA already exists, replacing it with a new stack")
+			if err := c.DeleteStackByNameSync(name); err != nil {
+				close(errs)
+				return errors.Wrap(err, "error deleting stack")
+			}
+			return c.createIAMServiceAccountTask(errs, spec, oidc, false)
```
Comment (aclevername) [inline pkg/cfn/manager/iam.go:48]: Am I right in thinking that VPC controller installation only occurs during cluster creation? If so then when will the scenario occur where the SA already exists occur?

**Comment by aclevername** [comment]
> The VPC controller requires a subset of the IAM policies of the VPC CNI plugin to work. In a cluster with no OIDC provider, the policies required by the CNI plugin are attached to the node role, so the VPC resource controller ends up using it

is there a way we could make it more explicit in the code that the VPC Controller also uses/needs this policy when OIDC is disabled? It feels almost accidental that the VPC Controller worked

File: pkg/cfn/manager/iam.go (hunk 5 above)
Comment (cPu1) [reply pkg/cfn/manager/iam.go:48]: >If so then when will the scenario occur where the SA already exists occur?

The VPC controller can be installed on an existing cluster using  `eksctl utils install-vpc-controllers`.

**Comment by cPu1** [comment]
> > The VPC controller requires a subset of the IAM policies of the VPC CNI plugin to work. In a cluster with no OIDC provider, the policies required by the CNI plugin are attached to the node role, so the VPC resource controller ends up using it
> 
> is there a way we could make it more explicit in the code that the VPC Controller also uses/needs this policy when OIDC is disabled? It feels almost accidental that the VPC Controller worked

There's little value in attaching the VPC controller-specific policies to the node role because they're a subset of the policies required by the VPC CNI plugin. Although I agree that a comment documenting this behaviour would be useful.

File: pkg/cfn/manager/iam.go (hunk 5 above)
Comment (aclevername) [reply pkg/cfn/manager/iam.go:48]: So is the scenario here when a user runs `eksctl utils install-vpc-controllers` after a cluster installation that already installed the VPC controller? If so why do we need to delete & recreate, can't just check for its existence and exit early if it does?

Comment (cPu1) [reply pkg/cfn/manager/iam.go:48]: This is to allow applying any changes to the policy document. If we just check for existence, any changes made to the policy document in code will not be applied.

Comment (aclevername) [reply pkg/cfn/manager/iam.go:48]: but is it needed for this PR? I'm just trying to understand when this codepath is used in relation to `vpc-controller` 😄 

It might be that this isn't needed as we will add the ability to update IAM policies without deleting here https://github.com/weaveworks/eksctl/pull/3064

Comment (cPu1) [reply pkg/cfn/manager/iam.go:48]: > I'm just trying to understand when this codepath is used in relation to vpc-controller

This codepath is invoked when `utils install-vpc-controllers` is run on a cluster that already has the VPC controller installed (either as part of `create cluster` or with `utils install-vpc-controllers` itself). The ServiceAccount created for the role needs the role ARN, so if we skip creation of this stack if it already exists, we'll have to fetch it and get the role ARN, and any changes to the policy document will be ignored.

Comment (aclevername) [reply pkg/cfn/manager/iam.go:48]: Ah I see, so is this just for the scenario in which: I have an already created eksctl cluster with oidc enabled and the VPC controller installed, but its missing the policies because I created it with an older version of eksctl? If so that makes sense 😄 

Apart from that scenario you'd never need to run `utils install-vpc-controllers` if its already installed correct?

Comment (cPu1) [reply pkg/cfn/manager/iam.go:48]: >Ah I see, so is this just for the scenario in which: I have an already created eksctl cluster with oidc enabled and the VPC controller installed, but its missing the policies because I created it with an older version of eksctl?

That's right.

>Apart from that scenario you'd never need to run utils install-vpc-controllers if its already installed correct?

Users may also run it to upgrade to a newer version of the VPC controller.

Comment (aclevername) [reply pkg/cfn/manager/iam.go:48]: Thanks! Makes sense. Does this add more downtime for users when they update the VPC controller as we will always delete and recreate the policies even if they are unchanged? Very minor, but it could be removed by using the update functionality https://github.com/weaveworks/eksctl/pull/3064

Comment (cPu1) [reply pkg/cfn/manager/iam.go:48]: >Does this add more downtime for users when they update the VPC controller as we will always delete and recreate the policies even if they are unchanged?

Yes. 

>Very minor, but it could be removed by using the update functionality #3064

Yeah, the ideal way would be to update the policies in the existing stack, but since we didn't already have code that updates the policies for IRSA, I went with recreating it. I was aware of your PR but it wasn't in `master` when I was working on this PR. After your PR is merged, I can change this code to use the update feature (or it can be done as an improvement later).

**Review by michaelbeaumont — APPROVED** [review]
My changes addressed, LGTM

**Review by aclevername — APPROVED** [review]
LGTM
