### PR TITLE
Cloudformation stack validation error because of underscore in EKS cluster name

### LINKED ISSUE #2943: Cloudformation stack validation error because of underscore in EKS cluster name
**What happened?**
When executing the following command

```
 eksctl create iamserviceaccount --region=eu-somewhere-1 --cluster="test-k8_cluster01" --namespace="kube-system" --name="aws-load-balancer-controller" --attach-policy-arn="arn:aws:iam::123456789:policy/AWSLoadBalancerControllerIAMPolicy" --override-existing-serviceaccounts --approve
```

The command crashes with the error message :

```
[✖]  creating CloudFormation stack "eksctl-test-k8_cluster01-addon-iamserviceaccount-kube-system-aws-node": ValidationError: 1 validation error detected: Value 'eksctl-test-k8_cluster01-addon-iamserviceaccount-kube-system-aws-node' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
	status code: 400, request id: b14a2ed8-cfb7-4d39-9a9b-fe3dff5ccb84
[✖]  creating CloudFormation stack "eksctl-test-k8_cluster01-addon-iamserviceaccount-kube-system-aws-load-balancer-controller": ValidationError: 1 validation error detected: Value 'eksctl-test-k8_cluster01-addon-iamserviceaccount-kube-system-aws-load-balancer-controller' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
	status code: 400, request id: 4ef28140-d880-4455-bacc-1c87ed569891
```

**What you expected to happen?**

Remove any unallowed characters and create the cloudformation stack


**How to reproduce it?**
user a cluster name with an undescore 


**Versions**

```
> $ kubectl version                                                                                                                                                                                                                                                              
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
                                                                                                                                                                                                                                                                                  
> $ eksctl version                                                                                                                                                                                                                                                               
0.34.0

```

**Logs**
 see attached file
[eksctl.log](https://github.com/weaveworks/eksctl/files/5694483/eksctl.log)

### PR DESCRIPTION
**Pull request by Himangini**
Added validation for cluster name and node group name for cloudformation error.
The code now checks the clustername or nodegroup name passed to have any invalid chars. If it does then the command displays error instead of trying to create the cluster which eventually crashes with a Cloudformation error. Also updated the docs for users with the Cloudformation naming guidelines information.

Fixes #2943 

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/ctl/cmdutils/cmdutils.go [hunk 1]
```diff
@@ -103,6 +104,12 @@ func GetNameArg(args []string) string {
 	return ""
 }
 
+// IsValidNameArg checks whether the name contains invalid characters
+func IsValidNameArg(name string) bool {
```
Comment (aclevername) [inline pkg/ctl/cmdutils/cmdutils.go:108]: Since we always call the func like `!cmdutils.IsValidNameArg()` shall we inverse the return value and make it `isInvalidNameArg`?

**Review by aclevername — APPROVED** [review]
LGTM, 1 nit :smile: 

Update: spotted couple edgecases

File: pkg/ctl/create/nodegroup.go [hunk 2]
```diff
@@ -26,6 +26,10 @@ type nodegroupOptions struct {
 
 func createNodeGroupCmd(cmd *cmdutils.Cmd) {
 	createNodeGroupCmdWithRunFunc(cmd, func(cmd *cmdutils.Cmd, ng *api.NodeGroup, options nodegroupOptions) error {
+		if ng.Name != "" && !cmdutils.IsValidNameArg(ng.Name) {
+			return cmdutils.ErrInvalidName(ng.Name)
+		}
+
```
Comment (aclevername) [inline pkg/ctl/create/nodegroup.go:32]: does this func ever run for multiple nodegroups? I thought we supported it, but it looks like we only pass in 1 `ng` :thinking:

File: pkg/ctl/create/cluster.go [hunk 3]
```diff
@@ -107,6 +107,10 @@ func doCreateCluster(cmd *cmdutils.Cmd, ngFilter *filter.NodeGroupFilter, params
 	cfg := cmd.ClusterConfig
 	meta := cmd.ClusterConfig.Metadata
 
+	if meta.Name != "" && !cmdutils.IsValidNameArg(meta.Name) {
+		return cmdutils.ErrInvalidName(meta.Name)
+	}
+
```
Comment (aclevername) [inline pkg/ctl/create/cluster.go:113]: you can create nodegroups as part of create cluster. do we want to verify they are valid too?

**Comment by Callisto13** [comment]
Can we add a note on the Unowned Cluster docs page that we do not support clusters created outside of eksctl which do not meet the CF pattern?

File: pkg/ctl/create/nodegroup.go (hunk 2 above)
Comment (Himangini) [reply pkg/ctl/create/nodegroup.go:32]: not sure, i thought this runs on a single nodegroup, i'll investigate

File: pkg/ctl/cmdutils/cmdutils.go (hunk 1 above)
Comment (Himangini) [reply pkg/ctl/cmdutils/cmdutils.go]: changed to the suggested name

File: pkg/ctl/create/cluster.go (hunk 3 above)
Comment (Himangini) [reply pkg/ctl/create/cluster.go]: added validation checks for multiple nodegroups 👍🏻

**Review by aclevername — APPROVED** [review]
LGTM!
