### PR TITLE
Apply undo flag when running `drain nodegroup`

### LINKED ISSUE #4648: Undo flag ignored in `eksctl drain nodegroup --undo`
**What were you trying to accomplish?**

 Running `eksctl drain nodegroup --undo`

**What happened?**

Does not uncordon any nodes. The documentation says that `--undo` should uncordon, see https://eksctl.io/usage/managing-nodegroups/#deleting-and-draining.

**How to reproduce it?**

**Logs**

```
eksctl drain nodegroup --undo --cluster=gnss-eks-2-dev --name=ginan-ops-green -v9
2022-01-18 07:32:11 [ℹ]  eksctl version 0.81.0-dev+9250c69b.2022-01-18T07:30:28Z
2022-01-18 07:32:11 [ℹ]  using region ap-southeast-2
2022-01-18 07:32:11 [▶]  failed to fetch nodegroup "ginan-ops-green" stack: describing CloudFormation stack "eksctl-gnss-eks-2-dev-nodegroup-ginan-ops-green": ValidationError: Stack with id eksctl-gnss-eks-2-dev-nodegroup-ginan-ops-green does not exist
	status code: 400, request id: 8dcffeed-9643-47de-947c-1a319cb8b164
2022-01-18 07:32:11 [ℹ]  1 nodegroup (ginan-ops-green) was included (based on the include/exclude rules)
2022-01-18 07:32:11 [ℹ]  will uncordon 0 nodegroup(s) in cluster "gnss-eks-2-dev"
2022-01-18 07:32:11 [ℹ]  will uncordon 1 managed nodegroup(s) in cluster "gnss-eks-2-dev"
2022-01-18 07:32:13 [▶]  no need to cordon node "ip-10-49-12-78.ap-southeast-2.compute.internal"
2022-01-18 07:32:13 [▶]  already drained: []
2022-01-18 07:32:13 [▶]  will drain: [ip-10-49-12-78.ap-southeast-2.compute.internal]
2022-01-18 07:32:13 [!]  ignoring DaemonSet-managed Pods: cilium/cilium-5hjnp, cilium/cilium-node-init-t5g6z, fluent-bit/fluent-bit-fluent-bit-loki-xjnmr, kube-system/aws-node-hw8kc, kube-system/kube-proxy-s2zzp, prometheus/kube-prometheus-stack-prometheus-node-exporter-5xd54
2022-01-18 07:32:13 [▶]  0 pods to be evicted from ip-10-49-12-78.ap-southeast-2.compute.internal
2022-01-18 07:32:13 [▶]  no need to cordon node "ip-10-49-12-78.ap-southeast-2.compute.internal"
2022-01-18 07:32:13 [✔]  drained all nodes: [ip-10-49-12-78.ap-southeast-2.compute.internal]
```

**Anything else we need to know?**

The undo flag is accepted, but ignored when running `drain nodegroup`, defaulting to `false`.

https://github.com/weaveworks/eksctl/blob/9250c69b1bbb8adc6525e55adcd9251ac1b09a61/pkg/actions/nodegroup/drain.go#L14

**Versions**

```
$ eksctl info
eksctl version: 0.76.0
kubectl version: v1.22.4
OS: linux
```

### PR DESCRIPTION
**Pull request by lbodor**
### Description

Fixes #4648

There is an existing test, which may be sufficient.

https://github.com/weaveworks/eksctl/blob/9250c69b1bbb8adc6525e55adcd9251ac1b09a61/pkg/drain/nodegroup_test.go#L20

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/actions/nodegroup/drain.go [hunk 1]
```diff
@@ -8,10 +8,10 @@ import (
 	"github.com/weaveworks/eksctl/pkg/drain"
 )
 
-func (m *Manager) Drain(nodeGroups []eks.KubeNodeGroup, plan bool, maxGracePeriod time.Duration, disableEviction bool) error {
+func (m *Manager) Drain(nodeGroups []eks.KubeNodeGroup, plan bool, maxGracePeriod time.Duration, undo bool, disableEviction bool) error {
```
Comment (cPu1) [inline pkg/actions/nodegroup/drain.go:11]: Nit:
```suggestion
func (m *Manager) Drain(nodeGroups []eks.KubeNodeGroup, plan bool, maxGracePeriod time.Duration, undo, disableEviction bool) error {
```

**Review by cPu1 — APPROVED** [review]
LGTM. Thanks for the contribution.
