### PR TITLE
Return message when VPC config missing on unowned ng create

### LINKED ISSUE #4049: panic when creating nodegroup on unowned cluster
**What were you trying to accomplish?**

Add a managed node group to an existing AWS EKS Cluster which is not eksctl managed
```
eksctl create nodegroup --config-file eks_nodegroup.yaml -p hcs_au
```
**What happened?**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x32eda7b]
```
**How to reproduce it?**

```
eksctl create nodegroup --config-file eks_nodegroup.yaml -p hcs_au
2021-08-04 14:15:44 [ℹ]  eksctl version 0.59.0
2021-08-04 14:15:44 [ℹ]  using region ap-southeast-2
2021-08-04 14:15:46 [!]  no eksctl-managed CloudFormation stacks found for "hcs-au", will attempt to create nodegroup(s) on non eksctl-managed cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x32eda7b]
```

**Logs**

```
eksctl create nodegroup --config-file eks_nodegroup.yaml -p hcs_au
2021-08-04 14:15:44 [ℹ]  eksctl version 0.59.0
2021-08-04 14:15:44 [ℹ]  using region ap-southeast-2
2021-08-04 14:15:46 [!]  no eksctl-managed CloudFormation stacks found for "hcs-au", will attempt to create nodegroup(s) on non eksctl-managed cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x32eda7b]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.loadVPCFromConfig(0x44e3690, 0xc00031dad0, 0xc00050fd00, 0x1, 0x1)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:296 +0x3b
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Create(0xc0003fcf00, 0x10000010101, 0x44a06f0, 0xc00051c380, 0xc0003fcf00, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:54 +0x2d6
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc0001242c0, 0xc00056e460, 0x101, 0x1, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:60 +0x3c5
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc00016e780, 0xc0002930c0, 0x0, 0x4, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:86 +0x106
github.com/spf13/cobra.(*Command).execute(0xc00016e780, 0xc000293080, 0x4, 0x4, 0xc00016e780, 0xc000293080)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00002f400, 0xc00051ae20, 0x1, 0xc000857f70)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
```
**Anything else we need to know?**

MacOS Big Sur
Downloaded binary of eksctl, tried 0.58, 0.59 and 0.60rc-0, all panic
AWS named profile

**Versions**

```
$ eksctl info
eksctl version: 0.59.0
kubectl version: v1.19.0
OS: darwin
```

**eks_nodegroup.yaml**

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hcs-au
  region: ap-southeast-2
  version: "1.20"
managedNodeGroups:
- name: localssd
  instanceTypes: ["m5ad.xlarge","m5d.xlarge"]
  spot: true
  availabilityZones: ["ap-southeast-2b","ap-southeast-2c"]
  desiredCapacity: 1
  minSize: 1
  maxSize: 2
  iam:
    instanceRoleARN: arn:aws:iam::671700000000:role/NodeInstanceRole
  launchTemplate:
    id: lt-07bd1ef4d00000000
```

### PR DESCRIPTION
**Pull request by NaivePa**
### Description
Fixes #4049 

Fixing npe when vpc details are not given in the configuration

Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Callisto13** [comment]
Out of curiosity, do which know which missing bit fails?

We already have checks for subnets, vpc-id and security group. Those should be the only required things. Which bit was it panicking on?

**Comment by NaivePa** [comment]
@Callisto13  it was a panic directly on VPC object,so added a nil check to handle it.

**Comment by Callisto13** [comment]
makes sense 👍  can you update the unit tests?

File: pkg/actions/nodegroup/create.go [hunk 1]
```diff
@@ -293,6 +294,9 @@ func (m *Manager) checkARMSupport(ctl *eks.ClusterProvider, clientSet kubernetes
 }
 
 func loadVPCFromConfig(provider api.ClusterProvider, cfg *api.ClusterConfig) error {
+	if cfg.VPC == nil {
+		return errors.New("VPC configuration required for creating nodegroups on clusters not owned by eksctl.")
+	}
 	if cfg.VPC.Subnets == nil || cfg.VPC.SecurityGroup == "" || cfg.VPC.ID == "" {
```
Comment (Callisto13) [inline pkg/actions/nodegroup/create.go:300]: We can probably single-line this. I think it is _just_ on the side of not being so long it's gross
```suggestion
	if cfg.VPC == nil || cfg.VPC.Subnets == nil || cfg.VPC.SecurityGroup == "" || cfg.VPC.ID == "" {
```

Comment (NaivePa) [reply pkg/actions/nodegroup/create.go:300]: @Callisto13 I was thinking about the same but i did not want to touch the existing code and also return error i think vpc.subnets, vpc.id, vpc.securityGroup will give error because vpc details are empty when putting it in single-line.

**Review by Callisto13 — APPROVED** [review]
