### PR TITLE
fix #1910 set China region correct audience

### LINKED ISSUE #1910: [IRSA] Audience for aws-cn partition should be sts.amazonaws.com
**What happened?**
Failed to call below command in IRSA enabled pod in AWS China regions:
```
aws sts get-caller-identity
```
error message is 
```
Not authorized to perform sts:AssumeRoleWithWebIdentity
```

**What you expected to happen?**
IRSA should be work.

**How to reproduce it?**
Following official doc.

**Anything else we need to know?**
Most likely, this issue was introduced by PR #1877.
Actually, audience is a token rather than endpoint, which was set the eks-identity-webhook, the default value is sts.amazonaws.com

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0-rc.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

### PR DESCRIPTION
**Pull request by stevensu1977**
### Description

fix #1910 , set China region correct audience, OIDC provider and AssumeRolePolicy use "sts.amazonaws.com"

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `site/content` directory)
- [x] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

File: pkg/iam/oidc/api.go [hunk 1]
```diff
@@ -16,10 +16,7 @@ import (
 	cft "github.com/weaveworks/eksctl/pkg/cfn/template"
 )
 
-var defaultAudienceByPartition = map[string]string{
-	"aws":    "sts.amazonaws.com",
-	"aws-cn": "sts.amazonaws.com.cn",
-}
+var defaultAudience = "sts.amazonaws.com"
```
Comment (cPu1) [inline pkg/iam/oidc/api.go]: Please make this a const
```suggestion
const defaultAudience = "sts.amazonaws.com"
```
