### PR TITLE
Fix setting ownership status when listing clusters

### LINKED ISSUE #4888: 0.83->0.85: eksctl get clusters shows different status for "EKSCTL CREATED"
**What were you trying to accomplish?**

I wanted to list the current set of clusters, so I ran 
```$ eksctl get clusters```

**What happened?**

Using 0.83, the list of clusters was given, and the correct status of "True" was given in the "EKSCTL CREATED" column

I then updated eksctl to 0.85, and repeated the command. Now the incorrect status of "False" was given for the same clusters.

**How to reproduce it?**

Create a cluster using an old version of eksctl. Verify that "eksctl get clusters" shows that "EKSCTL CREATED" status as True using eksctl 0.83.

Now try "eksctl get clusters" with eksctl 0.85 and see that status turn to False

**Logs**

The verbose command adds no new information.

**Anything else we need to know?**

I upgraded eksctl using brew on OSX.

**Versions**

```
$ eksctl info
```

```
% eksctl info
eksctl version: 0.85.0
kubectl version: v1.22.4
OS: darwin
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Instead of using the `clusterName` argument, the method was obtaining the cluster name via the `spec` field.

Fixes #4888 

This changelist correctly sets the `EKSCTL CREATED` column to `True` for clusters created via eksctl:

```
NAME					        REGION		EKSCTL CREATED
test-cluster                              	us-west-2	True
test-cluster2                             	us-west-2	True


```

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by nikimanoledaki** [comment]
Good job getting a fix quickly! :) Could you add unit tests please?

**Review by aclevername — CHANGES_REQUESTED** [review]
can we get some unit tests if possible, and update the unowned cluster integration test?

File: integration/matchers/cluster.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+type GetClusterOutput struct {
+	ClusterName   string
+	Region        string
+	EksctlCreated string
+}
+
+// AssertContainsCluster asserts that the output of the specified command contains the specified cluster
+func AssertContainsCluster(cmd runner.Cmd, out GetClusterOutput) {
+	Expect(cmd).To(runner.RunSuccessfullyWithOutputStringLines(
```
Comment (cPu1) [inline integration/matchers/cluster.go:19]: Intentionally not using a dot import because runner.Cmd is also being used here.

**Review by aclevername — APPROVED** [review]

File: pkg/cfn/manager/api.go [hunk 2]
```diff
@@ -474,36 +477,35 @@ func defaultStackStatusFilter() []*string {
...
-		}
+	input := &cloudformation.DeleteStackInput{
+		StackName: s.StackId,
 	}
 
-	return nil, fmt.Errorf("cannot delete stack %q as it doesn't bear our %q, %q tags", *s.StackName,
-		fmt.Sprintf("%s:%s", api.OldClusterNameTag, c.spec.Metadata.Name),
-		fmt.Sprintf("%s:%s", api.ClusterNameTag, c.spec.Metadata.Name))
-}
+	if cfnRole := c.roleARN; cfnRole != "" {
```
Comment (Skarlso) [inline pkg/cfn/manager/api.go:490]: I feel like creating the `cfnRole` variable is a bit of an overkill here. It's not like it's hard to read / type `c.roleARN` or looks too long or whatever. :)

**Review by Skarlso — APPROVED** [review]

File: pkg/cfn/manager/api.go (hunk 2 above)
Comment (cPu1) [reply pkg/cfn/manager/api.go:490]: This line wasn't introduced in this PR, I moved the existing code.

Comment (Skarlso) [reply pkg/cfn/manager/api.go:490]: ah
