### PR TITLE
Fix `get clusters --all-regions`

### LINKED ISSUE #4560: eksctl get clusters, --all-regions flag throws error
**What were you trying to accomplish?**
I was trying to get a list of all my eks clusters in all regions using:
```
eksctl get clusters --all-regions
```

**What happened?**
I left for my vacation on friday, december 17th and this was working. When i returned, this was not working and i was getting an error message as seen below in the logs section. I did not make any changes to anything in that time period.

I can still get my clusters if i specify a region, see "Anything else we need to know?"

**How to reproduce it?**

run 
```
eksctl get clusters --all-regions
```
or
```
eksctl get clusters -A
```

**Logs**

```
adam@xxxxx:~$ eksctl get clusters --all-regions -v 4
2021-12-29 11:51:31 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:33 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:36 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:39 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:42 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:43 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:45 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:48 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:51 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:54 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:51:57 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:00 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:03 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:05 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:07 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:10 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:14 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:16 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:19 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxx:user/adam"
2021-12-29 11:52:21 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 48.593868ms
2021-12-29 11:52:21 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 90.25453ms
2021-12-29 11:52:22 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 187.13548ms
2021-12-29 11:52:22 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 267.625928ms
2021-12-29 11:52:22 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 801.399168ms
2021-12-29 11:52:23 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 1.121728736s
2021-12-29 11:52:25 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 3.650789952s
2021-12-29 11:52:29 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 4.721184128s
2021-12-29 11:52:33 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 11.005962496s
2021-12-29 11:52:45 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 16.937630208s
2021-12-29 11:53:02 [!]  retryable error (RequestError: send request failed
caused by: Get "https://eks.ap-southeast-3.amazonaws.com/clusters?include=all&maxResults=100": dial tcp: lookup eks.ap-southeast-3.amazonaws.com on [2001:558:feed::1]:53: no such host) from eks/ListClusters - will retry after delay of 59.009997824s
```
**Anything else we need to know?**

os: MacOS Monterey version 12.0.1
Processor 2.6 GHz 6-Core Intel Core i7
bash version: GNU bash, version 5.1.12(1)

Are you using a downloaded binary or did you compile eksctl?
I installed eksctl using homebrew

What type of AWS credentials are you using (i.e. default/named profile, MFA)? - please don't include actual credentials though!
default/name profile and MFA. I am authenticating in my shell with an AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

also, when i specify a region, it works:
```
adam@xxxxx:~$ eksctl get clusters --region=us-east-2
2021-12-29 14:03:43 [ℹ]  eksctl version 0.77.0
2021-12-29 14:03:43 [ℹ]  using region us-east-2
NAME			REGION		EKSCTL CREATED
xxxxxxxxx		us-east-2	False
xxxxxxxxx		us-east-2	False
xxxxxxxxx	        us-east-2	False
xxxxxxxxx	        us-east-2	True
```
it is only when i use the --all-regions flag that i get the error.

**Versions**
```
eksctl version: 0.77.0
kubectl version: v1.21.5
OS: darwin
```
I was originally using 0.74 and had the same issue, so I tried updating to the latest version, 0.77, and still had the same issue.

### PR DESCRIPTION
**Pull request by cPu1**
### Description

When an AWS account has access to a region not supported by EKS, `get clusters --all-regions` attempts to query that region for EKS clusters, which fails. This changelist ensures only regions supported by EKS are queried for clusters.

Fixes  #4560 

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/eks/eks.go [hunk 1]
```diff
@@ -330,38 +330,46 @@ func (c *ClusterProvider) loadClusterKubernetesNetworkConfig(spec *api.ClusterCo
...
 // ListClusters returns a list of the EKS cluster in your account
 func (c *ClusterProvider) ListClusters(chunkSize int, listAllRegions bool) ([]*api.ClusterConfig, error) {
-	if listAllRegions {
-		var clusters []*api.ClusterConfig
-		// reset region and re-create the client, then make a recursive call
-		authorizedRegions, err := c.Provider.EC2().DescribeRegions(&ec2.DescribeRegionsInput{})
-		if err != nil {
-			return nil, err
-		}
+	if !listAllRegions {
```
Comment (Skarlso) [inline pkg/eks/eks.go:333]: Please update whatever is in eks_test.go to reflect these changes.

Comment (cPu1) [reply pkg/eks/eks.go:333]: The unit tests will continue to work with these changes as the same AWS API calls are still made. However, I'm working on adding a test case that will fail on `main`.

**Review by Skarlso — APPROVED** [review]
Well done! :)

**Review by nikimanoledaki — APPROVED** [review]
