### PR TITLE
overcome rate limiting of ListStacks calls

### LINKED ISSUE #567: Errors creating and deleting clusters due to CloudFormation throttling
**What happened?**
The `create-cluster` and `delete-cluster` sometimes fail with the error `Throttling: Rate exceeded`, e.g.:
```
2019-02-20T08:15:39Z [▶]  DEBUG: Validate Response cloudformation/ListStacks failed, not retrying, error Throttling: Rate exceeded
	status code: 400, request id: b5210374-...
2019-02-20T08:15:39Z [✖]  getting VPC configuration for cluster "newcluster": describing CloudFormation stacks for "newcluster": Throttling: Rate exceeded
	status code: 400, request id: b5210374-...
```

I enabled the verbose=5 to see AWS requests debugging, and noticed there is a surprisingly high number of `ListStacks` requests:
```
2019-02-20T09:20:52Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:52Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:52Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:53Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:53Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:53Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:53Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:54Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:54Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:54Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:54Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:54Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:55Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:55Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:55Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:55Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:55Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:20:57Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:57Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:57Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:57Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:57Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:58Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:58Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:58Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:58Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:59Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:59Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:20:59Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:00Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:00Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:01Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:01Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:01Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:01Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:01Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:02Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:02Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:03Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:03Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:03Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:03Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:04Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:06Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:10Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:10Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:11Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:13Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:14Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:14Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:14Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:14Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:15Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:15Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:15Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:15Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:15Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:16Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:16Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 200 OK
--
2019-02-20T09:21:16Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:17Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:19Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
--
2019-02-20T09:21:23Z [▶]  DEBUG: Response cloudformation/ListStacks Details:
HTTP/1.1 400 Bad Request
```
(`400 Bad Request` are throttling errors and the AWS SDK retries automatically up to 3 times by default).

I probably haven't looked enough into the code but I'm unsure a `create-cluster` operation should need to list them so many times.

**What you expected to happen?**
The source of all those `ListStacks` requests is reviewed and eventually removed/replace if not needed. There is not much information about the CF API limits, but it seems they are per-account, which means this errors may eventually cause disruptions for other users of the account. E.g. when it happens, I'm even unable to list stacks in the CloudFormation Web UI.

**How to reproduce it?**
Create and delete multiple clusters (I experience that with ~4 concurrent clusters). The reason for doing this is because I provision short-lived EKS clusters, and have control on the max number of concurrent clusters (due to limitations on VPCs and other resources).

**Anything else we need to know?**
I can confirm this issue happens with the Linux binary releases 0.11 and 0.21 (the latest one as of Today), using regular IAM access and secret keys.

### PR DESCRIPTION
**Pull request by errordeveloper**
### Description

This introduces custom retry handler (copied from kops).

I am not sure why `DefaultRetryer` didn't work, but this adds debug logs, so we will get a better idea of when the retry delay kicks in.

Most importantly it adds a built-in filter for non-deleted stacks that is set by default, and removed an extraneous call to `ListStacks`.

This fixes #567.

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)

### CODE REVIEW

**Comment by christopherhein** [comment]
LGTM! Nice work @errordeveloper

File: pkg/eks/logging_retryer.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+// LoggingRetryer adds some logging when we are retrying, so we have some idea what is happening
+// Right now it is very basic - e.g. it only logs when we retry (so doesn't log when we fail due to too many retries)
+// It was copied from k8s.io/kops/upup/pkg/fi/cloudup/awsup/logging_retryer.go; the original version used glog, and
+// didn't export the constructor
+type LoggingRetryer struct {
+	client.DefaultRetryer
+}
+
+var _ request.Retryer = &LoggingRetryer{}
```
Comment (martina-if) [inline pkg/eks/logging_retryer.go]: what is this variable here? Is it used? Is it supposed to be here?

Comment (errordeveloper) [reply pkg/eks/logging_retryer.go]: It is a common way of validating that given struct implements the interface.

Comment (errordeveloper) [reply pkg/eks/logging_retryer.go]: It is a common way of validating that given struct implements the interface.

Comment (martina-if) [reply pkg/eks/logging_retryer.go]: Ah, ok, thanks
