### PR TITLE
Fix nodegroup filter bug (#2276)

### LINKED ISSUE #2276: include/exclude rules misbehaved and deleted all nodegroups
**What happened?**
When performing regular maintenance and rotation/upgrades on a cluster I was in the process of rotating nodegroups once at a time, when eksctl decided to "delete" all nodegroups unexpectedly.

**What you expected to happen?**
When I give inclusive/exclusive rules it follows the expected and documented use-case.  Admittedly, I should have every single time ran without `--approve` just to verify and validate what it would do.  While that seems overly cautious, in the future I will run without approve and will intentionally add --exclude rules for every other nodegroup just for paranoia's sake.  This absolutely can not happen to a client of mine or anyone's again.  I believe this to be a bug in the inclusive/exclusive logic.

**How to reproduce it?**
I don't know how to recommend how to reproduce this, but I can confirm my eksctl repeatedly had this problem for a while.  Right now if I want to use an inclusive rule only (which would normally by default exclude everything else) it does not do this.  It grabs all nodegroups.  (See below)

This was my usage path, copy/pasted from my terminal...

```bash
# Created a new nodegroup named 'k8s-1a-m5ad-xlarge-primary' to replace an existing one 'k8s-1a-m5ad-xlarge'
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1a-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1a-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted JUST the old one...
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1a-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1a-m5ad-xlarge) was included (based on the include/exclude rules)
# Created another new node group to replace one in the 1b AZ
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1b-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1b-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted the old nodegroup
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1b-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1b-m5ad-xlarge) was included (based on the include/exclude rules)
# Created a third nodegroup
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1c-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted the old nodegroup
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge) was included (based on the include/exclude rules)
# Now, on the following node-group I didn't care about needing it highly available since it was a special-purpose nodegroup with no "live" resources on it...
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1a-highmem" --approve
[ℹ]  4 nodegroups (k8s-1a-highmem, k8s-1a-m5ad-xlarge-primary, k8s-1b-m5ad-xlarge-primary, k8s-1c-m5ad-xlarge-primary) were included (based on the include/exclude rules)
```

And right now, no matter what I do, the old logic of single-inclusive being exclusive by default automatically seems to include all items...

```bash
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge"
[ℹ]  4 nodegroups (k8s-1a-r5a-2xlarge-highmem, k8s-1b-m5ad-xlarge-primary, k8s-1c-m5ad-xlarge, k8s-1c-m5ad-xlarge-primary) were included (based on the include/exclude rules)
```

So to make things work properly if I want to rotate/delete a nodegroup right now I have to...

```bash
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge" --exclude "k8s-1a-r5a-2xlarge-highmem" --exclude "k8s-1b-m5ad-xlarge-primary" --exclude "k8s-1c-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge) was included (based on the include/exclude rules)
```

**Anything else we need to know?**
This has severely put a bad taste in my mouth for this tool.  This caused a brief outage of my customer just now.  

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.18.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Log**
Debug Log: https://gist.github.com/AndrewFarley/17a5c403b954ea84f1ae9dee956544c0
Config File: https://gist.github.com/AndrewFarley/7497aed22915210e0df4c975828ecb6b

### PR DESCRIPTION
**Pull request by martina-if**
fixes #2276

When a nodegroup exists in the cluster but not in the config file that creates an implicit exclusion
rule that was triggering a behavior that biased the logic towards including ngs that did not match
any given filter.

I rewrote part of the logic and the tests, and included a regression test. I believe this is a bit
easier to understand but the filter should probably be rewritten in a simpler way.

- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

This was a first refactor of this logic. But this should be simplified more after creating a common interface for `Nodegroup`s and `ManagedNodegroup`s which will simplify the implementation of the filter and other parts of the codebase.

## Testing

<details>
<summary> Before </summary>

```
eksctl delete nodegroup -f ../clusters/martina-test-2276.yaml --include=1c-m5ad-xlarge 
[ℹ]  eksctl version 0.23.0-dev+b283537b.2020-06-26T17:32:10Z
[ℹ]  using region eu-north-1
[ℹ]  comparing 6 nodegroups defined in the given config ("../clusters/martina-test-2276.yaml") against remote state
[ℹ]  nodegroup "blah" present in the given config, but missing in the cluster
[ℹ]  combined include rules: 1c-m5ad-xlarge
[ℹ]  5 nodegroups (1a-m5ad-xlarge-primary, 1a-r5a-2xlarge-highmem, 1b-m5ad-xlarge-primary, 1c-m5ad-xlarge, 1c-m5ad-xlarge-primary) were included (based on the include/exclude rules)
[ℹ]  combined exclude rules: blah
[ℹ]  1 nodegroup (blah) was excluded (based on the include/exclude rules)
[ℹ]  (plan) would drain 5 nodegroup(s) in cluster "martina-test-2276"
[ℹ]  (plan) would delete 5 nodegroups from cluster "martina-test-2276"
[ℹ]  (plan) 5 parallel tasks: { delete nodegroup "1c-m5ad-xlarge" [async], delete nodegroup "1a-r5a-2xlarge-highmem" [async], delete nodegroup "1c-m5ad-xlarge-primary" [async], delete nodegroup "1a-m5ad-xlarge-primary" [async], delete nodegroup "1b-m5ad-xlarge-primary" [async] }
[ℹ]  (plan) would delete 5 nodegroups from auth ConfigMap in cluster "martina-test-2276"
[✔]  (plan) would have deleted 5 nodegroup(s) from cluster "martina-test-2276"
[!]  no changes were applied, run again with '--approve' to apply the changes

```
</details>

<details>
<summary> After </summary>

```
 eksctl create nodegroup -f ../clusters/martina-test-2276.yaml --include=1c-m5ad-xlarge
[ℹ]  eksctl version 0.24.0-dev+4d1b5be4.2020-06-29T12:24:25Z
[ℹ]  using region eu-north-1
[ℹ]  will use version 1.15 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "1c-m5ad-xlarge" present in the given config, but missing in the cluster
[ℹ]  nodegroup "blah" present in the given config, but missing in the cluster
[ℹ]  nodegroup "1c-m5ad-xlarge" will use "ami-0d6711173ab77aaf9" [AmazonLinux2/1.15]
[!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: bee5b200-04a6-4ceb-ae0c-cdbc682a1473) from cloudformation/DescribeStacks - will retry after delay of 663.837106ms
[ℹ]  combined include rules: 1c-m5ad-xlarge
[ℹ]  1 nodegroup (1c-m5ad-xlarge) was included (based on the include/exclude rules)
[ℹ]  5 nodegroups (1a-m5ad-xlarge-primary, 1a-r5a-2xlarge-highmem, 1b-m5ad-xlarge-primary, 1c-m5ad-xlarge-primary, blah) were excluded (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "martina-test-2276"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "1c-m5ad-xlarge" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-martina-test-2276-nodegroup-1c-m5ad-xlarge"
[ℹ]  --nodes-min=2 was set automatically for nodegroup 1c-m5ad-xlarge
[ℹ]  --nodes-max=2 was set automatically for nodegroup 1c-m5ad-xlarge
[ℹ]  deploying stack "eksctl-martina-test-2276-nodegroup-1c-m5ad-xlarge"
[ℹ]  no tasks
[ℹ]  adding identity "arn:aws:iam::083751696308:role/eksctl-martina-test-2276-nodegrou-NodeInstanceRole-MBAACXVF2MLD" to auth ConfigMap
[ℹ]  nodegroup "1c-m5ad-xlarge" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "1c-m5ad-xlarge"
[ℹ]  nodegroup "1c-m5ad-xlarge" has 2 node(s)
[ℹ]  node "ip-192-168-44-143.eu-north-1.compute.internal" is ready
[ℹ]  node "ip-192-168-85-141.eu-north-1.compute.internal" is ready
[✔]  created 1 nodegroup(s) in cluster "martina-test-2276"
[✔]  created 0 managed nodegroup(s) in cluster "martina-test-2276"
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration



$ eksctl delete nodegroup -f ../clusters/martina-test-2276.yaml --include=1c-m5ad-xlarge
[ℹ]  eksctl version 0.24.0-dev+4d1b5be4.2020-06-29T12:24:25Z
[ℹ]  using region eu-north-1
[ℹ]  comparing 6 nodegroups defined in the given config ("../clusters/martina-test-2276.yaml") against remote state
[ℹ]  combined include rules: 1c-m5ad-xlarge
[ℹ]  1 nodegroup (1c-m5ad-xlarge) was included (based on the include/exclude rules)
[ℹ]  5 nodegroups (1a-m5ad-xlarge-primary, 1a-r5a-2xlarge-highmem, 1b-m5ad-xlarge-primary, 1c-m5ad-xlarge-primary, blah) were excluded (based on the include/exclude rules)
[ℹ]  (plan) would drain 1 nodegroup(s) in cluster "martina-test-2276"
[ℹ]  (plan) would delete 1 nodegroups from cluster "martina-test-2276"
[ℹ]  (plan) 1 task: { delete nodegroup "1c-m5ad-xlarge" [async] }
[ℹ]  (plan) would delete 1 nodegroups from auth ConfigMap in cluster "martina-test-2276"
[✔]  (plan) would have deleted 1 nodegroup(s) from cluster "martina-test-2276"
[!]  no changes were applied, run again with '--approve' to apply the changes

```
</details>

### CODE REVIEW

File: pkg/ctl/cmdutils/filter/nodegroup_filter.go [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+		return included, excluded
+	}
+
+	return matching, notMatching
+}
+
+// Match decides whether the given nodegroup is considered included by this filter. It takes into account not only the
+// inclusion and exclusion rules (globs) but also the modifiers onlyRemote and onlyLocal.
+func (f *NodeGroupFilter) Match(ngName string) bool {
+	if f.onlyRemote {
```
Comment (michaelbeaumont) [inline pkg/ctl/cmdutils/filter/nodegroup_filter.go:163]: this could also be implemented using `MatchAll([ngName])`

File: pkg/ctl/cmdutils/filter/nodegroup_filter.go [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+}
+
+func (f *NodeGroupFilter) onlyRemoteNodegroups() sets.String {
+	return f.remoteNodegroups.Difference(f.localNodegroups)
+}
+
+// FilterMatching matches names against the filter and returns all included node groups
+func (f *NodeGroupFilter) FilterMatching(nodeGroups []*api.NodeGroup) []*api.NodeGroup {
+	var match []*api.NodeGroup
+	for _, ng := range nodeGroups {
```
Comment (michaelbeaumont) [inline pkg/ctl/cmdutils/filter/nodegroup_filter.go:191]: The Filter and ForEach functions too

**Comment by martina-if** [comment]
> Is this a breaking change?

It could be considered breaking.... The UX is the same but the behavior of the filter is different so that things that were included before now they may not be (since now exclusion takes precedence over inclusion). The perfect example is the bug fix itself: things were included by default if not explicitly excluded and that made the user delete a bunch of nodegroups.

**Comment by whereisaaron** [comment]
AFAIK `--include` and `--exclude` are only used for config files. So I would expect a `delete` using `--include` and `--exclude` would only apply to items in the config file. I would be surprised if `eksctl delete` using `--include` and `--exclude` tried to create/delete something not in the config file.

Regards simpler logic. rather than treating one of the otherwise symmetric semantics, as special or preferential, we could treat them normally and process them in order. Simpler logic and more concise expressions. Also the user doesn't need to know the special implicit semantics.

Assuming doing nothing is the starting point, every filter starts with `--exclude *`, or the selection set is empty, however you want to look at it. You could argue that this itself is special/implicit semantics, but a user in doubt can simply start their filter option with `--exclude *` or `--include *` and be confident of the outcome.

`bird`
`cat`
`dog`
`cow`

- `--exclude * --include cat` -> `cat`
- `--exclude * --exclude cat` --> ``
- `--exclude * --exclude cat --include cat` --> `cat`
- `--exclude * --include cat --include cat` --> `cat`
- `--exclude * --include cat --exclude cat` --> ``
- `--exclude * --include c*` --> `cat, cow`
- `--exclude * --exclude c*` --> ``
- `--exclude * --include *` --> `bird, cat, dog, cow`
- `--exclude * --exclude *` --> ``
- `--exclude * --include * --exclude c*` --> `bird, dog`
- `--exclude * --include * --exclude c* --include cow` --> `bird, dog, cow`
- `--exclude * --include *o* --exclude c*` --> `dog`
- `--exclude * --include *o* --exclude c* --include cow` --> `dog, cow`
etc.

**Comment by martina-if** [comment]
Hi @aaronjwood thanks for your insights!

> So I would expect a delete using --include and --exclude would only apply to items in the config file. I would be surprised if eksctl delete using --include and --exclude tried to create/delete something not in the config file.

I would imagine this too but there is also the flag `--only-missing` which applies to nodegroups in the cluster that are not present in the config file. In that case we need to also need to filter by `--include` and `--exclude`.

Regarding the order, I thought about that but I don't think we have a good way to know in which order these flags were given and I didn't want to change the UX too much. I will keep this in mind for when we have version in place because I think it's more intuitive.
