### PR TITLE
Fix authorization error check from Fargate

### LINKED ISSUE #5319: [Bug] eksctl 0.98.0 throws error about Fargate in AWS China on delete
When running eksctl in AWS China partition (aws-cn), running `eksctl delete cluster` now throws an error and the process stops:

```
Error: failed to get Fargate profile(s) for cluster "my-cluster": operation error EKS: ListFargateProfiles, https response error StatusCode: 403, RequestID: 851072a6-f8a5-4c5b-aed5-a55c8777e97f, api error AccessDeniedException: Account <redacted> is not authorized to use this service
```

This is a regression in eksctl 0.98.0 (after migrating to SDK v2). Version 0.97.0 works fine.
Also, 0.98.0 doesn't have this problem on creation - only deletion is affected.

Note the following:
- Role has `eks:*` permissions for all resources
- [EKS Fargate is not supported in AWS China](https://docs.amazonaws.cn/en_us/aws/latest/userguide/eks.html)

In comparison, version 0.97.0 just prints an info message and proceeds with deletion:

```
[ℹ]  either account is not authorized to use Fargate or region cn-north-1 is not supported. Ignoring error
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #5319

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by nikimanoledaki — APPROVED** [review]

File: pkg/fargate/fargate.go [hunk 1]
```diff
@@ -61,6 +62,6 @@ func toSelectors(in []ekstypes.FargateProfileSelector) []api.FargateProfileSelec
 // Unauthorized errors are of the form:
 //   AccessDeniedException: Account <account> is not authorized to use this service
 func IsUnauthorizedError(err error) bool {
-	var accessDeniedErr *ekstypes.AccessDeniedException
-	return errors.As(err, &accessDeniedErr)
+	var apiErr smithy.APIError
+	return errors.As(err, &apiErr) && apiErr.ErrorCode() == "AccessDeniedException"
```
Comment (Himangini) [inline pkg/fargate/fargate.go:66]: should we add a test for this?

Comment (cPu1) [reply pkg/fargate/fargate.go:66]: The error is constructed by the AWS SDK from the HTTP response, it'd require mimicking the SDK logic.
