### PR TITLE
Fix cluster DNS for non-default ServiceIPv4CIDRs and Bottlerocket support in private clusters

### LINKED ISSUE #3719: Create EKS Fully-Private cluster with bottlerocket
**What were you trying to accomplish?**

I would like to create a EKS Fully-Private cluster with **bottlerocket** using eksctl. However, it seems the bottlerocket worker nodes are not able to join the cluster. 

**What happened?**

I can see the error message `Error: timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "self"` after the worker node stack been created :
```
2021-05-18 10:31:43 [ℹ]  building nodegroup stack "eksctl-test-nodegroup-self"
2021-05-18 10:31:43 [ℹ]  --nodes-min=2 was set automatically for nodegroup self
2021-05-18 10:31:43 [ℹ]  --nodes-max=2 was set automatically for nodegroup self
2021-05-18 10:31:46 [ℹ]  deploying stack "eksctl-test-nodegroup-self"
2021-05-18 10:31:46 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:32:04 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:32:22 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:32:39 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:32:59 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:33:16 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:33:34 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:33:54 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:34:10 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:34:30 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:34:46 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:35:04 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:35:23 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:35:42 [ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-self"
2021-05-18 10:35:43 [ℹ]  waiting for the control plane availability...
2021-05-18 10:35:43 [✔]  saved kubeconfig as "/Users/josh/.kube/config"
2021-05-18 10:35:43 [ℹ]  no tasks
2021-05-18 10:35:43 [✔]  all EKS cluster resources for "test" have been created
2021-05-18 10:35:44 [ℹ]  adding identity "arn:aws:iam::<Account>:role/eksctl-test-nodegroup-sel-NodeInstanceRole-181GOSNF3D564" to auth ConfigMap
2021-05-18 10:35:45 [ℹ]  nodegroup "self" has 0 node(s)
2021-05-18 10:35:45 [ℹ]  waiting for at least 2 node(s) to become ready in "self"
Error: timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "self"
```

**How to reproduce it?**
1. I am using the following template from the [example](https://github.com/weaveworks/eksctl/blob/main/examples/20-bottlerocket.yaml)  and adding `privateCluster` section: 
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-west-2

privateCluster:
  enabled: true
  additionalEndpointServices:
  - 'autoscaling'
  - 'logs'

nodeGroups:
  - name: self
    instanceType: m5.xlarge
    privateNetworking: true
    desiredCapacity: 1
    amiFamily: Bottlerocket
    labels:
      "network-locality.example.com/public": "true"
    bottlerocket:
      enableAdminContainer: true
      settings:
        motd: "Hello, eksctl!"

```

2. using the following command to create the EKS cluster : 
```
$ eksctl create cluster -f cluster_config.yml
```

**Versions**

```
$ eksctl version
0.49.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-cf75c9", GitCommit:"cf75c9601ec63a63ba54c1c47caa9945af1f3a81", GitTreeState:"clean", BuildDate:"2021-02-13T00:14:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

May I know if it is the expected behavior ? 
I can create the EKS cluster and worker node successfully without adding `privateCluster`.

### LINKED ISSUE #3864: Cluster DNS does not work with a non-default ServiceIPv4CIDR
When a custom ServiceIPv4CIDR is set, DNS in the cluster does not work. 

Example config:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test
  region: us-west-2
  version: "1.20"

kubernetesNetworkConfig:
  serviceIPv4CIDR: 172.16.0.0/12
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes cluster DNS for non-default ServiceIPv4CIDRs and Bottlerocket support in private clusters.

Fixes #3719 

Fixes #3864 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: integration/tests/cluster_dns/cluster_dns_test.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+					NodeGroupBase: &api.NodeGroupBase{
+						Name: "dns",
+						ScalingConfig: &api.ScalingConfig{
+							DesiredCapacity: aws.Int(1),
+						},
+					},
+				},
+			}
+
+			cmd := params.EksctlCreateCmd.WithArgs(
```
Comment (Callisto13) [inline integration/tests/cluster_dns/cluster_dns_test.go:56]: can you add the check for if the `SkipCreate` check around this?

File: integration/tests/cluster_dns/cluster_dns_test.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+			Expect(err).ToNot(HaveOccurred())
+			d := test.CreateDaemonSetFromFile(test.Namespace, "../../data/test-dns.yaml")
+			test.WaitForDaemonSetReady(d, 2*time.Minute)
+			ds, err := test.GetDaemonSet(test.Namespace, d.Name)
+			Expect(err).ToNot(HaveOccurred())
+			fmt.Fprintf(GinkgoWriter, "ds.Status = %#v", ds.Status)
+		})
+
+		AfterSuite(func() {
+			cmd := params.EksctlDeleteCmd.WithArgs(
```
Comment (Callisto13) [inline integration/tests/cluster_dns/cluster_dns_test.go:79]: likewise a check for the `SkipDelete` param

File: integration/tests/cluster_dns/cluster_dns_test.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+}
+
+func TestClusterDNS(t *testing.T) {
+	testutils.RegisterAndRun(t)
+}
+
+var _ = Describe("(Integration) [Cluster DNS test]", func() {
+
+	Context("Cluster with non-default ServiceIPv4CIDR", func() {
+		BeforeSuite(func() {
```
Comment (Callisto13) [inline integration/tests/cluster_dns/cluster_dns_test.go:37]: are `XSuite` funcs supposed to live inside the actual test? 🤔  I know that _can_ but I think it is convention to put them outside the `Describe` at suite level

File: pkg/nodebootstrap/userdata.go [hunk 4]
```diff
@@ -77,6 +86,21 @@ func NewManagedBootstrapper(clusterConfig *api.ClusterConfig, ng *api.ManagedNod
 	return nil
 }
 
+func getClusterDNS(clusterConfig *api.ClusterConfig) (string, error) {
```
Comment (Callisto13) [inline pkg/nodebootstrap/userdata.go:89]: is this path tested?

File: pkg/apis/eksctl.io/v1alpha5/types.go [hunk 5]
```diff
@@ -728,6 +732,23 @@ func (c *ClusterConfig) AppendAvailabilityZone(newAZ string) {
 	c.AvailabilityZones = append(c.AvailabilityZones, newAZ)
 }
 
+// SetClusterStatus populates ClusterStatus using *eks.Cluster.
+func (c *ClusterConfig) SetClusterStatus(cluster *eks.Cluster) error {
+	if networkConfig := cluster.KubernetesNetworkConfig; networkConfig != nil && networkConfig.ServiceIpv4Cidr != nil {
+		c.Status.KubernetesNetworkConfig = &KubernetesNetworkConfig{
```
Comment (Callisto13) [inline pkg/apis/eksctl.io/v1alpha5/types.go:738]: are we adding this to the status for just "display purposes"? i can't see this status field being used anywhere, have i missed it

Comment (cPu1) [reply pkg/apis/eksctl.io/v1alpha5/types.go:738]: It's used in `getClusterDNS`.

File: pkg/nodebootstrap/userdata.go (hunk 4 above)
Comment (cPu1) [reply pkg/nodebootstrap/userdata.go:89]: Yes: https://github.com/weaveworks/eksctl/pull/3867/files#diff-7fffb935439e217b3a7c5100d1de60b26e2d8c71d525e80c6c00bf477b3a9bb0R135

File: integration/tests/cluster_dns/cluster_dns_test.go (hunk 3 above)
Comment (cPu1) [reply integration/tests/cluster_dns/cluster_dns_test.go:37]: They're typically defined at the top-level for global initialisation but we also have some tests defining it in a `Describe` block. I  chose to define it this way because it's also testing the `create cluster` functionality with a custom `ServiceIPv4CIDR` and having it in a `Describe` block lets you provide more context for the test. I was going to use `BeforeEach` but our integration tests have been using `BeforeSuite` for cluster creation.

File: pkg/nodebootstrap/userdata.go (hunk 4 above)
Comment (Callisto13) [reply pkg/nodebootstrap/userdata.go:89]: can we add some more coverage? it looks like that test is only doing happy path, and that it ends up in the userdata so it is technically testing 2 things.

Or maybe move the test of this to another location? like `pkg/nodebootstrap/userdata_test.go` or smth. The DNS thing will run for every call of `NewBootstrapper`, not in the `UserData` call, and not for just al2.
We didn't have tests for `NewBootstrapper` before since it wasn't really doing anything. Now it actually does something, we can have a test (or 3 to cover all cases introduced by this func) at a different "level".

Comment (cPu1) [reply pkg/nodebootstrap/userdata.go:89]: Makes sense, there does need to be a dedicated test for cluster DNS.

**Review by Callisto13 — APPROVED** [review]
LGTM
