### PR TITLE
Ignore IAM OIDC errors if no OIDC provider is associated with cluster

### LINKED ISSUE #5289: [Bug] EKS is not integrated with OIDC Provider, but it's doing Get OpenID call
EKS is not integrated with OIDC Provider, but it's doing Get OpenID call because of which the deletion is failing. The main issue is this role is blocked by the IT team

```
eksctl version 0.97.0
using region us-east-1
deleting EKS cluster "test"
will drain 0 unmanaged nodegroup(s) in cluster "test"
deleted 0 Fargate profile(s)
kubeconfig has been updated
cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: operation error IAM: GetOpenIDConnectProvider, https response error StatusCode: 403, RequestID: e08bc362-77c7-4aba-a5cb-9e888885b484, api error AccessDenied: User: arn:aws:sts::485443633092:assumed-role/EksctlRole-BCGSSRVAC970/AWSCodeBuild-670ebbbbbbbbbb3d-7a3ba6ee3300 is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::00000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/4FC3F00000797DAEAF1103D8027 with an explicit deny in a permissions boundary
````

### PR DESCRIPTION
**Pull request by cPu1**
### Description

This changelist tags the cluster with the value of `iam.withOIDC` to allow eksctl to determine during cluster deletion if an OIDC provider was associated with the cluster or not. Upon encountering an IAM permissions error, it throws an error if the cluster has an OIDC provider associated with it, which is determined either by the tag, or by the presence of IAM service accounts for clusters that lack the tag. 

Closes #5289

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/cfn/manager/delete_tasks.go [hunk 1]
```diff
@@ -178,26 +181,60 @@ func (c *StackCollection) NewTaskToDeleteUnownedNodeGroup(ctx context.Context, c
...
+					logger.Warning("expected an OIDC provider to be associated with the cluster; found %d service account(s)", len(allServiceAccountsWithStacks))
+				}
+			case len(allServiceAccountsWithStacks) > 0:
+				if !force {
+					return nil, fmt.Errorf("found %d IAM service account(s); %s: %w", len(allServiceAccountsWithStacks), errMsg, err)
+				}
+			default:
+				logger.Info("could not determine if cluster has an OIDC provider because IAM permissions are missing; " +
+					"if an OIDC provider was associated with the cluster (either by setting `iam.withOIDC: true` or by using `eksctl utils associate-iam-oidc-provider`), " +
+					"run `aws iam delete-open-id-connect-provider` from an authorized IAM entity")
```
Comment (Skarlso) [inline pkg/cfn/manager/delete_tasks.go:234]:
```suggestion
					"run `aws iam delete-open-id-connect-provider` from an authorised IAM entity to clean up remaining resources")
```

File: pkg/ctl/utils/associate_iam_oidc_provider.go [hunk 2]
```diff
@@ -83,3 +92,16 @@ func doAssociateIAMOIDCProvider(cmd *cmdutils.Cmd) error {
...
+func addOIDCTag(ctx context.Context, provider api.ClusterProvider, cluster *ekstypes.Cluster) error {
+	_, err := provider.EKS().TagResource(ctx, &eks.TagResourceInput{
+		ResourceArn: cluster.Arn,
+		Tags: map[string]string{
+			api.ClusterOIDCEnabledTag: "true",
+		},
+	})
+	if err != nil {
+		return fmt.Errorf("error tagging EKS cluster with OIDC tag: %w", err)
+	}
```
Comment (Skarlso) [inline pkg/ctl/utils/associate_iam_oidc_provider.go:105]:
```suggestion
	if _, err := provider.EKS().TagResource(ctx, &eks.TagResourceInput{
		ResourceArn: cluster.Arn,
		Tags: map[string]string{
			api.ClusterOIDCEnabledTag: "true",
		},
	}); err != nil {
		return fmt.Errorf("error tagging EKS cluster with OIDC tag: %w", err)
	}
```

**Review by Skarlso — COMMENTED** [review]
Think generally this is fine. Would you mind including a manual run with the permission error to see that everything is fine? Thanks. :)

File: pkg/cfn/manager/delete_tasks.go (hunk 1 above)
Comment (cPu1) [reply pkg/cfn/manager/delete_tasks.go:234]: We have more usages of the US variant of the spelling. Good suggestion on adding the cleanup part, although I'm thinking of:

```suggestion
					"run `aws iam delete-open-id-connect-provider` from an authorized IAM entity to delete the OIDC provider")
```

**Comment by cPu1** [comment]
> Think generally this is fine. Would you mind including a manual run with the permission error to see that everything is fine? Thanks. :)

Ah, I tested it manually yesterday but our cleanup scripts removed the cluster. I did verify that the error is propagated and the messages are logged. I can open a new ticket to add integration tests.

File: pkg/cfn/manager/delete_tasks.go [hunk 3]
```diff
@@ -178,26 +181,60 @@ func (c *StackCollection) NewTaskToDeleteUnownedNodeGroup(ctx context.Context, c
...
+				}
+				if len(allServiceAccountsWithStacks) > 0 {
+					logger.Warning("expected an OIDC provider to be associated with the cluster; found %d service account(s)", len(allServiceAccountsWithStacks))
+				}
+			case len(allServiceAccountsWithStacks) > 0:
+				if !force {
+					return nil, fmt.Errorf("found %d IAM service account(s); %s: %w", len(allServiceAccountsWithStacks), errMsg, err)
+				}
+			default:
+				logger.Info("could not determine if cluster has an OIDC provider because IAM permissions are missing; " +
```
[the remark this answers is not in the document]
Comment (cPu1) [reply pkg/cfn/manager/delete_tasks.go:232]: I don't think "the" is required here.

**Review by Skarlso — APPROVED** [review]

File: pkg/cfn/manager/delete_tasks.go (hunk 1 above)
Comment (cPu1) [reply pkg/cfn/manager/delete_tasks.go:234]: I have changed it to:

```suggestion
					"run `aws iam delete-open-id-connect-provider` from an authorized IAM entity to delete it")
```


so now the message is "if an OIDC provider was associated with the cluster (either by setting `iam.withOIDC: true` or by using `eksctl utils associate-iam-oidc-provider`), run `aws iam delete-open-id-connect-provider` from an authorized IAM entity to delete it".

File: pkg/actions/cluster/unowned.go [hunk 4]
```diff
@@ -191,14 +180,14 @@ func (c *UnownedCluster) deleteIAMAndOIDC(ctx context.Context, wait bool, cluste
 		}
 	}
 
-	deleteAddonIAMtasks, err := c.stackManager.NewTaskToDeleteAddonIAM(ctx, wait)
+	deleteAddonIAMTasks, err := c.stackManager.NewTaskToDeleteAddonIAM(ctx, wait)
```
Comment (Himangini) [inline pkg/actions/cluster/unowned.go:183]: ⭐

File: pkg/actions/cluster/unowned.go [hunk 5]
```diff
@@ -277,7 +266,7 @@ func (c *UnownedCluster) deleteAndWaitForNodegroupsDeletion(ctx context.Context,
 		}
 
 		if isUnowned() {
-			// if a managed ng does not have a stack, we queue if for deletion via api
+			// if a managed ng does not have a stack, we queue it for deletion via api
```
Comment (Himangini) [inline pkg/actions/cluster/unowned.go:269]: ⭐ ⭐

**Review by Himangini — APPROVED** [review]
👍🏻 lgtm
