### PR TITLE
Fix launch template errors

### LINKED ISSUE #1257: instance type t2.medium is not compatible with EBS-optimised setting
This currently breaks our integration test.

```
------------------------------
(Integration) Create, Get, Scale & Delete when creating a cluster with 1 node 
  should not return an error
  /Users/ilya/Code/eksctl/integration/creategetdelete_test.go:63
Using kubeconfig: /Users/ilya/Code/eksctl/integration/kubeconfig-230267087
starting '../eksctl "--region" "us-west-2" "create" "cluster" "--verbose" "4" "--name" "wonderful-wardrobe-1567503606" "--tags" "alpha.eksctl.io/description=eksctl integration test" "--nodegroup-name" "ng-0" "--node-labels" "ng-name=ng-0" "--node-type" "t2.medium" "--nodes" "1" "--version" "1.13" "--kubeconfig" "/Users/ilya/Code/eksctl/integration/kubeconfig-230267087"'

... 

2019-09-03T10:57:36+01:00 [✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. EBS-optimized instances are not supported for your requested configuration. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 3d1709ce-ce31-11e9-9b09-77f465522aa6)"
```

### LINKED ISSUE #1293: Error: You must use a valid fully-formed launch template
I'm getting this issue deploying using `eksctl` as of today. I've made no changes to my deployment scripts:

> You must use a valid fully-formed launch template. EBS-optimized instances are not supported for your requested configuration. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: a6251170-cfe8-11e9-ae88-234007dafb6a)

My `eksctl` command is:

```
AWS_REGION=us-east-1 /usr/local/bin/eksctl create cluster --region=us-east-1 --node-type=t2.medium --zones=us-east-1a,us-east-1b,us-east-1d --verbose=4 >> /var/log/eksctl.log 2>&1
```

My `eksctl` is pulled from https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_linux_amd64.tar.gz at deployment time.

Full verbose output:

```
# cat eksctl.log
2019-09-05T14:07:25Z [ℹ]  using region us-east-1
2019-09-05T14:07:25Z [▶]  role ARN for the current session is "arn:aws:iam::595721378487:user/cloud_user"
2019-09-05T14:07:25Z [▶]  VPC CIDR (192.168.0.0/16) was divided into 8 subnets [192.168.0.0/19 192.168.32.0/19 192.168.64.0/19 192.168.96.0/19 192.168.128.0/19 192.168.160.0/19 192.168.192.0/19 192.168.224.0/19]
2019-09-05T14:07:25Z [ℹ]  subnets for us-east-1a - public:192.168.0.0/19 private:192.168.96.0/19
2019-09-05T14:07:25Z [ℹ]  subnets for us-east-1b - public:192.168.32.0/19 private:192.168.128.0/19
2019-09-05T14:07:25Z [ℹ]  subnets for us-east-1d - public:192.168.64.0/19 private:192.168.160.0/19
2019-09-05T14:07:25Z [▶]  resolving AMI using StaticGPUResolver for region us-east-1, instanceType t2.medium and imageFamily AmazonLinux2
2019-09-05T14:07:25Z [▶]  can't resolve AMI using StaticGPUResolver as instance type t2.medium is non-GPU
2019-09-05T14:07:25Z [▶]  resolving AMI using StaticDefaultResolver for region us-east-1, version 1.13, instanceType t2.medium and imageFamily AmazonLinux2
2019-09-05T14:07:25Z [ℹ]  nodegroup "ng-8d360547" will use "ami-0d3998d69ebe9b214" [AmazonLinux2/1.13]
2019-09-05T14:07:25Z [ℹ]  using Kubernetes version 1.13
2019-09-05T14:07:25Z [ℹ]  creating EKS cluster "beautiful-unicorn-1567692445" in "us-east-1" region
2019-09-05T14:07:25Z [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "beautiful-unicorn-1567692445",
        "region": "us-east-1",
        "version": "1.13"
    },
    "iam": {
        "withOIDC": false
    },
    "vpc": {
        "cidr": "192.168.0.0/16",
        "subnets": {
            "private": {
                "us-east-1a": {
                    "cidr": "192.168.96.0/19"
                },
                "us-east-1b": {
                    "cidr": "192.168.128.0/19"
                },
                "us-east-1d": {
                    "cidr": "192.168.160.0/19"
                }
            },
            "public": {
                "us-east-1a": {
                    "cidr": "192.168.0.0/19"
                },
                "us-east-1b": {
                    "cidr": "192.168.32.0/19"
                },
                "us-east-1d": {
                    "cidr": "192.168.64.0/19"
                }
            }
        },
        "autoAllocateIPv6": false,
        "nat": {
            "gateway": "Single"
        }
    },
    "nodeGroups": [
        {
            "name": "ng-8d360547",
            "ami": "ami-0d3998d69ebe9b214",
            "amiFamily": "AmazonLinux2",
            "instanceType": "t2.medium",
            "privateNetworking": false,
            "securityGroups": {
                "withShared": true,
                "withLocal": true
            },
            "volumeSize": 0,
            "volumeType": "gp2",
            "volumeName": "/dev/xvda",
            "volumeEncrypted": false,
            "volumeIOPS": null,
            "labels": {
                "alpha.eksctl.io/cluster-name": "beautiful-unicorn-1567692445",
                "alpha.eksctl.io/nodegroup-name": "ng-8d360547"
            },
            "ssh": {
                "allow": false
            },
            "iam": {
                "withAddonPolicies": {
                    "imageBuilder": false,
                    "autoScaler": false,
                    "externalDNS": false,
                    "certManager": false,
                    "appMesh": false,
                    "ebs": false,
                    "fsx": false,
                    "efs": false,
                    "albIngress": false,
                    "xRay": false,
                    "cloudWatch": false
                }
            }
        }
    ],
    "availabilityZones": [
        "us-east-1a",
        "us-east-1b",
        "us-east-1d"
    ],
    "cloudWatch": {
        "clusterLogging": {}
    }
}

2019-09-05T14:07:25Z [ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
2019-09-05T14:07:25Z [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --name=beautiful-unicorn-1567692445'
2019-09-05T14:07:25Z [ℹ]  CloudWatch logging will not be enabled for cluster "beautiful-unicorn-1567692445" in "us-east-1"
2019-09-05T14:07:25Z [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-1 --name=beautiful-unicorn-1567692445'
2019-09-05T14:07:25Z [ℹ]  2 sequential tasks: { create cluster control plane "beautiful-unicorn-1567692445", create nodegroup "ng-8d360547" }
2019-09-05T14:07:25Z [▶]  started task: create cluster control plane "beautiful-unicorn-1567692445"
2019-09-05T14:07:25Z [ℹ]  building cluster stack "eksctl-beautiful-unicorn-1567692445-cluster"
2019-09-05T14:07:25Z [▶]  CreateStackInput = {
  Capabilities: ["CAPABILITY_IAM"],
  StackName: "eksctl-beautiful-unicorn-1567692445-cluster",
  Tags: [{
      Key: "alpha.eksctl.io/cluster-name",
      Value: "beautiful-unicorn-1567692445"
    },{
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "beautiful-unicorn-1567692445"
    }],
  TemplateBody: "{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]\",\"Resources\":{\"ClusterSharedNodeSecurityGroup\":{\"Type\":\"AWS::EC2::SecurityGroup\",\"Properties\":{\"GroupDescription\":\"Communication between all nodes in the cluster\",\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/ClusterSharedNodeSecurityGroup\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"ControlPlane\":{\"Type\":\"AWS::EKS::Cluster\",\"Properties\":{\"Name\":\"beautiful-unicorn-1567692445\",\"ResourcesVpcConfig\":{\"SecurityGroupIds\":[{\"Ref\":\"ControlPlaneSecurityGroup\"}],\"SubnetIds\":[{\"Ref\":\"SubnetPublicUSEAST1B\"},{\"Ref\":\"SubnetPublicUSEAST1D\"},{\"Ref\":\"SubnetPublicUSEAST1A\"},{\"Ref\":\"SubnetPrivateUSEAST1B\"},{\"Ref\":\"SubnetPrivateUSEAST1D\"},{\"Ref\":\"SubnetPrivateUSEAST1A\"}]},\"RoleArn\":{\"Fn::GetAtt\":\"ServiceRole.Arn\"},\"Version\":\"1.13\"}},\"ControlPlaneSecurityGroup\":{\"Type\":\"AWS::EC2::SecurityGroup\",\"Properties\":{\"GroupDescription\":\"Communication between the control plane and worker nodegroups\",\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/ControlPlaneSecurityGroup\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"IngressInterNodeGroupSG\":{\"Type\":\"AWS::EC2::SecurityGroupIngress\",\"Properties\":{\"Description\":\"Allow nodes to communicate with each other (all ports)\",\"FromPort\":0,\"GroupId\":{\"Ref\":\"ClusterSharedNodeSecurityGroup\"},\"IpProtocol\":\"-1\",\"SourceSecurityGroupId\":{\"Ref\":\"ClusterSharedNodeSecurityGroup\"},\"ToPort\":65535}},\"InternetGateway\":{\"Type\":\"AWS::EC2::InternetGateway\",\"Properties\":{\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/InternetGateway\"}}]}},\"NATGateway\":{\"Type\":\"AWS::EC2::NatGateway\",\"Properties\":{\"AllocationId\":{\"Fn::GetAtt\":\"NATIP.AllocationId\"},\"SubnetId\":{\"Ref\":\"SubnetPublicUSEAST1A\"},\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/NATGateway\"}}]}},\"NATIP\":{\"Type\":\"AWS::EC2::EIP\",\"Properties\":{\"Domain\":\"vpc\"}},\"NATPrivateSubnetRouteUSEAST1A\":{\"Type\":\"AWS::EC2::Route\",\"Properties\":{\"DestinationCidrBlock\":\"0.0.0.0/0\",\"NatGatewayId\":{\"Ref\":\"NATGateway\"},\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1A\"}}},\"NATPrivateSubnetRouteUSEAST1B\":{\"Type\":\"AWS::EC2::Route\",\"Properties\":{\"DestinationCidrBlock\":\"0.0.0.0/0\",\"NatGatewayId\":{\"Ref\":\"NATGateway\"},\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1B\"}}},\"NATPrivateSubnetRouteUSEAST1D\":{\"Type\":\"AWS::EC2::Route\",\"Properties\":{\"DestinationCidrBlock\":\"0.0.0.0/0\",\"NatGatewayId\":{\"Ref\":\"NATGateway\"},\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1D\"}}},\"PolicyCloudWatchMetrics\":{\"Type\":\"AWS::IAM::Policy\",\"Properties\":{\"PolicyDocument\":{\"Statement\":[{\"Action\":[\"cloudwatch:PutMetricData\"],\"Effect\":\"Allow\",\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"},\"PolicyName\":{\"Fn::Sub\":\"${AWS::StackName}-PolicyCloudWatchMetrics\"},\"Roles\":[{\"Ref\":\"ServiceRole\"}]}},\"PolicyNLB\":{\"Type\":\"AWS::IAM::Policy\",\"Properties\":{\"PolicyDocument\":{\"Statement\":[{\"Action\":[\"elasticloadbalancing:*\",\"ec2:CreateSecurityGroup\",\"ec2:Describe*\"],\"Effect\":\"Allow\",\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"},\"PolicyName\":{\"Fn::Sub\":\"${AWS::StackName}-PolicyNLB\"},\"Roles\":[{\"Ref\":\"ServiceRole\"}]}},\"PrivateRouteTableUSEAST1A\":{\"Type\":\"AWS::EC2::RouteTable\",\"Properties\":{\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/PrivateRouteTableUSEAST1A\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"PrivateRouteTableUSEAST1B\":{\"Type\":\"AWS::EC2::RouteTable\",\"Properties\":{\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/PrivateRouteTableUSEAST1B\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"PrivateRouteTableUSEAST1D\":{\"Type\":\"AWS::EC2::RouteTable\",\"Properties\":{\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/PrivateRouteTableUSEAST1D\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"PublicRouteTable\":{\"Type\":\"AWS::EC2::RouteTable\",\"Properties\":{\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/PublicRouteTable\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"PublicSubnetRoute\":{\"Type\":\"AWS::EC2::Route\",\"Properties\":{\"DestinationCidrBlock\":\"0.0.0.0/0\",\"GatewayId\":{\"Ref\":\"InternetGateway\"},\"RouteTableId\":{\"Ref\":\"PublicRouteTable\"}}},\"RouteTableAssociationPrivateUSEAST1A\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1A\"},\"SubnetId\":{\"Ref\":\"SubnetPrivateUSEAST1A\"}}},\"RouteTableAssociationPrivateUSEAST1B\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1B\"},\"SubnetId\":{\"Ref\":\"SubnetPrivateUSEAST1B\"}}},\"RouteTableAssociationPrivateUSEAST1D\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PrivateRouteTableUSEAST1D\"},\"SubnetId\":{\"Ref\":\"SubnetPrivateUSEAST1D\"}}},\"RouteTableAssociationPublicUSEAST1A\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PublicRouteTable\"},\"SubnetId\":{\"Ref\":\"SubnetPublicUSEAST1A\"}}},\"RouteTableAssociationPublicUSEAST1B\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PublicRouteTable\"},\"SubnetId\":{\"Ref\":\"SubnetPublicUSEAST1B\"}}},\"RouteTableAssociationPublicUSEAST1D\":{\"Type\":\"AWS::EC2::SubnetRouteTableAssociation\",\"Properties\":{\"RouteTableId\":{\"Ref\":\"PublicRouteTable\"},\"SubnetId\":{\"Ref\":\"SubnetPublicUSEAST1D\"}}},\"ServiceRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"AssumeRolePolicyDocument\":{\"Statement\":[{\"Action\":[\"sts:AssumeRole\"],\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"eks.amazonaws.com\"]}}],\"Version\":\"2012-10-17\"},\"ManagedPolicyArns\":[\"arn:aws:iam::aws:policy/AmazonEKSServicePolicy\",\"arn:aws:iam::aws:policy/AmazonEKSClusterPolicy\"]}},\"SubnetPrivateUSEAST1A\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1a\",\"CidrBlock\":\"192.168.96.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/internal-elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPrivateUSEAST1A\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"SubnetPrivateUSEAST1B\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1b\",\"CidrBlock\":\"192.168.128.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/internal-elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPrivateUSEAST1B\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"SubnetPrivateUSEAST1D\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1d\",\"CidrBlock\":\"192.168.160.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/internal-elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPrivateUSEAST1D\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"SubnetPublicUSEAST1A\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1a\",\"CidrBlock\":\"192.168.0.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPublicUSEAST1A\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"SubnetPublicUSEAST1B\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1b\",\"CidrBlock\":\"192.168.32.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPublicUSEAST1B\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"SubnetPublicUSEAST1D\":{\"Type\":\"AWS::EC2::Subnet\",\"Properties\":{\"AvailabilityZone\":\"us-east-1d\",\"CidrBlock\":\"192.168.64.0/19\",\"Tags\":[{\"Key\":\"kubernetes.io/role/elb\",\"Value\":\"1\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SubnetPublicUSEAST1D\"}}],\"VpcId\":{\"Ref\":\"VPC\"}}},\"VPC\":{\"Type\":\"AWS::EC2::VPC\",\"Properties\":{\"CidrBlock\":\"192.168.0.0/16\",\"EnableDnsHostnames\":true,\"EnableDnsSupport\":true,\"Tags\":[{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/VPC\"}}]}},\"VPCGatewayAttachment\":{\"Type\":\"AWS::EC2::VPCGatewayAttachment\",\"Properties\":{\"InternetGatewayId\":{\"Ref\":\"InternetGateway\"},\"VpcId\":{\"Ref\":\"VPC\"}}}},\"Outputs\":{\"ARN\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::ARN\"}},\"Value\":{\"Fn::GetAtt\":\"ControlPlane.Arn\"}},\"CertificateAuthorityData\":{\"Value\":{\"Fn::GetAtt\":\"ControlPlane.CertificateAuthorityData\"}},\"ClusterStackName\":{\"Value\":{\"Ref\":\"AWS::StackName\"}},\"Endpoint\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::Endpoint\"}},\"Value\":{\"Fn::GetAtt\":\"ControlPlane.Endpoint\"}},\"FeatureNATMode\":{\"Value\":\"Single\"},\"SecurityGroup\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::SecurityGroup\"}},\"Value\":{\"Ref\":\"ControlPlaneSecurityGroup\"}},\"ServiceRoleARN\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::ServiceRoleARN\"}},\"Value\":{\"Fn::GetAtt\":\"ServiceRole.Arn\"}},\"SharedNodeSecurityGroup\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::SharedNodeSecurityGroup\"}},\"Value\":{\"Ref\":\"ClusterSharedNodeSecurityGroup\"}},\"SubnetsPrivate\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::SubnetsPrivate\"}},\"Value\":{\"Fn::Join\":[\",\",[{\"Ref\":\"SubnetPrivateUSEAST1B\"},{\"Ref\":\"SubnetPrivateUSEAST1D\"},{\"Ref\":\"SubnetPrivateUSEAST1A\"}]]}},\"SubnetsPublic\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::SubnetsPublic\"}},\"Value\":{\"Fn::Join\":[\",\",[{\"Ref\":\"SubnetPublicUSEAST1B\"},{\"Ref\":\"SubnetPublicUSEAST1D\"},{\"Ref\":\"SubnetPublicUSEAST1A\"}]]}},\"VPC\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::VPC\"}},\"Value\":{\"Ref\":\"VPC\"}}}}"
}
2019-09-05T14:07:25Z [ℹ]  deploying stack "eksctl-beautiful-unicorn-1567692445-cluster"
2019-09-05T14:07:25Z [▶]  start waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:07:25Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:07:43Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:08:02Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:08:21Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:08:40Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:08:58Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:09:18Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:20:24Z [▶]  done after 12m58.128332229s of waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-cluster" to reach "CREATE_COMPLETE" status
2019-09-05T14:20:24Z [▶]  processing stack outputs
2019-09-05T14:20:24Z [▶]  completed task: create cluster control plane "beautiful-unicorn-1567692445"
2019-09-05T14:20:24Z [▶]  started task: create nodegroup "ng-8d360547"
2019-09-05T14:20:24Z [▶]  waiting for 1 parallel tasks to complete
2019-09-05T14:20:24Z [▶]  started task: create nodegroup "ng-8d360547"
2019-09-05T14:20:24Z [ℹ]  building nodegroup stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547"
2019-09-05T14:20:24Z [▶]  user-data = H4sIAAAAAAAA/6xafXPiOJP/P59Cl516arcyNn4BAjzL1RlwApNAQiDkZW8vJWQBCrbkyDIQ5uY++5VsIMbyzjO7zzJVk7Lc3eqXX7fabf+EfBZ7GmJ0RuYnIURLOMdRA9DY9094TFHgNU40oIHSCvKST6alhKEUIU5CEZVCzDVCIwEpwqUpYyISHIY69C09WpysORH4ZUZ8HEkpiFGBqWiA/z0BAICfAF5GSPhaFGJEZgSB6D0SOPCAx1moEQpiSgSYMQ6W8RT7WHxOLpwAbhkF14TGG2CBn51r65eTROJvI8xXBOHfd/KvGYI+CLCAHhQQhJDDAAvMowa4cy97N4PPwHkYvXTcC+f+evySriW8Ll0RzmiAqbggPm6WsEClVN3SXp6O6Wq30aXPptAHkHogElAQdLRX+/p+NHbvXjqD0WcwuOm4L9dOy73eX4yd3mA8+pfb7nyQ2TU1jzKqFWyaiO7dfga9wWjsDNruS6/zw3v4UnKyU8qywWgkIBfN3GUpjnhpSuieEfx3QgCAplHmYY2EzU9fd5p8y9/04RT70Z4gdcm3z9APF1BP9dEJK+3RpRGv+elrxpisvAButJB5UljfeXy5vemMsrc5npNIYJ7s2xQ8xtnFNRELTUBCxUGZNCRZEdD32VoLOVkRH8+xl0r5uJ/mUcjZiniYN+E6yt5kVMrHXOMxFSTATY+hJeZZj2CxZnyphX48J7SJKMnyU6JNCdU8wpslFooSokS6PUciszilkSGVNBQL3ctQhczTCJ1xmFGJBHCOm5++ykxwr0YvbvvuxWm3b+4H42+6t+Q6RlxPbx8nyjcdJpkI15GOWCAxVAphHGENBl613LB1M7O1REhaZhTEpcv6Owz8Y6cVEUt4SsoTANiaYt4AnDHRkP+dABBCsWiAhGdXTHZ/D7xRWiJ0r2QampTri6Rcye2kAMwDEkWE0agBTo1quXyqVi5N/lruZW8A2u7duHfRaztjN1lN7vd7vfZ7p912pu25s+61nHmv5XScQWu+fFssyWV9bbScYXThdJxJ/66/dodPnclw2HHXIfcevviJEBRUfO9ysu23yo+dsVvpd5brwdg1+mNk9CfssTPuJWv918Pa+mLsjvst99Ix791EiLPpX0F7Qp4fv8TPj3c+2rbbzqi37gyfvlyx595ihQbO0G21hk5nPndvHan1kLXnc7fl9LuPiRCLRoE3mZbWVskwnjbmtoc4j7Y35pbj9u0lW4cRNkZ19/b+zV7F3dUwrD4OB70+a191Q6e/TIScT1/vxLYPnef6U7Tsbx65ddMfDG4fnCW7GHVsqx7Wbhf+cjOxl9XyYDHc1ohdfT5/vLpYO3O802S13C7C4MGvdyfIGlxuLp+8eYiiYNLvvs0GVcSWgRFePU2fF93BWjxXHmI2RIjcL/v3r+eekQhpk7Zfcp9LqyldP2/nlS1yH9ZexfDM9aZCVsPa2ftZ7+aedIIrbFVNYtDBG9tY98Z6cbGZWOVEyB0SHguXLXyFwzKqduPOeegQ//xNjPr+kPWNy0VtWi89ReFTuzafjJ/HJWraz9XLVf9Lfdp9S4RsX3vjx07l7o7zaOx2Z87WaDtr13Fg/7Xfdted+VNncmfcOsNuqeUMO878atl3ajK8nrt2W4mQ0np40Xf6LWdWy4f1ehfWluOgznPLelhUxrC6YFE4PoN35+8tE/dvEiG3j9H9e1y+frP54svlq/O8apfNaWmyjb36/fbRejCvzxZ006Ov6/rj9OFtaj30uxcTYXTvz4xVKT000fV48Ix783r3ctabtFfhWW/C6sLd8HLZttcb/MzmV8H6fYXr9iN67zxunPBqMTCIF61ugovrRMh9t4c6995yDHt3b3fnr11vc9Nlo9m2Nx9cDZ+uaP3RKBvG9iK6Gbfaz2PT3nSD1+DdtN+fljWXJkI4255d9RbdwL8zWhW8eriKbsl1qX0Z9ia9t+fX8UxY4/enh/c7y3dX/mO9Qrq13iq6j0pfjNl6nQhpXS6GscvPyvH59qk76LXnLRr11ufsS+kJzYZW7ezcqN/f9sz17GE7vSavr8vxW5kNRsun5keZcAedoiLx/dq1q3cI6oiLH61KMCQTzCVRA6zMNCJ+HCXtQKrP/rqxK7IAIMyFbL2gwBqMxYJxIt7/QIn0J+un1HwhRBg1SqULyzJdt9U2rVat3nZcu1xxyx2r5nYqnXq9auvR0tTjSMMwEpopD/bjY2MnmMIAN8AUw1iQWexrMSWIcaqZlep5tW6Vy5VjIWl3kBop3bARH0am1xkjd1b/NfHyF0eSfXeE/NdfFJOa+G8JQTHnmAptb+K/J21JqNcA7bT3lwshxzPMMUXyEeDrt5O96QfX/g0m7Jx5cC3eYPRxdYxi5BNMhS6BiamQKCWM6staJBvDlZm0imaWl8+jrCwNCLbE9GhFI0eX37MhQ4hYEEDpLbiONAIDLaMT4xlCTFe7p6cfzPFcA/SjyT63I33jQz7HoFJLVoIK9HSrvFs8t8/TSljRTWu3Ztnp2SUsPQqg7wMzdV5g6wH2SBwA09qJ8vQdSz3FXYXq9ZyURWTqtdwasXWrQKtyjkwqVc0pKqyDEunCzPwgssqpYnNL2ZKXj1UNzJ1xtb3YvUbllGFrenklka2oSGxMc4LLebaNqdt53yKFCuUUJOpmQYE/oKmQbbIeObgSKnSoXOBxqG4Ra6YlpqYuH2h9YJbPd7FWuBeZjcsVa7+mhFqFn7BzKF2oZhFblR5UYI5Rhs3OA9mGOdAgWwEI4ipOZ6oWocrJFSV4xVPlIxWUQVmNlLBzukqLjsXPCzwh84IgzsAeA7gAdBVa5NVj+FYU2HMViVym6zGVdHK6YFf28FJ8UKF5UyxlN5Ut1upF+FMUDcy8LUVlIL9fJW8JquQzEdM8V1hYYVTJ+SQ3C2iUwisjnqurahLltYbmHje1g3+K0lvNPUs/rnyhraIytD1adGrkFJULaZj2JInz7LzRxUdQwaLE8eZoC+mcg8f2ZOmhlgfkMR6lKKUy40MYP4J/bMBMKWDzgsqsxL6spigviAgqKIZIiW1i3pEXhHVsnLBzZ3UeaEFxxio+gzqFdF9F5GX2lJT5a9bycVOPEaGc70Qtmwky8sBQqGSICmtkptgFH9uZ5iE/lbiqGaSkcFFxL2pLcqBX9vLUNqioC8JUTf4gD8DQKjrOlYKQNzjIF/ZDf2F8AKJg93wCh0osPaVmk/zmstAc49U8ilisVdWKDpVMQwV9YkFXVFDUJFJVCCopUeQAmI9uPve8vLVQTTZPbaN4PrAoXzSCgiY8KC4aShbKVsIosKXIW0obUlR5eUFlCszcEwDPgQzlrwssQvlDI1ADo8KpAKtJW5cBlTwZch6uKHkod1ecR9TTnNhFB5nqEbX4BVYxRHOV1soWWq4S8CIMSZPVfjdfHST484gtagWKam05nzSYKvKDSr7PKnhqCIo6G64kNFR7NsURBWnKi54XUR5I84JTp9AVSvPgFTTrlnLKCDsbRJTPDqI2t8ca/tCTfwA3LyHzIj2A4Q889qevFtTXMM3DpOVA4F6NXvYvHQdO323+yynH4eXPoHN70xuMm3/reK/g1VKzalhlwzTLdtpF/ZjHjt+8/pjHMm8Xm/mXi7vJoEZhgL/rJOW1JGUennMWhykvnWs1z64ald2Rl3mL2Pwzk6CPF7w/NvL1PI6jqAEMPfmXLmYmaHuZuwnTYXQ2xWI3OTseru2nZ5Ay+h6wODNOwxROfew1wAz6Ed4tr/F0wdgyM2uFaIHH4+sGsAIjUpkFj/e8m4pRzw5pCaai7VwQH//hAHo3ot4e6RowDzfAQ6rJd/VyduzYSzSsZDVMCO4pPCaxdxQoiXWHk2T2nV7NdrdSDHUGo/2U1DR005DxMI0jChZAkkw1k8v0JXtCMMNQxBxfQoEPDr9jAgp8lcZvlAzd2x/D+owj0ynujjAd5sY8cVByO53Xj69Hrf3XGQfeP4XKPzOc/Ok/ko8CpjBanOyUEEBjAHOON0Rkl0IS4hkkfnaNsphGWKSss5giaQyYY/GyL5k//wK+7iO9ID4GHEMP7D8VeBHvIQaS7p/A+xjikxkAv/0GTj99PSL8dgqaTblqfjsFv/8O/vGPHZUUIG/+H/if3wyt/vvZJ3n7n0Dmy0EoABgtGNhRZ5Y5FjH/oJvtx84eoxj8+r2DAIBvJx9FpHfbPP30M4q5DzQtIj6mInn30iiVzGpdtyrygTT5W/IlfkRSJTVZJksJwjQSrsq/nCYSM59P/HWpmS8y8mLHT7fu3yBYhuWX0x10WMwR/qNCCX4CYkEigCAFbIU5Jx4G+09AUgEICvCfhfyHr1zAr7+6NxdHPv/4bEVx3PFXKAUOyBDI65Rkr1TmE5WG9unnLKol6I45T39JmaV2qTeSjxmQ8IEHccCoxrHPoJe7l1bbffHP3YwE5CJz74+rwF/55EupEOeVyunJ/wcAAP//cKJwu2cmAAA=
2019-09-05T14:20:24Z [ℹ]  --nodes-min=2 was set automatically for nodegroup ng-8d360547
2019-09-05T14:20:24Z [ℹ]  --nodes-max=2 was set automatically for nodegroup ng-8d360547
2019-09-05T14:20:24Z [▶]  CreateStackInput = {
  Capabilities: ["CAPABILITY_IAM"],
  StackName: "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547",
  Tags: [
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "beautiful-unicorn-1567692445"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "beautiful-unicorn-1567692445"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "ng-8d360547"
    },
    {
      Key: "eksctl.io/v1alpha2/nodegroup-name",
      Value: "ng-8d360547"
    }
  ],
  TemplateBody: "{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: false) [created and managed by eksctl]\",\"Resources\":{\"EgressInterCluster\":{\"Type\":\"AWS::EC2::SecurityGroupEgress\",\"Properties\":{\"Description\":\"Allow control plane to communicate with worker nodes in group ng-8d360547 (kubelet and workload TCP ports)\",\"DestinationSecurityGroupId\":{\"Ref\":\"SG\"},\"FromPort\":1025,\"GroupId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SecurityGroup\"},\"IpProtocol\":\"tcp\",\"ToPort\":65535}},\"EgressInterClusterAPI\":{\"Type\":\"AWS::EC2::SecurityGroupEgress\",\"Properties\":{\"Description\":\"Allow control plane to communicate with worker nodes in group ng-8d360547 (workloads using HTTPS port, commonly used with extension API servers)\",\"DestinationSecurityGroupId\":{\"Ref\":\"SG\"},\"FromPort\":443,\"GroupId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SecurityGroup\"},\"IpProtocol\":\"tcp\",\"ToPort\":443}},\"IngressInterCluster\":{\"Type\":\"AWS::EC2::SecurityGroupIngress\",\"Properties\":{\"Description\":\"Allow worker nodes in group ng-8d360547 to communicate with control plane (kubelet and workload TCP ports)\",\"FromPort\":1025,\"GroupId\":{\"Ref\":\"SG\"},\"IpProtocol\":\"tcp\",\"SourceSecurityGroupId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SecurityGroup\"},\"ToPort\":65535}},\"IngressInterClusterAPI\":{\"Type\":\"AWS::EC2::SecurityGroupIngress\",\"Properties\":{\"Description\":\"Allow worker nodes in group ng-8d360547 to communicate with control plane (workloads using HTTPS port, commonly used with extension API servers)\",\"FromPort\":443,\"GroupId\":{\"Ref\":\"SG\"},\"IpProtocol\":\"tcp\",\"SourceSecurityGroupId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SecurityGroup\"},\"ToPort\":443}},\"IngressInterClusterCP\":{\"Type\":\"AWS::EC2::SecurityGroupIngress\",\"Properties\":{\"Description\":\"Allow control plane to receive API requests from worker nodes in group ng-8d360547\",\"FromPort\":443,\"GroupId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SecurityGroup\"},\"IpProtocol\":\"tcp\",\"SourceSecurityGroupId\":{\"Ref\":\"SG\"},\"ToPort\":443}},\"NodeGroup\":{\"Type\":\"AWS::AutoScaling::AutoScalingGroup\",\"Properties\":{\"LaunchTemplate\":{\"LaunchTemplateName\":{\"Fn::Sub\":\"${AWS::StackName}\"},\"Version\":{\"Fn::GetAtt\":\"NodeGroupLaunchTemplate.LatestVersionNumber\"}},\"MaxSize\":\"2\",\"MinSize\":\"2\",\"Tags\":[{\"Key\":\"Name\",\"PropagateAtLaunch\":\"true\",\"Value\":\"beautiful-unicorn-1567692445-ng-8d360547-Node\"},{\"Key\":\"kubernetes.io/cluster/beautiful-unicorn-1567692445\",\"PropagateAtLaunch\":\"true\",\"Value\":\"owned\"}],\"VPCZoneIdentifier\":{\"Fn::Split\":[\",\",{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SubnetsPublic\"}]}},\"UpdatePolicy\":{\"AutoScalingRollingUpdate\":{\"MaxBatchSize\":\"1\",\"MinInstancesInService\":\"0\"}}},\"NodeGroupLaunchTemplate\":{\"Type\":\"AWS::EC2::LaunchTemplate\",\"Properties\":{\"LaunchTemplateData\":{\"EbsOptimized\":true,\"IamInstanceProfile\":{\"Arn\":{\"Fn::GetAtt\":\"NodeInstanceProfile.Arn\"}},\"ImageId\":\"ami-0d3998d69ebe9b214\",\"InstanceType\":\"t2.medium\",\"NetworkInterfaces\":[{\"AssociatePublicIpAddress\":true,\"DeviceIndex\":0,\"Groups\":[{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::SharedNodeSecurityGroup\"},{\"Ref\":\"SG\"}]}],\"UserData\":\"H4sIAAAAAAAA/6xafXPiOJP/P59Cl516arcyNn4BAjzL1RlwApNAQiDkZW8vJWQBCrbkyDIQ5uY++5VsIMbyzjO7zzJVk7Lc3eqXX7fabf+EfBZ7GmJ0RuYnIURLOMdRA9DY9094TFHgNU40oIHSCvKST6alhKEUIU5CEZVCzDVCIwEpwqUpYyISHIY69C09WpysORH4ZUZ8HEkpiFGBqWiA/z0BAICfAF5GSPhaFGJEZgSB6D0SOPCAx1moEQpiSgSYMQ6W8RT7WHxOLpwAbhkF14TGG2CBn51r65eTROJvI8xXBOHfd/KvGYI+CLCAHhQQhJDDAAvMowa4cy97N4PPwHkYvXTcC+f+evySriW8Ll0RzmiAqbggPm6WsEClVN3SXp6O6Wq30aXPptAHkHogElAQdLRX+/p+NHbvXjqD0WcwuOm4L9dOy73eX4yd3mA8+pfb7nyQ2TU1jzKqFWyaiO7dfga9wWjsDNruS6/zw3v4UnKyU8qywWgkIBfN3GUpjnhpSuieEfx3QgCAplHmYY2EzU9fd5p8y9/04RT70Z4gdcm3z9APF1BP9dEJK+3RpRGv+elrxpisvAButJB5UljfeXy5vemMsrc5npNIYJ7s2xQ8xtnFNRELTUBCxUGZNCRZEdD32VoLOVkRH8+xl0r5uJ/mUcjZiniYN+E6yt5kVMrHXOMxFSTATY+hJeZZj2CxZnyphX48J7SJKMnyU6JNCdU8wpslFooSokS6PUciszilkSGVNBQL3ctQhczTCJ1xmFGJBHCOm5++ykxwr0YvbvvuxWm3b+4H42+6t+Q6RlxPbx8nyjcdJpkI15GOWCAxVAphHGENBl613LB1M7O1REhaZhTEpcv6Owz8Y6cVEUt4SsoTANiaYt4AnDHRkP+dABBCsWiAhGdXTHZ/D7xRWiJ0r2QampTri6Rcye2kAMwDEkWE0agBTo1quXyqVi5N/lruZW8A2u7duHfRaztjN1lN7vd7vfZ7p912pu25s+61nHmv5XScQWu+fFssyWV9bbScYXThdJxJ/66/dodPnclw2HHXIfcevviJEBRUfO9ysu23yo+dsVvpd5brwdg1+mNk9CfssTPuJWv918Pa+mLsjvst99Ix791EiLPpX0F7Qp4fv8TPj3c+2rbbzqi37gyfvlyx595ihQbO0G21hk5nPndvHan1kLXnc7fl9LuPiRCLRoE3mZbWVskwnjbmtoc4j7Y35pbj9u0lW4cRNkZ19/b+zV7F3dUwrD4OB70+a191Q6e/TIScT1/vxLYPnef6U7Tsbx65ddMfDG4fnCW7GHVsqx7Wbhf+cjOxl9XyYDHc1ohdfT5/vLpYO3O802S13C7C4MGvdyfIGlxuLp+8eYiiYNLvvs0GVcSWgRFePU2fF93BWjxXHmI2RIjcL/v3r+eekQhpk7Zfcp9LqyldP2/nlS1yH9ZexfDM9aZCVsPa2ftZ7+aedIIrbFVNYtDBG9tY98Z6cbGZWOVEyB0SHguXLXyFwzKqduPOeegQ//xNjPr+kPWNy0VtWi89ReFTuzafjJ/HJWraz9XLVf9Lfdp9S4RsX3vjx07l7o7zaOx2Z87WaDtr13Fg/7Xfdted+VNncmfcOsNuqeUMO878atl3ajK8nrt2W4mQ0np40Xf6LWdWy4f1ehfWluOgznPLelhUxrC6YFE4PoN35+8tE/dvEiG3j9H9e1y+frP54svlq/O8apfNaWmyjb36/fbRejCvzxZ006Ov6/rj9OFtaj30uxcTYXTvz4xVKT000fV48Ix783r3ctabtFfhWW/C6sLd8HLZttcb/MzmV8H6fYXr9iN67zxunPBqMTCIF61ugovrRMh9t4c6995yDHt3b3fnr11vc9Nlo9m2Nx9cDZ+uaP3RKBvG9iK6Gbfaz2PT3nSD1+DdtN+fljWXJkI4255d9RbdwL8zWhW8eriKbsl1qX0Z9ia9t+fX8UxY4/enh/c7y3dX/mO9Qrq13iq6j0pfjNl6nQhpXS6GscvPyvH59qk76LXnLRr11ufsS+kJzYZW7ezcqN/f9sz17GE7vSavr8vxW5kNRsun5keZcAedoiLx/dq1q3cI6oiLH61KMCQTzCVRA6zMNCJ+HCXtQKrP/rqxK7IAIMyFbL2gwBqMxYJxIt7/QIn0J+un1HwhRBg1SqULyzJdt9U2rVat3nZcu1xxyx2r5nYqnXq9auvR0tTjSMMwEpopD/bjY2MnmMIAN8AUw1iQWexrMSWIcaqZlep5tW6Vy5VjIWl3kBop3bARH0am1xkjd1b/NfHyF0eSfXeE/NdfFJOa+G8JQTHnmAptb+K/J21JqNcA7bT3lwshxzPMMUXyEeDrt5O96QfX/g0m7Jx5cC3eYPRxdYxi5BNMhS6BiamQKCWM6staJBvDlZm0imaWl8+jrCwNCLbE9GhFI0eX37MhQ4hYEEDpLbiONAIDLaMT4xlCTFe7p6cfzPFcA/SjyT63I33jQz7HoFJLVoIK9HSrvFs8t8/TSljRTWu3Ztnp2SUsPQqg7wMzdV5g6wH2SBwA09qJ8vQdSz3FXYXq9ZyURWTqtdwasXWrQKtyjkwqVc0pKqyDEunCzPwgssqpYnNL2ZKXj1UNzJ1xtb3YvUbllGFrenklka2oSGxMc4LLebaNqdt53yKFCuUUJOpmQYE/oKmQbbIeObgSKnSoXOBxqG4Ra6YlpqYuH2h9YJbPd7FWuBeZjcsVa7+mhFqFn7BzKF2oZhFblR5UYI5Rhs3OA9mGOdAgWwEI4ipOZ6oWocrJFSV4xVPlIxWUQVmNlLBzukqLjsXPCzwh84IgzsAeA7gAdBVa5NVj+FYU2HMViVym6zGVdHK6YFf28FJ8UKF5UyxlN5Ut1upF+FMUDcy8LUVlIL9fJW8JquQzEdM8V1hYYVTJ+SQ3C2iUwisjnqurahLltYbmHje1g3+K0lvNPUs/rnyhraIytD1adGrkFJULaZj2JInz7LzRxUdQwaLE8eZoC+mcg8f2ZOmhlgfkMR6lKKUy40MYP4J/bMBMKWDzgsqsxL6spigviAgqKIZIiW1i3pEXhHVsnLBzZ3UeaEFxxio+gzqFdF9F5GX2lJT5a9bycVOPEaGc70Qtmwky8sBQqGSICmtkptgFH9uZ5iE/lbiqGaSkcFFxL2pLcqBX9vLUNqioC8JUTf4gD8DQKjrOlYKQNzjIF/ZDf2F8AKJg93wCh0osPaVmk/zmstAc49U8ilisVdWKDpVMQwV9YkFXVFDUJFJVCCopUeQAmI9uPve8vLVQTTZPbaN4PrAoXzSCgiY8KC4aShbKVsIosKXIW0obUlR5eUFlCszcEwDPgQzlrwssQvlDI1ADo8KpAKtJW5cBlTwZch6uKHkod1ecR9TTnNhFB5nqEbX4BVYxRHOV1soWWq4S8CIMSZPVfjdfHST484gtagWKam05nzSYKvKDSr7PKnhqCIo6G64kNFR7NsURBWnKi54XUR5I84JTp9AVSvPgFTTrlnLKCDsbRJTPDqI2t8ca/tCTfwA3LyHzIj2A4Q889qevFtTXMM3DpOVA4F6NXvYvHQdO323+yynH4eXPoHN70xuMm3/reK/g1VKzalhlwzTLdtpF/ZjHjt+8/pjHMm8Xm/mXi7vJoEZhgL/rJOW1JGUennMWhykvnWs1z64ald2Rl3mL2Pwzk6CPF7w/NvL1PI6jqAEMPfmXLmYmaHuZuwnTYXQ2xWI3OTseru2nZ5Ay+h6wODNOwxROfew1wAz6Ed4tr/F0wdgyM2uFaIHH4+sGsAIjUpkFj/e8m4pRzw5pCaai7VwQH//hAHo3ot4e6RowDzfAQ6rJd/VyduzYSzSsZDVMCO4pPCaxdxQoiXWHk2T2nV7NdrdSDHUGo/2U1DR005DxMI0jChZAkkw1k8v0JXtCMMNQxBxfQoEPDr9jAgp8lcZvlAzd2x/D+owj0ynujjAd5sY8cVByO53Xj69Hrf3XGQfeP4XKPzOc/Ok/ko8CpjBanOyUEEBjAHOON0Rkl0IS4hkkfnaNsphGWKSss5giaQyYY/GyL5k//wK+7iO9ID4GHEMP7D8VeBHvIQaS7p/A+xjikxkAv/0GTj99PSL8dgqaTblqfjsFv/8O/vGPHZUUIG/+H/if3wyt/vvZJ3n7n0Dmy0EoABgtGNhRZ5Y5FjH/oJvtx84eoxj8+r2DAIBvJx9FpHfbPP30M4q5DzQtIj6mInn30iiVzGpdtyrygTT5W/IlfkRSJTVZJksJwjQSrsq/nCYSM59P/HWpmS8y8mLHT7fu3yBYhuWX0x10WMwR/qNCCX4CYkEigCAFbIU5Jx4G+09AUgEICvCfhfyHr1zAr7+6NxdHPv/4bEVx3PFXKAUOyBDI65Rkr1TmE5WG9unnLKol6I45T39JmaV2qTeSjxmQ8IEHccCoxrHPoJe7l1bbffHP3YwE5CJz74+rwF/55EupEOeVyunJ/wcAAP//cKJwu2cmAAA=\"},\"LaunchTemplateName\":{\"Fn::Sub\":\"${AWS::StackName}\"}}},\"NodeInstanceProfile\":{\"Type\":\"AWS::IAM::InstanceProfile\",\"Properties\":{\"Path\":\"/\",\"Roles\":[{\"Ref\":\"NodeInstanceRole\"}]}},\"NodeInstanceRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"AssumeRolePolicyDocument\":{\"Statement\":[{\"Action\":[\"sts:AssumeRole\"],\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"ec2.amazonaws.com\"]}}],\"Version\":\"2012-10-17\"},\"ManagedPolicyArns\":[\"arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy\",\"arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy\",\"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly\"],\"Path\":\"/\"}},\"SG\":{\"Type\":\"AWS::EC2::SecurityGroup\",\"Properties\":{\"GroupDescription\":\"Communication between the control plane and worker nodes in group ng-8d360547\",\"Tags\":[{\"Key\":\"kubernetes.io/cluster/beautiful-unicorn-1567692445\",\"Value\":\"owned\"},{\"Key\":\"Name\",\"Value\":{\"Fn::Sub\":\"${AWS::StackName}/SG\"}}],\"VpcId\":{\"Fn::ImportValue\":\"eksctl-beautiful-unicorn-1567692445-cluster::VPC\"}}}},\"Outputs\":{\"FeatureLocalSecurityGroup\":{\"Value\":true},\"FeaturePrivateNetworking\":{\"Value\":false},\"FeatureSharedSecurityGroup\":{\"Value\":true},\"InstanceProfileARN\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::InstanceProfileARN\"}},\"Value\":{\"Fn::GetAtt\":\"NodeInstanceProfile.Arn\"}},\"InstanceRoleARN\":{\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}::InstanceRoleARN\"}},\"Value\":{\"Fn::GetAtt\":\"NodeInstanceRole.Arn\"}}}}"
}
2019-09-05T14:20:24Z [ℹ]  deploying stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547"
2019-09-05T14:20:24Z [▶]  start waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547" to reach "CREATE_COMPLETE" status
2019-09-05T14:20:24Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547" to reach "CREATE_COMPLETE" status
2019-09-05T14:20:40Z [▶]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547" to reach "CREATE_COMPLETE" status
2019-09-05T14:23:14Z [✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547"
2019-09-05T14:23:14Z [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2019-09-05T14:23:14Z [▶]  AWS::CloudFormation::Stack/eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547: ROLLBACK_IN_PROGRESS – "The following resource(s) failed to create: [NodeGroup]. . Rollback requested by user."
2019-09-05T14:23:14Z [✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. EBS-optimized instances are not supported for your requested configuration. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: a6251170-cfe8-11e9-ae88-234007dafb6a)"
2019-09-05T14:23:14Z [▶]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::IAM::InstanceProfile/NodeInstanceProfile: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::IAM::InstanceProfile/NodeInstanceProfile: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::IAM::InstanceProfile/NodeInstanceProfile: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::IAM::Role/NodeInstanceRole: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroup/SG: CREATE_COMPLETE
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroup/SG: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS – "Resource creation Initiated"
2019-09-05T14:23:14Z [▶]  AWS::EC2::SecurityGroup/SG: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS
2019-09-05T14:23:14Z [▶]  AWS::CloudFormation::Stack/eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547: CREATE_IN_PROGRESS – "User Initiated"
2019-09-05T14:23:14Z [▶]  failed task: create nodegroup "ng-8d360547" (will continue until other parallel tasks are completed)
2019-09-05T14:23:14Z [▶]  failed task: create nodegroup "ng-8d360547" (will not run other sequential tasks)
2019-09-05T14:23:14Z [ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2019-09-05T14:23:14Z [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=beautiful-unicorn-1567692445'
2019-09-05T14:23:14Z [✖]  waiting for CloudFormation stack "eksctl-beautiful-unicorn-1567692445-nodegroup-ng-8d360547" to reach "CREATE_COMPLETE" status: ResourceNotReady: failed waiting for successful resource state
2019-09-05T14:23:14Z [✖]  failed to create cluster "beautiful-unicorn-1567692445"
```

### PR DESCRIPTION
**Pull request by cPu1**
Not all instance types support EBS-optimized volumes, this fix makes the configuration optional

- Fixes #1293 
- Fixes #1257 

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)
- [x] Manually tested

### CODE REVIEW

File: pkg/cfn/builder/api_test.go [hunk 1]
```diff
@@ -1551,7 +1551,7 @@ var _ = Describe("CloudFormation template builder API", func() {
 		})
 	})
 
-	Context("NodeGroup{EbsOptimized=true}", func() {
+	Context("NodeGroup{EbsOptimized=nil}", func() {
```
Comment (errordeveloper) [inline pkg/cfn/builder/api_test.go]: We should add test for true and false cases, but I'm happy if you add those later on.

File: pkg/cfn/builder/api_test.go [hunk 2]
```diff
@@ -1566,7 +1566,7 @@ var _ = Describe("CloudFormation template builder API", func() {
 
 		It("should have correct instance type and sizes", func() {
 			Expect(getLaunchTemplateData(ngTemplate).InstanceType).To(Equal("m5.2xlarge"))
-			Expect(getLaunchTemplateData(ngTemplate).EbsOptimized).To(Equal(true))
+			Expect(getLaunchTemplateData(ngTemplate).EbsOptimized).To(Equal(false))
```
Comment (errordeveloper) [inline pkg/cfn/builder/api_test.go]: I'd make `EbsOptimized` a `*bool`, and test for this to be nil...

File: docs/release_notes/0.5.2.md [hunk 3]
```diff
@@ -4,4 +4,5 @@
 
 - fix cluster deletion due to OIDC errors (#1289)
 - fix updating clusters to 1.14 (#1291)
-- improve log and error messaging on exclude rules (#1296)
\ No newline at end of file
+- improve log and error messaging on exclude rules (#1296)
+- fix launch template errors (#1293)
```
Comment (errordeveloper) [inline docs/release_notes/0.5.2.md]: Would you mind to make this more specific? 
```
- make EBS-optimized setting optional, as enabling it by default breaks for some instance types (#1293)
```

File: pkg/cfn/builder/api_test.go (hunk 1 above)
Comment (cPu1) [reply pkg/cfn/builder/api_test.go]: It makes sense to add tests for this as it was a bug, but overall we can't keep adding tests for all possible values.

File: pkg/cfn/builder/api_test.go [hunk 4]
```diff
@@ -387,7 +387,7 @@ var _ = Describe("CloudFormation template builder API", func() {
 			Status: &api.ClusterStatus{
 				Endpoint:                 endpoint,
 				CertificateAuthorityData: caCertData,
-				ARN:                      arn,
+				ARN: arn,
```
[the remark this answers is not in the document]
Comment (cPu1) [reply pkg/cfn/builder/api_test.go]: I believe the newer version of goimports prefers formatting it this way.
