### PR TITLE
Fix bug in update-cluster-endpoint #1820

### LINKED ISSUE #1820: update-cluster-endpoint not using correct values from flags
When we merged #1693 we introduced a bug.

The fields in the `ClusterConfig` object are always set by the loader with default values which means https://github.com/weaveworks/eksctl/pull/1693/files#diff-3d2e69c16896f6dcabb52f22a3fdac50R88 was not a good way to determine whether we are dealing with a config file or not.

As a result, the command using argument flags always tries to set the default values.

This is breaking the integration tests.

### PR DESCRIPTION
**Pull request by martina-if**
fixes #1820

- [x] Manually tested
- [x] Make sure Integration tests pass
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

## Integration tests passing

```
------------------------------

Ran 10 of 10 Specs in 3830.525 seconds
SUCCESS! -- 10 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (3830.53s)
PASS
```

### CODE REVIEW

File: pkg/ctl/utils/update_cluster_endpoint_access.go [hunk 1]
```diff
@@ -85,17 +72,16 @@ func doUpdateClusterEndpoints(cmd *cmdutils.Cmd, newPrivate bool, newPublic bool
...
+		if !flagSet("private-access", cmd) {
 			newPrivate = curPrivate
 		}
-		if !publicSet {
+		if !flagSet("public-access", cmd) {
 			newPublic = curPublic
 		}
+	} else {
+		newPublic = *cfg.VPC.ClusterEndpoints.PublicAccess
+		newPrivate = *cfg.VPC.ClusterEndpoints.PrivateAccess
```
Comment (cPu1) [inline pkg/ctl/utils/update_cluster_endpoint_access.go]: If a ClusterConfig file is supplied with a blank `vpc.clusterEndpoints` field, the defaults set in `ClusterEndpointAccessDefaults()` can override the current settings.

**Comment by cPu1** [comment]
Apologies, I left a couple comments but just saw that the PR has been updated to WIP.

File: pkg/ctl/utils/update_cluster_endpoint_access.go (hunk 1 above)
Comment (martina-if) [reply pkg/ctl/utils/update_cluster_endpoint_access.go]: You are right. Good catch! I'll redo this part as I did initially by changing the loader and moving the validation to the loader instead of having it in `NewCtl()`

**Comment by martina-if** [comment]
@cPu1 I implemented it in a different way. I ran a few manual tests and I think it should be fine now, but please take a look and tell me if you find any potential issues. 

The current way of defining defaults, loading and validation is not good for these cases... we should refactor all this.

In the meantime I'm checking if the endpoint access integration tests are working.

File: pkg/apis/eksctl.io/v1alpha5/validation.go [hunk 2]
```diff
@@ -111,6 +107,9 @@ func ValidateClusterConfig(cfg *ClusterConfig) error {
 
 // ValidateClusterEndpointConfig checks the endpoint configuration for potential issues
 func (c *ClusterConfig) ValidateClusterEndpointConfig() error {
+	if !c.HasClusterEndpointAccess() {
```
Comment (sayboras) [inline pkg/apis/eksctl.io/v1alpha5/validation.go]: @martina-if this check is fine, however the implementation of `HasClusterEndpointAccess` is a little bit weird for me

```
func (c *ClusterConfig) HasClusterEndpointAccess() bool {
	if c.VPC != nil && c.VPC.ClusterEndpoints != nil {
		pubAccess := c.VPC.ClusterEndpoints.PublicAccess
		privAccess := c.VPC.ClusterEndpoints.PrivateAccess
		hasPublicAccess := pubAccess != nil && *pubAccess
		hasPrivateAccess := privAccess != nil && *privAccess
		return hasPublicAccess || hasPrivateAccess
	}
	return true // so if nothing is specficified, it returns true, which is has cluster endpoint configured.
}
```
