### PR TITLE
Fix include update irsa

### LINKED ISSUE #5843: [Bug] 'update iamserviceaccount' incorrect include/exclude behavior, doesn't affect create/delete (0.120.0)
### What were you trying to accomplish?

Updating an IAM Service Account in order to trigger the re-annotation of the k8s `ServiceAccount`, using `eksctl` and a config file.

### What happened?

1. I was unable to select a single `iam.ServiceAccount` with `update` and `--include`, I could only get the command to select all accounts or none. The same `--include` with `create` or `delete` worked just fine.
2. When I used the non-config-file approach I found `update` didn't update the k8s `ServiceAccount` like `create`/`delete` do.
3. I had to fall back to deleting and then recreating the `iam.ServiceAccount` in order to reannotate the `ServiceAccount`

While `ekstcl create iamservice` and `ekstcl delete iamservice` work with `--include` and `--exclude` exactly as expected. The `ekstcl update iamservice` include/exclude behavior was inexplicable.

`ekstcl update iamservice` with `--config-file=myconfig.yaml` and

*  `--include=nonmatching/serviceaccount` matches nothing as expected ✅
*  `--include=matching/serviceaccount` should match one account but actually matches *all* IAM Service Accounts in the config ❌
* `'--exclude=*'` matches *all* IAM Service Accounts in the config ❌
* `--exclude=nonmatching` matches *all* IAM Service Accounts in the config ✅

When I worked around the config file problem, I found that 'update' doesn't actually update the ServiceAccount in k8s (as I expected, since create/delete do account on the `ServiceAccount`), just the Cloudformation stack. I had to delete/create in the end.

### How to reproduce it?

1. `eksctl` config file `foo.yaml` with more than one iam.serviceAccount.
2. `ekstcl update iamservice --config-file=foo.yaml --include=amazon-cloudwatch/cloudwatch-agent`
3. Note that the plan is to update all accounts, not just the included one 

```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-node
        namespace: kube-system
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
    - metadata:
        name: cloudwatch-agent
        namespace: amazon-cloudwatch
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
    - metadata:
        name: fluent-bit
        namespace: amazon-cloudwatch
      attachPolicyARNs:
      - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
...   
```

**Anything else we need to know?**

I worked around this by not using the config file. I found that 'update' doesn't actually update the ServiceAccount in k8s (as I expected), just the Cloudformation stack. I had to delete/create as a workaround.

Downloaded Linux binary, default profile.

**Versions**

```
$ eksctl info
eksctl version: 0.102.0
kubectl version: v1.22.6-eks-7d68063
OS: linux
```

### PR DESCRIPTION
**Pull request by yuxiang-zhang**
### Description

Use filter to fix include/exclude when running `update iamserviceaccount --include`. 

Fixes #5843 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [x] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by yuxiang-zhang** [comment]
Manual tests: 
```
 % ./eksctl update iamserviceaccount --config-file=examples/13-iamserviceaccounts.yaml '--exclude=*'
2022-12-09 19:28:21 [ℹ]  combined exclude rules: *
2022-12-09 19:28:21 [ℹ]  11 iamserviceaccounts (backend-apps/cache-access, backend-apps/s3-reader, cert-manager/cert-manager, ci-cd/build-service, default/some-app, kube-system/autoscaler-service, kube-system/aws-load-balancer-controller, kube-system/cluster-autoscaler, kube-system/ebs-csi-controller-sa, kube-system/efs-csi-controller-sa, kube-system/external-dns) were excluded (based on the include/exclude rules)
2022-12-09 19:28:21 [ℹ]  no tasks
 % eksctl update iamserviceaccount --config-file=examples/13-iamserviceaccounts.yaml '--exclude=*'
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount backend-apps/s3-reader as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/aws-load-balancer-controller as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/ebs-csi-controller-sa as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/efs-csi-controller-sa as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/external-dns as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount cert-manager/cert-manager as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/cluster-autoscaler as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount backend-apps/cache-access as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount kube-system/autoscaler-service as it does not exist
2022-12-09 19:28:24 [ℹ]  cannot update IAMServiceAccount default/some-app as it does not exist
2022-12-09 19:28:24 [ℹ]  the following IAMServiceAccounts will not be updated as they do not exist: backend-apps/s3-reader, kube-system/aws-load-balancer-controller, kube-system/ebs-csi-controller-sa, kube-system/efs-csi-controller-sa, kube-system/external-dns, cert-manager/cert-manager, kube-system/cluster-autoscaler, backend-apps/cache-access, kube-system/autoscaler-service, default/some-app
2022-12-09 19:28:24 [ℹ]  1 task: { 1 task: { update IAMServiceAccount ci-cd/build-service } }
2022-12-09 19:28:24 [!]  no changes were applied, run again with '--approve' to apply the changes
```
```
 % ./eksctl update iamserviceaccount --config-file=examples/13-iamserviceaccounts.yaml --include=ci-cd/build-service
2022-12-09 19:28:38 [ℹ]  combined include rules: ci-cd/build-service
2022-12-09 19:28:38 [ℹ]  1 iamserviceaccount (ci-cd/build-service) was included (based on the include/exclude rules)
2022-12-09 19:28:38 [ℹ]  10 iamserviceaccounts (backend-apps/cache-access, backend-apps/s3-reader, cert-manager/cert-manager, default/some-app, kube-system/autoscaler-service, kube-system/aws-load-balancer-controller, kube-system/cluster-autoscaler, kube-system/ebs-csi-controller-sa, kube-system/efs-csi-controller-sa, kube-system/external-dns) were excluded (based on the include/exclude rules)
2022-12-09 19:28:38 [ℹ]  1 task: { 1 task: { update IAMServiceAccount ci-cd/build-service } }
2022-12-09 19:28:38 [!]  no changes were applied, run again with '--approve' to apply the changes
 % eksctl update iamserviceaccount --config-file=examples/13-iamserviceaccounts.yaml --include=ci-cd/build-service
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount backend-apps/s3-reader as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/aws-load-balancer-controller as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/ebs-csi-controller-sa as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/efs-csi-controller-sa as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/external-dns as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount cert-manager/cert-manager as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/cluster-autoscaler as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount backend-apps/cache-access as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount kube-system/autoscaler-service as it does not exist
2022-12-09 19:28:42 [ℹ]  cannot update IAMServiceAccount default/some-app as it does not exist
2022-12-09 19:28:42 [ℹ]  the following IAMServiceAccounts will not be updated as they do not exist: backend-apps/s3-reader, kube-system/aws-load-balancer-controller, kube-system/ebs-csi-controller-sa, kube-system/efs-csi-controller-sa, kube-system/external-dns, cert-manager/cert-manager, kube-system/cluster-autoscaler, backend-apps/cache-access, kube-system/autoscaler-service, default/some-app
2022-12-09 19:28:42 [ℹ]  1 task: { 1 task: { update IAMServiceAccount ci-cd/build-service } }
2022-12-09 19:28:42 [!]  no changes were applied, run again with '--approve' to apply the changes
```

File: pkg/actions/irsa/delete.go [hunk 1]
```diff
@@ -15,14 +13,7 @@ func (m *Manager) Delete(ctx context.Context, serviceAccounts []string, plan, wa
...
 
-	logger.Info(taskTree.Describe())
-	if errs := taskTree.DoAllSync(); len(errs) > 0 {
-		logger.Info("%d error(s) occurred and IAM Role stacks haven't been deleted properly, you may wish to check CloudFormation console", len(errs))
-		for _, err := range errs {
-			logger.Critical("%s\n", err.Error())
-		}
-		return fmt.Errorf("failed to delete iamserviceaccount(s)")
-	}
+	doTasks(taskTree, "delete")
```
Comment (A-Hilaly) [inline pkg/actions/irsa/delete.go:16]: We need to handle the error here.

File: pkg/actions/irsa/irsa.go [hunk 2]
```diff
@@ -26,14 +26,14 @@ func New(clusterName string, stackManager manager.StackManager, oidcManager *iam
 	}
 }
 
-func doTasks(taskTree *tasks.TaskTree) error {
+func doTasks(taskTree *tasks.TaskTree, verb string) error {
```
Comment (A-Hilaly) [inline pkg/actions/irsa/irsa.go:29]: nit: maybe operation or action instead of verb?

File: pkg/actions/irsa/create.go [hunk 3]
```diff
@@ -9,7 +9,7 @@ func (a *Manager) CreateIAMServiceAccount(iamServiceAccounts []*api.ClusterIAMSe
 	taskTree := a.stackManager.NewTasksToCreateIAMServiceAccounts(iamServiceAccounts, a.oidcManager, kubernetes.NewCachedClientSet(a.clientSet))
 	taskTree.PlanMode = plan
 
-	err := doTasks(taskTree)
+	err := doTasks(taskTree, "create")
```
Comment (A-Hilaly) [inline pkg/actions/irsa/create.go:12]: Can we create enums for "create", "delete", "update" and reuse them in `doTasks` call?

File: pkg/actions/irsa/irsa.go (hunk 2 above)
Comment (yuxiang-zhang) [reply pkg/actions/irsa/irsa.go]: Yeah I was thinking about the same, but I saw some other methods were doing the same and using `verb`. Anyways, that's changed to `action Action` now :)

**Comment by yuxiang-zhang** [comment]
I was trying to add unit test for `--include` and `--exclude` flags in `pkg/ctl/update/iamserviceaccount_test.go`. I wanted to spy on the `UpdateIAMServiceAccounts` from `irsa.Manager` to make sure the `filteredServiceAccounts` are passed in as intended, but I realize that `irsa.Manager` is a struct and does not have fakes generated for it. I could not write the unit test as a result.

File: pkg/actions/irsa/irsa.go [hunk 4]
```diff
@@ -17,6 +17,14 @@ type Manager struct {
 	clientSet    kubeclient.Interface
 }
 
+type Action string
+
+const (
+	Create Action = "create"
+	Delete Action = "delete"
+	Update Action = "update"
+)
```
Comment (cPu1) [inline pkg/actions/irsa/irsa.go:26]: We don't need to export these. Additionally, this can be made more readable by prefixing the action values with the enum name. 

```suggestion
type action string

const (
	actionCreate action = "create"
	actionDelete action = "delete"
	actionUpdate action = "update"
)
```

**Review by cPu1 — APPROVED** [review]
LGTM :tada:
