### PR TITLE
Fix upgrading nodegroups with old template format

### LINKED ISSUE #2565: Failed to update managed nodegroups from 1.16 to 1.17
**What happened?**
I want to upgrade my managed nodegroup from 1.16  to 1.17. The nodegroups AMI version is: `1.16.13-20200814`.

```
eksctl get nodegroups --cluster=bs-k-dev-v1 -o yaml node-group-az-b-v1
- Cluster: bs-k-dev-v1
  CreationTime: "2020-03-05T07:22:31.924Z"
  DesiredCapacity: 1
  ImageID: ""
  InstanceType: t3.xlarge
  MaxSize: 4
  MinSize: 1
  Name: node-group-az-b-v1
  NodeInstanceRoleARN: ""
  StackName: eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1
```

Running upgrade node group runs into this error:
```
eksctl upgrade nodegroup -f clusters/bs-k-dev-v1.yml --cluster=bs-k-dev-v1 --name=node-group-az-b-v1 --kubernetes-version=1.17
[ℹ]  Update nodegroup stack
[✖]  unexpected status "UPDATE_ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Version and ReleaseVersion updates cannot be combined with other updates"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Version and ReleaseVersion updates cannot be combined with other updates"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Version and ReleaseVersion updates cannot be combined with other updates"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Version and ReleaseVersion updates cannot be combined with other updates"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1: CREATE_IN_PROGRESS – "User Initiated"
Error: error updating nodegroup stack: waiting for CloudFormation stack "eksctl-bs-k-dev-v1-nodegroup-node-group-az-b-v1": ResourceNotReady: failed waiting for successful resource state
```
 
Without setting the kubernetes version, eksctl upgrade doesn't do anything.
```
eksctl upgrade nodegroup -f clusters/bs-k-dev-v1.yml --cluster=bs-k-dev-v1 --name=node-group-az-b-v1 
[ℹ]  nodegroup "node-group-az-b-v1" is already up-to-date
```

**What you expected to happen?**
The expected result is an updated nodegroup to kubernetes version 1.17

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:20:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}


$ eksctl version
0.26.0

```

**Logs**

### PR DESCRIPTION
**Pull request by cPu1**
goformation unmarshals an attribute reference as an array. For old templates, this was causing the reference to `"Fn::GetAtt": "NodeInstanceRole.Arn"` to be unmarshalled as `"Fn::GetAtt": ["NodeInstanceRole", "Arn"]`, which, in turn, was triggering an update on this resource. However, when upgrading a nodegroup, CloudFormation does not permit combining release version updates with other updates, and this resulted in an error.

Fixes #2565 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

File: pkg/managed/service.go [hunk 1]
```diff
@@ -217,17 +240,35 @@ func (m *Service) UpgradeNodeGroup(options UpgradeOptions) error {
...
+	if err != nil {
+		return false, err
+	}
+	if found {
+		newFormatVersion := semver.Version{
+			Major: 0,
+			Minor: 25,
+			Patch: 0,
+		}
+		return ver.Compare(newFormatVersion) < 0, nil
```
Comment (michaelbeaumont) [inline pkg/managed/service.go:267]:
```suggestion
		return ver.LT(newFormatVersion), nil
```

**Review by michaelbeaumont — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
Hmm still not 100% the auto merge...
