### PR TITLE
Use correct VPC endpoint names for China regions

### LINKED ISSUE #3081: Failed to create private cluster in AWS China regions
**What were you trying to accomplish?**
create private cluster in AWS China regions(Beijing and Ningxia)

**What happened?**
Failed with below error message:
```
[✖]  error adding resources for VPC endpoints: error building endpoint service details: error describing VPC endpoint services: InvalidServiceName: The Vpc Endpoint Service 'cn.com.amazonaws.cn-northwest-1.s3' does not exist
        status code: 400, request id: 6fdefd95-7a31-4adf-bd4b-2a3a3195794a
```

**How to reproduce it?**

create cluster with below command and config file:
```
eksctl create cluster -f ./eks-private-cluster.yaml --region cn-northeast-1
```
eks-private-cluster.yaml:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-test
  region: cn-northwest-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

managedNodeGroups:
- name: ng1
  instanceType: c5.xlarge
  desiredCapacity: 1
  privateNetworking: true
```

**Logs**

```
[ℹ]  eksctl version 0.32.0
[ℹ]  using region cn-northwest-1
[ℹ]  setting availability zones to [cn-northwest-1c cn-northwest-1b cn-northwest-1a]
[ℹ]  subnets for cn-northwest-1c - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for cn-northwest-1b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for cn-northwest-1a - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "private-test" in "cn-northwest-1" region with managed nodes
[ℹ]  1 nodegroup (ng1) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=cn-northwest-1 --cluster=private-test'
[ℹ]  CloudWatch logging will not be enabled for cluster "private-test" in "cn-northwest-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=cn-northwest-1 --cluster=private-test'
[ℹ]  Kubernetes API endpoint access will use provided values {publicAccess=true, privateAccess=true} for cluster "private-test" in "cn-northwest-1"
[ℹ]  2 sequential tasks: { create cluster control plane "private-test", 2 sequential sub-tasks: { update cluster VPC endpoint access configuration, create managed nodegroup "ng1" } }
[ℹ]  building cluster stack "eksctl-private-test-cluster"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=cn-northwest-1 --name=private-test'
[✖]  error adding resources for VPC endpoints: error building endpoint service details: error describing VPC endpoint services: InvalidServiceName: The Vpc Endpoint Service 'cn.com.amazonaws.cn-northwest-1.s3' does not exist
        status code: 400, request id: 6fdefd95-7a31-4adf-bd4b-2a3a3195794a
```

**Anything else we need to know?**

The S3 Vpc Endpoint Service should be "com.amazonaws.cn-northwest-1.s3", no "cn." prefix.
Relevant code is [here](https://github.com/weaveworks/eksctl/blob/b91c8b5088e813fb39b029f52fb2db6512d14159/pkg/cfn/builder/vpc_endpoint.go#L131)

**Versions**

```
$ eksctl version
0.32.0
$ kubectl version
```

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Description

Fixes #3081 

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by Callisto13 — APPROVED** [review]
👍

File: pkg/cfn/builder/vpc_endpoint.go [hunk 1]
```diff
@@ -123,16 +123,27 @@ func (e *VPCEndpointResourceSet) hasEndpoint(endpoint string) bool {
...
+var chinaPartitionServiceHasChinaPrefix = map[string]bool{
+	api.EndpointServiceEC2:            true,
+	api.EndpointServiceECRAPI:         true,
+	api.EndpointServiceECRDKR:         true,
+	api.EndpointServiceS3:             false,
+	api.EndpointServiceSTS:            true,
+	api.EndpointServiceCloudFormation: true,
+	api.EndpointServiceAutoscaling:    true,
+	api.EndpointServiceCloudWatch:     false,
+}
```
Comment (cPu1) [inline pkg/cfn/builder/vpc_endpoint.go:135]: Since only S3 and CloudWatch do not have a prefix, we can have a map called `chinaPartitionServicesWithoutPrefix` containing just the two services, and invert the condition in the code below.

File: pkg/cfn/builder/vpc_endpoint.go [hunk 2]
```diff
@@ -123,16 +123,27 @@ func (e *VPCEndpointResourceSet) hasEndpoint(endpoint string) bool {
...
-	servicePrefix := ""
-	if api.Partition(region) == api.PartitionChina {
-		servicePrefix = "cn."
-	}
-	serviceRegionPrefix := fmt.Sprintf("%scom.amazonaws.%s.", servicePrefix, region)
+	serviceDomain := fmt.Sprintf("com.amazonaws.%s", region)
 	for i, endpoint := range endpoints {
-		serviceNames[i] = serviceRegionPrefix + endpoint
+		name := fmt.Sprintf("%s.%s", serviceDomain, endpoint)
+		if api.Partition(region) == api.PartitionChina && chinaPartitionServiceHasChinaPrefix[endpoint] {
```
Comment (cPu1) [inline pkg/cfn/builder/vpc_endpoint.go:143]: Based on the above comment, this would become:
```suggestion
		if api.Partition(region) == api.PartitionChina && !chinaPartitionServicesWithoutPrefix[endpoint] {
```

File: pkg/cfn/builder/vpc_endpoint.go (hunk 1 above)
Comment (michaelbeaumont) [reply pkg/cfn/builder/vpc_endpoint.go:135]: Ah I actually meant to add a check to make sure it's in the map and fail if not. I don't think we should assume either way.

Comment (michaelbeaumont) [reply pkg/cfn/builder/vpc_endpoint.go:135]: added, WDYT?

Comment (cPu1) [reply pkg/cfn/builder/vpc_endpoint.go:135]: That validation is already done in `ValidatePrivateCluster` before this code is run.

Comment (michaelbeaumont) [reply pkg/cfn/builder/vpc_endpoint.go:135]: I don't think so, I'm checking whether we have explicitly added the china prefix for that service, which is more of an assertion about the code.

Comment (cPu1) [reply pkg/cfn/builder/vpc_endpoint.go:135]: Ah, okay. This redundant check does require remembering to update two lists when a new endpoint service is added, and forgetting to update it here will break cluster creation for China regions.

**Review by cPu1 — APPROVED** [review]
