### PR TITLE
Fix node groups not joining the cluster

### LINKED ISSUE #1312: Nodegroups not joining the cluster
**What happened?**

Using the current version of `eksctl`, **0.5.2**, when creating two nodegroups using a config file, both nodegroups are created but just the first one joins the cluster. When checking the ConfigMap `aws-auth`, just one nodegroup is there.

**What you expected to happen?**

I would expect that all the nodegroups are added to the `aws-auth` ConfigMap, and therefore show up with `kubectl get nodes`.

**How to reproduce it?**

Using a **1.13** EKS cluster named `development`, use this config file, `test.yaml` to create the nodegroups with `eksctl create nodegroup -f test.yaml`.

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: development
  region: eu-west-1
  version: "1.13"

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    privateNetworking: true
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    privateNetworking: true
```

**Anything else we need to know?**

OS: macOS
eksctl: Installed using `brew`.

This issue seems to be introduced between **0.4.1** and **0.5.2**, as with 0.4.1 works fine.

**Versions**

```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.2"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

$ go version
go version go1.13 darwin/amd64
```

**Logs**

- Using `eksctl` **0.5.2**

```sh
$ eksctl create nodegroup -f test.yaml
[ℹ]  using region eu-west-1
[ℹ]  nodegroup "ng-1" will use "ami-0199284372364b02a" [AmazonLinux2/1.13]
[ℹ]  nodegroup "ng-2" will use "ami-0199284372364b02a" [AmazonLinux2/1.13]
[ℹ]  2 nodegroups (ng-1, ng-2) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 2 nodegroups in cluster "development"
[ℹ]  2 parallel tasks: { create nodegroup "ng-1", create nodegroup "ng-2" }
[ℹ]  building nodegroup stack "eksctl-development-nodegroup-ng-1"
[ℹ]  building nodegroup stack "eksctl-development-nodegroup-ng-2"
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-2
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-2
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-1
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-1
[ℹ]  deploying stack "eksctl-development-nodegroup-ng-2"
[ℹ]  deploying stack "eksctl-development-nodegroup-ng-1"
[ℹ]  adding role "arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-N75PLALYFBL1" to auth ConfigMap
[ℹ]  nodegroup "ng-1" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ng-1"
[ℹ]  nodegroup "ng-1" has 2 node(s)
[ℹ]  node "ip-10-3-43-18.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-10-3-6-25.eu-west-1.compute.internal" is ready

$ eksctl get nodegroups --cluster development
CLUSTER		NODEGROUP	CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID
development	ng-1		2019-09-08T19:41:02Z	2		2		2			t3.small	ami-0199284372364b02a
development	ng-2		2019-09-08T19:41:02Z	2		2		2			t3.small	ami-0199284372364b02a

$ kubectl get nodes
NAME                                       STATUS   ROLES    AGE   VERSION
ip-10-3-43-18.eu-west-1.compute.internal   Ready    <none>   93s   v1.13.8-eks-cd3eb0
ip-10-3-6-25.eu-west-1.compute.internal    Ready    <none>   93s   v1.13.8-eks-cd3eb0

$ kubectl get configmap -n kube-system aws-auth -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-N75PLALYFBL1
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-08T19:45:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "918"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b278b81-d271-11e9-987b-0a80449407fe
```

- Using `eksctl` **0.4.1**

```sh
$ eksctl create nodegroup -f test.yaml
[ℹ]  using region eu-west-1
[ℹ]  nodegroup "ng-1" will use "ami-00ac2e6b3cb38a9b9" [AmazonLinux2/1.13]
[ℹ]  nodegroup "ng-2" will use "ami-00ac2e6b3cb38a9b9" [AmazonLinux2/1.13]
[ℹ]  2 nodegroups (ng-1, ng-2) were included
[ℹ]  will create a CloudFormation stack for each of 2 nodegroups in cluster "development"
[ℹ]  2 parallel tasks: { create nodegroup "ng-1", create nodegroup "ng-2" }
[ℹ]  building nodegroup stack "eksctl-development-nodegroup-ng-2"
[ℹ]  building nodegroup stack "eksctl-development-nodegroup-ng-1"
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-1
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-1
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-2
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-2
[ℹ]  deploying stack "eksctl-development-nodegroup-ng-1"
[ℹ]  deploying stack "eksctl-development-nodegroup-ng-2"
[ℹ]  adding role "arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-2RX93EXNE729" to auth ConfigMap
[ℹ]  nodegroup "ng-1" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ng-1"
[ℹ]  nodegroup "ng-1" has 2 node(s)
[ℹ]  node "ip-10-3-20-98.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-10-3-47-125.eu-west-1.compute.internal" is ready
[ℹ]  adding role "arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-14X8P4JO00HZO" to auth ConfigMap
[ℹ]  nodegroup "ng-2" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ng-2"
[ℹ]  nodegroup "ng-2" has 2 node(s)
[ℹ]  node "ip-10-3-41-213.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-10-3-7-52.eu-west-1.compute.internal" is ready
[✔]  created 2 nodegroup(s) in cluster "development"
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration

$ eksctl get nodegroups --cluster development
CLUSTER		NODEGROUP	CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID
development	ng-1		2019-09-08T19:50:26Z	2		2		2			t3.small	ami-00ac2e6b3cb38a9b9
development	ng-2		2019-09-08T19:50:26Z	2		2		2			t3.small	ami-00ac2e6b3cb38a9b9

$ kubectl get nodes
NAME                                        STATUS   ROLES    AGE     VERSION
ip-10-3-20-98.eu-west-1.compute.internal    Ready    <none>   2m20s   v1.13.7-eks-c57ff8
ip-10-3-41-213.eu-west-1.compute.internal   Ready    <none>   2m7s    v1.13.7-eks-c57ff8
ip-10-3-47-125.eu-west-1.compute.internal   Ready    <none>   2m19s   v1.13.7-eks-c57ff8
ip-10-3-7-52.eu-west-1.compute.internal     Ready    <none>   2m2s    v1.13.7-eks-c57ff8

$ kubectl get configmap -n kube-system aws-auth -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-2RX93EXNE729
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::930347582273:role/eksctl-development-nodegroup-ng-NodeInstanceRole-14X8P4JO00HZO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-08T19:45:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1951"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b278b81-d271-11e9-987b-0a80449407fe
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #1312 

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] All unit tests passing (i.e. `make test`)
- [x] Manually tested

### CODE REVIEW

File: pkg/ctl/create/nodegroup.go [hunk 1]
```diff
@@ -168,8 +168,6 @@ func doCreateNodeGroups(cmd *cmdutils.Cmd, updateAuthConfigMap bool) error {
 				logger.Info("as you are using a GPU optimized instance type you will need to install NVIDIA Kubernetes device plugin.")
 				logger.Info("\t see the following page for instructions: https://github.com/NVIDIA/k8s-device-plugin")
 			}
-
-			return nil
```
Comment (errordeveloper) [inline pkg/ctl/create/nodegroup.go]: Ok, so this a stale line since we removed `ngFilter.ForEach`, right? In that case, I think this a candidate for 0.5.3.

Comment (cPu1) [reply pkg/ctl/create/nodegroup.go]: That's right. I was also planning to include it in 0.5.3.
