### PR TITLE
Fix error with install-vpc-controllers

### LINKED ISSUE #1452: Error with util install-vpc-controllers when trying to create windows nodes.
**What happened?**
 I tried to use eksctl to create a windows EKS cluster.  I was able to successfully create a linux cluster following the steps in https://eksworkshop.com/ using eskctl from cloud9.

But when trying to set up a windows cluster using the same environment and following the steps in the the blog https://aws.amazon.com/blogs/aws/amazon-eks-windows-container-support-now-generally-available/ and the documentation https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

it fails on the step...
*eksctl utils install-vpc-controllers --name demo-windows-cluster --approve*
  with the error
_[:information_source:]  using region us-west-2_
_[:information_source:]  replaced "ClusterRole.rbac.authorization.k8s.io/vpc-resource-controller"_
_[:information_source:]  replaced "ClusterRoleBinding.rbac.authorization.k8s.io/vpc-resource-controller"_
_[:information_source:]  replaced "kube-system:ServiceAccount/vpc-resource-controller"_
_[:information_source:]  replaced "kube-system:Deployment.apps/vpc-resource-controller"_
_[:information_source:]  created "CertificateSigningRequest.certificates.k8s.io/vpc-admission-webhook.kube-system"_
[:heavy_multiplication_x:]  _error installing VPC controller: failed to find certificate after approval_

If I run that command a second time, the error goes away ...
_[:information_source:]  using region us-west-2_
_[:information_source:]  replaced "ClusterRole.rbac.authorization.k8s.io/vpc-resource-controller"_
_[:information_source:]  replaced "ClusterRoleBinding.rbac.authorization.k8s.io/vpc-resource-controller"_
_[:information_source:]  replaced "kube-system:ServiceAccount/vpc-resource-controller"_
_[:information_source:]  replaced "kube-system:Deployment.apps/vpc-resource-controller"_
_[:information_source:]  replaced "kube-system:Service/vpc-admission-webhook"_
_[:information_source:]  replaced "kube-system:Deployment.apps/vpc-admission-webhook"_
_[:information_source:]  replaced "kube-system:MutatingWebhookConfiguration.admissionregistration.k8s.io/vpc-admission-webhook-cfg"_

and I was able to add windows nodes.  However the sample app, windows-server-IIS.yaml, containers never start up so clearly there is a problem.  

Since I was using a corporate account with some limits on permissions (IAM and Organization) are specific permissions I know I don't have,  I created a personal AWS account and tried the same thing again...successfully following the workshop using eskctl and creating the cluster, then removing it and attempting to create the windows cluster as per the blog.  I got the same error running...
*eksctl utils install-vpc-controllers --name demo-windows-cluster --approve*
...
[:heavy_multiplication_x:]  _error installing VPC controller: failed to find certificate after approval_

I also tried this command on the cluster created according to the workshop instructions with the same result. 

I  attempting to create the sample application in my personal account after seeing the error with install-vpc-controllers and re-running it to hide the error as above with the same result.

I have not tried the above outside Cloud9 but previously I have only managed to get EKS to work using eskctl in Cloud9.  I was never able to get the non eskctl method to work to create a cluster I guessed due to IAM authorization problems.  I found the documentation is vague complex and assumes too much.

**What you expected to happen?**
I expect to be able to create a Windows nodes using eskctl and be able to run the sample application.

**How to reproduce it?**
see above

**Anything else we need to know?**
Using Firefox running on Windows 10 to access AWS, Cloud9 etc but doubt that matters.
I originally posted the problem on the #eks slack group as Tim

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.7.0"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}```

**Logs**
see above

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #1452

### Checklist
- [x] Manually tested

### CODE REVIEW

File: pkg/addons/vpc_controller.go [hunk 1]
```diff
@@ -134,15 +136,53 @@ func (v *VPCController) generateCert() error {
 		return errors.Wrap(err, "updating approval")
 	}
 
-	approvedCSR, err := csrClientSet.Get(certificateSigningRequest.Name, metav1.GetOptions{})
+	logger.Info("waiting for certificate to be available")
+
+	watchTimeout := 45 * time.Second
```
Comment (martina-if) [inline pkg/addons/vpc_controller.go]: I would make this timeout a constant at the beginning of the file with a name so we can search for it (something like `certificateWaitTimeout`). There is also the `--timeout` flag, should we use that instead?

File: pkg/addons/vpc_controller.go [hunk 2]
```diff
@@ -134,15 +136,53 @@ func (v *VPCController) generateCert() error {
...
+	defer watcher.Stop()
+
+	timer := time.NewTimer(timeout)
+	defer timer.Stop()
+
+	for {
+		select {
+		case event, ok := <-watcher.ResultChan():
+			if !ok {
+				return nil, errors.New("unexpected close of ResultChan")
```
Comment (martina-if) [inline pkg/addons/vpc_controller.go]: Might not be super useful to the user. Perhaps "failed waiting for certificate. unexpected close of channel"?

File: pkg/addons/vpc_controller.go (hunk 1 above)
Comment (cPu1) [reply pkg/addons/vpc_controller.go]: I agree with making it a package-level variable but using the `--timeout` option for this may not be very intuitive. Also, the watch is an internal detail and IMO the timeout shouldn't be configurable.
