### PR TITLE
fix #1871, add partion check(aws-cn,aws) for OpenIDConnectProviderArn

### LINKED ISSUE #1871: IAM Role for service account is not working in AWS China regions
**What happened?**

I am testing the eksctl 0.15.0-rc.0. 

By following the [official doc](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html) to set up IAM service account, then I connect to Pod to execute following command with service account enabled:
```
sh-4.2# aws sts get-caller-identity --region=cn-northwest-1
An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

Root cause of this issue is that the aws partition of OpenIDConnectProviderArn is in-correct: https://github.com/weaveworks/eksctl/blob/4d238734bef69eff6d2731e2c321371d6677970c/pkg/iam/oidc/api.go#L63

**What you expected to happen?**
IRSA should work in China regions.

**How to reproduce it?**
Just following [official doc](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html)

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0-rc.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

### PR DESCRIPTION
**Pull request by stevensu1977**
### Description
Fix IAM Role for service account is not working in AWS China regions #1871

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `site/content` directory)
- [x] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

**Comment by stevensu1977** [comment]
@martina-if  @cPu1  can you assign a reviewer , review my commit ?  Thanks a lot !

File: pkg/iam/oidc/api.go [hunk 1]
```diff
@@ -58,10 +59,17 @@ func NewOpenIDConnectManager(iamapi iamiface.IAMAPI, accountID, issuer string) (
 // CheckProviderExists will return true when the provider exists, it may return errors
 // if it was unable to call IAM API
 func (m *OpenIDConnectManager) CheckProviderExists() (bool, error) {
+
+	//check region partion
+	partion := "aws"
+	if strings.Contains(m.issuerURL.Host, "amazonaws.com.cn") {
+		partion = "aws-cn"
+	}
```
Comment (cPu1) [inline pkg/iam/oidc/api.go]: The partition information is extracted in `ClusterProvider.NewOpenIDConnectManager` from the EKS cluster's ARN: https://github.com/weaveworks/eksctl/blob/de84cc0e11805eab79bba79208a41d23e8668af6/pkg/eks/eks.go#L233
Instead of extracting that information again from the issuer's host, WDYT about passing the partition to `iamoidc.NewOpenIDConnectManager`?

So this line https://github.com/weaveworks/eksctl/blob/de84cc0e11805eab79bba79208a41d23e8668af6/pkg/eks/eks.go#L243 becomes
```golang
return iamoidc.NewOpenIDConnectManager(c.Provider.IAM(), accountID, *c.Status.clusterInfo.cluster.Identity.Oidc.Issuer, parsedARN.Partition)
```

**Comment by stevensu1977** [comment]
@cPu1  thank your comments ,  I already  changed it  and fix test issue.

**Comment by cPu1** [comment]
@stevensu1977 I changed the base branch to `master` and there are some conflicting files because I pushed a related change earlier today. Could you rebase and resolve the conflicts? I can also do it if you're fine with it.

**Comment by stevensu1977** [comment]
@cPu1  when I rebase my code I made a mistake , so take a long time ,conflicts  resolved just completed , of course you can manual merge my PR/code ,  thank your kindly help !

**Comment by cPu1** [comment]
@stevensu1977 it looks the rebase got done against the release branch and now I see conflicts trying to rebase with master. May I suggest resetting your branch's changes and basing it off master, and making this one-line change:

https://github.com/weaveworks/eksctl/blob/d375fd2e3a0f480d7453ea3229ece8c236ac543b/pkg/iam/oidc/api.go#L73-L77

to

```golang
	input := &awsiam.GetOpenIDConnectProviderInput{
		OpenIDConnectProviderArn: aws.String(
			fmt.Sprintf("arn:%s:iam::%s:oidc-provider/%s", m.partition, m.accountID, m.hostnameAndPath()),
		),
	}
```
