### PR TITLE
Unpin and fix containerd integration test

### LINKED ISSUE #4294: containerd runtime integration test failing
failed 3 times in a row: https://github.com/weaveworks/eksctl/runs/3790538994?check_suite_focus=true

times out when waiting for the nodegroup to report healthy
```
[0] 2021-10-04 16:25:12 [ℹ]  adding identity "arn:aws:iam::<redacted>:role/eksctl-it-crud-floral-rainbow-163-NodeInstanceRole-1NIOK5ODMQKJI" to auth ConfigMap
[0] 2021-10-04 16:25:12 [▶]  saved auth ConfigMap for "test-containerd"
[0] 2021-10-04 16:25:13 [ℹ]  nodegroup "test-containerd" has 0 node(s)
[0] 2021-10-04 16:25:13 [ℹ]  waiting for at least 2 node(s) to become ready in "test-containerd"
...
```

inspecting `kubectl get nodes` shows the nodes as not registered

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

Closes #4294 

Run proof:

```
Ran 1 of 41 Specs in 1640.415 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 40 Skipped
```

Although focused, this test should not interfere with the rest as it has been running for a while now. I'm running a full suite but that takes hours.

Until then, this is the fix.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: integration/tests/crud/creategetdelete_test.go [hunk 1]
```diff
@@ -404,6 +404,7 @@ var _ = Describe("(Integration) Create, Get, Scale & Delete", func() {
 			})
 			It("should create the nodegroup without problems", func() {
 				clusterConfig := makeClusterConfig()
+				clusterConfig.Metadata.Name = params.ClusterName
```
Comment (aclevername) [inline integration/tests/crud/creategetdelete_test.go:407]: nooooooooooo :joy:

**Review by aclevername — APPROVED** [review]
lmao
