### PR TITLE
Fix propagating errors from AssignSubnets

### LINKED ISSUE #1657: Error: VPCZoneIdentifier must be of type List of String
Reported by a user on Slack:

>I'm having an issue with Cloudformation reporting to eksctl that VPCZoneIdentifier must be of type List of String when running
```
eksctl create cluster -f cluster.yaml
ℹ]  eksctl version 0.10.2
[ℹ]  using region us-east-1
....
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-cluster-stgv1-nodegroup-ng-1"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "Value of property VPCZoneIdentifier must be of type List of String"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=cluster-stgv1'
[✖]  waiting for CloudFormation stack "eksctl-cluster-stgv1-nodegroup-ng-1": ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "cluster-stgv1"
```
eksctl version is 0.10.2
and the config.yaml
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-stgv2
  region: us-east-1
vpc:
  # clusterEndpoints:
  #   privateAccess: true
  cidr: 10.133.0.0/24
  autoAllocateIPv6: false
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)
nodeGroups:
  - name: ng-1
    availabilityZones:
      - "us-east-1a"
      - "us-east-1b"
    instanceType: m3.medium
    desiredCapacity: 6
    minSize: 6
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    # kubeletExtraConfig:
    #     kubeReserved:
    #         cpu: "300m"
    #         memory: "300Mi"
    #         ephemeral-storage: "1Gi"
    #     kubeReservedCgroup: "/kube-reserved"
    #     systemReserved:
    #         cpu: "300m"
    #         memory: "300Mi"
    #         ephemeral-storage: "1Gi"
    #     evictionHard:
    #         memory.available:  "200Mi"
    #         nodefs.available: "10%"
    #     featureGates:
    #         DynamicKubeletConfig: true
    #         RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled
    amiFamily: AmazonLinux2
    ssh: # import default public key (~/.ssh/id_rsa.pub)
      allow: true
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        cloudWatch: true
        albIngress: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description
Fixes propagating errors from `AssignSubnets`.

Fixes #1657 

### Checklist
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`) and target version (e.g. `version/0.12.0`)
- [ ] Added note in `docs/release_notes/draft.md` (or relevant release note)

### CODE REVIEW

File: pkg/cfn/builder/nodegroup.go [hunk 1]
```diff
@@ -197,27 +199,30 @@ func AssignSubnets(availabilityZones []string, clusterStackName string, clusterS
 			return fmt.Sprintf("(subnets=%#v AZs=%#v)", subnets, availabilityZones)
 		}
 		if len(subnets) < numNodeGroupsAZs {
-			return fmt.Errorf("VPC doesn't have enough subnets for nodegroup AZs %s", makeErrorDesc())
+			return nil, fmt.Errorf("VPC doesn't have enough subnets for nodegroup AZs %s", makeErrorDesc())
 		}
-		vpcZoneIdentifier = make([]interface{}, numNodeGroupsAZs)
+		subnetIDs := make([]string, numNodeGroupsAZs)
```
Comment (martina-if) [inline pkg/cfn/builder/nodegroup.go]: Thanks!
