### PR TITLE
Fix upgrading managed nodegroups

### LINKED ISSUE #1962: fail to update managed worker nodes from 1.14 to 1.15
**What happened?**
eksctl failed to get the correct AMI:
from Cloudformation stack
```
Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2e3ded7b-7955-4255-8945-ccc201882424)
```

**What you expected to happen?**
Worker nodes should be 1.15

**How to reproduce it?**
```sh
echo export cluster="old-cluster"
# create a eks cluster + managed worker nodes
eksctl create cluster \
    --name $cluster \
    --version 1.14 \
    --managed
# update control plane
eksctl update cluster --name $cluster --approve

# update add-ons
eksctl utils update-kube-proxy \
    --cluster $cluster \
    --approve

eksctl utils update-aws-node \
    --cluster $cluster \
    --approve

eksctl utils update-coredns \
    --cluster $cluster \
    --approve
# try to update managed worker nodes:
export MANAGED_NODE_GROUP=$(eksctl get nodegroup --cluster $cluster -ojson|jq -r '.[].Name')

echo eksctl upgrade nodegroup \
    --name=${MANAGED_NODE_GROUP} \
    --cluster=$cluster \
    --kubernetes-version=1.15
```
**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
eksctl version
0.15.0

kubectl version --short
Client Version: v1.14.7-eks-1861c5
Server Version: v1.15.10-eks-bac369
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

```[ℹ]  Update nodegroup stack
[✖]  unexpected status "UPDATE_ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 501bd6c8-c0bd-43c9-874b-5be995316fe5)"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2e3ded7b-7955-4255-8945-ccc201882424)"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: CREATE_IN_PROGRESS – "User Initiated"
```

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Currently, AMIs published for EKS worker nodes are not immediately available for use with managed nodegroups. To work around this, this change uses the AWS EKS Nodegroup API and leaves the ReleaseVersion unset to allow the default behaviour of the API choosing the latest available AMI version.

This change also switches from updating the CloudFormation stack to using the UpdateNodegroupVersion API call, because with the ReleaseVersion no longer being set to the latest AMI release obtained via SSM, some other field must be updated in order to trigger a stack update. Rather than use a hack like updating a label on the nodegroup, we simply use the UpdateNodegroupVersion API call which also gives more control over the update process.

Fixes #1962 

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

File: pkg/managed/service.go [hunk 1]
```diff
@@ -114,118 +113,121 @@ func (m *Service) GetLabels(nodeGroupName string) (map[string]string, error) {
...
+	logger.Info("nodegroup upgrade request submitted")
+	return nil
 }
 
-func (m *Service) updateNodeGroupVersion(nodeGroupName, releaseVersion string) error {
-	template, err := m.stackCollection.GetManagedNodeGroupTemplate(nodeGroupName)
-	if err != nil {
-		return err
-	}
+func (m *Service) waitForUpdate(ctx context.Context, nodeGroupName string, updateID *string) error {
```
Comment (michaelbeaumont) [inline pkg/managed/service.go:169]: can this code be replaced with the function here: https://github.com/weaveworks/eksctl/blob/8faceb2d3f5ae1b1065d24624615866eac16e7da/pkg/eks/update.go#L201

Comment (cPu1) [reply pkg/managed/service.go:169]: I avoided using it because that function is tied to `ClusterProvider` and uses fields, like the `WaitTimeout`, that are set when `ClusterProvider` is created and can't be changed later. We could refactor it but that'd require changing all calling code, which I think would've been out of scope of this PR, but I think we can address it in a separate PR. Moreover, the `DescribeUpdateRequest` in `waitForUpdateToSucceed` lacks the `NodegroupName` field, so I'm not sure if it'd still work the same (although I think the update ID should suffice).
