### PR TITLE
Do not wait for aws-ebs-csi-driver if there are no nodegroups

### LINKED ISSUE #5891: [Bug] creating cluster with --without-nodegroups and aws-ebs-csi-driver addon fails
### What were you trying to accomplish?
Hi, I wanted to create a cluster with no nodegroups (managed nodegroups are defined in the config though) and the aws-ebs-csi-driver addon.
We want to create the cluster without nodes as we need to roll out calico and remove the aws-node deployment.

### What happened?
The cluster create failed with status degraded, unfortunately I don't have the exact logs anymore.

### How to reproduce it?
Create cluster using a config file containing a managed nodegroup and the aws-ebs-csi-driver addon.
Run eksctl create cluster -f config.yaml --without-nodegroups.

**Anything else we need to know?**
Using eksctl on macOS Monterey, downloaded through brew.
AWS Credentials are managed by aws-vault.

I found https://github.com/weaveworks/eksctl/pull/4629 and was wondering if maybe the check doesn't recognize the --without-nodegroups flag?

After creating the nodegroups the addon works as expected, the major issue for us is that some of the finalizing steps such as making the cluster endpoint private only are missing.

**Versions**
```
❯ eksctl info
eksctl version: 0.117.0-dev+98027776c.2022-11-04T12:59:49Z
kubectl version: v1.21.0+vmware.1-wcp
OS: darwin
```

### PR DESCRIPTION
**Pull request by radTuti**
### Description

similar to #5458; closes #5891, #5585

aws-ebs-csi-driver will stay in degraded state until nodegroups are added.
SInce the addon is now a requirement for k8s 1.23, the cluster creation should not fail.

#### Manual validation

Given cluster config  `cluster.yaml`

```yaml
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: cluster-1jnq
  region: us-west-2
  version: "1.23"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
    roleOnly: true
    roleName: cluster-1jnq-AmazonEKS_EBS_CSI_DriverRole

addons:
- name: aws-ebs-csi-driver
  version: v1.11.4-eksbuild.1
  serviceAccountRoleARN: arn:aws:iam::ACCOUNT_ID:role/cluster-1jnq-AmazonEKS_EBS_CSI_DriverRole

nodeGroups:
  - name: worker-pool
    instanceType: t3.large
    desiredCapacity: 3

```

Running `eksctl create cluster -f cluster.yaml --without-nodegroup` successfully creates the cluster with no node group.

Additional validated scenarios:
- setting `desiredCapacity: 0` in `cluster.yaml` and running `eksctl create cluster -f cluster.yaml`
- setting `desiredCapacity:0`, `maxSize: 3` in `cluster.yaml` and running `eksctl create cluster -f cluster.yaml`

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] ~Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)~
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [x] Backfilled missing tests for code in same general area :tada:
- [x] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/actions/addon/addon_test.go [hunk 1]
```diff
@@ -1,19 +1,51 @@
...
+		})
+	})
+
+	When("addon is aws-ebs-csi-driver with no nodegroup", func() {
+		It("does not wait for addon to be active", func() {
+			a := &api.Addon{
+				Name: api.AWSEBSCSIDriverAddon,
+			}
+			err := addon.ExportWaitForAddonToBeActive(manager, context.Background(), a, 0)
+			Expect(err).To(BeNil())
```
Comment (cPu1) [inline pkg/actions/addon/addon_test.go:48]: This should go in `pkg/actions/addon/create_test.go` and, as noted in the comment above, it should be tested by calling `manager.Create`.

File: pkg/actions/addon/create.go [hunk 2]
```diff
@@ -23,8 +23,6 @@ import (
 
 const (
 	kubeSystemNamespace = "kube-system"
-	vpcCNIName          = "vpc-cni"
-	ebsCSIDriverName    = "aws-ebs-csi-driver"
```
Comment (cPu1) [inline pkg/actions/addon/create.go:27]: :+1:

**Review by cPu1 — COMMENTED** [review]
Thanks for the detailed PR. I have left some suggestions on improving the tests but otherwise it LGTM!

**Comment by radTuti** [comment]
> Thanks for the detailed PR. I have left some suggestions on improving the tests but otherwise it LGTM!

Thanks for the review and updating the tests. I have updated the branch. Is there anything else needed to get this merged?

**Review by cPu1 — APPROVED** [review]
