### PR TITLE
gitops apply: use temp dir instead of --output-path

### LINKED ISSUE #1274: `eksctl gitops apply`  CLI flag validations
Today the value of `--output-path` is not checked before starting to run the command's actions so if it points to an existing folder that already contains something it will fail too late.

eksctl should validate values for all flags as early as possible.

Example:
```
$ EKSCTL_EXPERIMENTAL=true eksctl gitops apply --cluster martina-test-3 --region eu-north-1 --git-url=git@github.com:martina-if/flux-test-3 --output-path=/tmp/gitops-repos2/  --quickstart-profile app-dev --git-email me@me.com
[ℹ]  Generating public key infrastructure for the Helm Operator and Tiller
[ℹ]    this may take up to a minute, please be patient
[!]  Public key infrastructure files were written into directory "/tmp/eksctl-helm-pki113134613"
[!]  please move the files into a safe place or delete them
[ℹ]  Generating manifests
.
.
.
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:42359/healthz: EOF), retrying ...
[ℹ]  Helm Operator started successfully
[ℹ]  see https://docs.fluxcd.io/projects/helm-operator for details on how to use the Helm Operator
[ℹ]  Waiting for Flux to start
[ℹ]  Flux started successfully
[ℹ]  see https://docs.fluxcd.io/projects/flux for details on how to use Flux
[ℹ]  Committing and pushing manifests to git@github.com:martina-if/flux-test-3
[master 23ddde8] Add Initial Flux configuration
 2 files changed, 39 insertions(+), 38 deletions(-)
 rewrite flux/tiller-ca-cert-configmap.yaml (86%)
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.83 KiB | 1.83 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:martina-if/flux-test-3
   31443a8..23ddde8  master -> master
[ℹ]  Flux will only operate properly once it has write-access to the Git repository
fatal: destination path '/tmp/gitops-repos2/flux-test-3' already exists and is not an empty directory.
```

### PR DESCRIPTION
**Pull request by marccarre**
### WARNING: UX decision

This PR should only be merged if we decide we no longer want to generate a local clone of the user's configuration repository as an output.

### Description

Given end-users provide their configuration Git repository as an input, it makes little sense to return it, cloned locally, as an output. Instead, `eksctl gitops apply` now:

- no longer expose `--output-path`,
- uses a temporary directory instead, for cloning and file operations,
- expects that the end-user already has, or soon will clone this
  repository, and will "pull" the latest changes themselves, once
  they have run `eksctl gitops apply`.

Fixes #1274.

### Checklist

- [x] Code compiles correctly (i.e `make build`)
- [x] ~Added tests that cover your change (if possible)~
- [x] All unit tests passing (i.e. `make test`)
- [x] ~Added/modified documentation as required (such as the `README.md`, and `examples` directory)~
- [x] Manually tested

### Manual tests

```console
$ cd $GOPATH/src/github.com/weaveworks/eksctl
$ make build
```

Using the default (current directory) fails, as it is a non-empty directory:
```console
$ EKSCTL_EXPERIMENTAL=true ./eksctl \
    -f examples/eks-quickstart-app-dev.yaml \
    gitops apply \
    --quickstart-profile git@github.com:marccarre/eks-quickstart-app-dev.git \
    --git-url git@github.com:marccarre/my-gitops-repo.git \
    --git-email carre.marc+eksctl@gmail.com

[ℹ]  Generating public key infrastructure for the Helm Operator and Tiller
[ℹ]    this may take up to a minute, please be patient
[!]  Public key infrastructure files were written into directory "/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/eksctl-helm-pki208351179"
[!]  please move the files into a safe place or delete them
[ℹ]  Generating manifests
[ℹ]  Cloning git@github.com:marccarre/my-gitops-repo.git
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/eksctl-install-flux-clone-244413614'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 367 (delta 23), reused 45 (delta 10), pack-reused 306
Receiving objects: 100% (367/367), 147.66 KiB | 440.00 KiB/s, done.
Resolving deltas: 100% (130/130), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  Writing Flux manifests
[ℹ]  created "Namespace/flux"
[ℹ]  Applying Helm TLS Secret(s)
[ℹ]  created "flux:Secret/flux-helm-tls-cert"
[ℹ]  created "flux:Secret/tiller-secret"
[!]  Note: certificate secrets aren't added to the Git repository for security reasons
[ℹ]  Applying manifests
[ℹ]  created "flux:Deployment.apps/flux"
[ℹ]  created "flux:Deployment.apps/memcached"
[ℹ]  created "flux:Service/memcached"
[ℹ]  created "flux:ConfigMap/flux-helm-tls-ca-config"
[ℹ]  created "flux:Deployment.extensions/tiller-deploy"
[ℹ]  created "flux:ServiceAccount/flux"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/flux"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/flux"
[ℹ]  created "CustomResourceDefinition.apiextensions.k8s.io/helmreleases.helm.fluxcd.io"
[ℹ]  created "flux:Deployment.apps/flux-helm-operator"
[ℹ]  created "flux:Service/tiller-deploy"
[ℹ]  created "flux:ServiceAccount/tiller"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/tiller"
[ℹ]  created "flux:ServiceAccount/helm"
[ℹ]  created "flux:Role.rbac.authorization.k8s.io/tiller-user"
[ℹ]  created "kube-system:RoleBinding.rbac.authorization.k8s.io/tiller-user-binding"
[ℹ]  created "flux:ServiceAccount/flux-helm-operator"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  created "flux:Secret/flux-git-deploy"
[ℹ]  Waiting for Helm Operator to start
ERROR: logging before flag.Parse: E0917 19:35:56.171265   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:35:56 socat[25373] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:35:58.200229   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:35:58 socat[25374] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:00.233366   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:00 socat[25375] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:02.267884   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:02 socat[25376] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:04.298357   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:04 socat[25404] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:06.328215   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:06 socat[25408] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:08.361427   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:08 socat[25409] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:10.390164   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:10 socat[25410] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:12.422270   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:12 socat[25414] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:14.452200   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:14 socat[25415] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:36:16.482849   72791 portforward.go:331] an error occurred forwarding 60861 -> 3030: error forwarding port 3030 to pod f3d326e41c475fdf0ea62339e2b52912c2936646d7c96c17a79fd3aabf510d3d, uid : exit status 1: 2019/09/17 10:36:16 socat[25418] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60861/healthz: EOF), retrying ...
[ℹ]  Helm Operator started successfully
[ℹ]  see https://docs.fluxcd.io/projects/helm-operator for details on how to use the Helm Operator
[ℹ]  Waiting for Flux to start
[ℹ]  Flux started successfully
[ℹ]  see https://docs.fluxcd.io/projects/flux for details on how to use Flux
[ℹ]  Committing and pushing manifests to git@github.com:marccarre/my-gitops-repo.git
[master 2401b70] Add Initial Flux configuration
 1 file changed, 38 insertions(+), 38 deletions(-)
 rewrite flux/tiller-ca-cert-configmap.yaml (87%)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.13 KiB | 2.13 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:marccarre/my-gitops-repo.git
   0dda406..2401b70  master -> master
[ℹ]  Flux will only operate properly once it has write-access to the Git repository
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/my-gitops-repo124594972/my-gitops-repo'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 371 (delta 25), reused 48 (delta 11), pack-reused 306
Receiving objects: 100% (371/371), 149.90 KiB | 429.00 KiB/s, done.
Resolving deltas: 100% (132/132), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  cloning repository "git@github.com:marccarre/eks-quickstart-app-dev.git":master
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/quickstart-771602485'...
remote: Enumerating objects: 190, done.
remote: Total 190 (delta 0), reused 0 (delta 0), pack-reused 190
Receiving objects: 100% (190/190), 48.32 KiB | 151.00 KiB/s, done.
Resolving deltas: 100% (84/84), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  processing template files in repository
[ℹ]  writing new manifests to "/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/my-gitops-repo124594972/my-gitops-repo/base"
[ℹ]  Nothing to commit (the repository contained identical files), moving on
Everything up-to-date
[ℹ]  please configure git@github.com:marccarre/my-gitops-repo.git so that the following Flux SSH public key has write access to it
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCokQQ+tiKTKpAYsCgn/bDP2iDJvtm/k63SqwEtbakI06I/Ub2z6LHWwrbx1y4ZqNd2AXfpfZ+82Ymwu0yy8ZIzzPXnLvf0d8r1ewsORySkavTRAmPmexA+CtprKfAGxv1Nya7L0N/YdOX9Ww3M/7xfus8T6ZQQ158XKttooATJBPQ35Nzv10GGiwdzjgQ0ZQALf+b0mDj4xObDwvzeOK7L90dLRu3F1pGNhA8wxq8+RkVJXBVPlnHcbx9o+fbINNzXtp06OJmi0EQmvEnPzFGW7Qmpcas4raYtIv3DlRfTgFf3x2QJ397RfafJfM7H/ebPKDdC96jlzVWxykjgjtcL
```

Re-running the command now no longer complains about the directory:

```console
$ EKSCTL_EXPERIMENTAL=true ./eksctl \
    -f examples/eks-quickstart-app-dev.yaml \
    gitops apply \
    --quickstart-profile git@github.com:marccarre/eks-quickstart-app-dev.git \
    --git-url git@github.com:marccarre/my-gitops-repo.git \
    --git-email carre.marc+eksctl@gmail.com

[ℹ]  Generating public key infrastructure for the Helm Operator and Tiller
[ℹ]    this may take up to a minute, please be patient
[!]  Public key infrastructure files were written into directory "/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/eksctl-helm-pki047560648"
[!]  please move the files into a safe place or delete them
[ℹ]  Generating manifests
[ℹ]  Cloning git@github.com:marccarre/my-gitops-repo.git
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/eksctl-install-flux-clone-438350471'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 371 (delta 25), reused 48 (delta 11), pack-reused 306
Receiving objects: 100% (371/371), 149.90 KiB | 439.00 KiB/s, done.
Resolving deltas: 100% (132/132), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  Writing Flux manifests
[ℹ]  Applying Helm TLS Secret(s)
[ℹ]  deleted "flux:Secret/flux-helm-tls-cert"
[ℹ]  deleted "flux:Secret/tiller-secret"
[ℹ]  created "flux:Secret/flux-helm-tls-cert"
[ℹ]  created "flux:Secret/tiller-secret"
[!]  Note: certificate secrets aren't added to the Git repository for security reasons
[ℹ]  Applying manifests
[ℹ]  deleted "flux:ServiceAccount/flux"
[ℹ]  deleted "ClusterRole.rbac.authorization.k8s.io/flux"
[ℹ]  deleted "ClusterRoleBinding.rbac.authorization.k8s.io/flux"
[ℹ]  deleted "flux:Deployment.apps/flux-helm-operator"
[ℹ]  deleted "flux:ConfigMap/flux-helm-tls-ca-config"
[ℹ]  deleted "flux:ServiceAccount/tiller"
[ℹ]  deleted "ClusterRoleBinding.rbac.authorization.k8s.io/tiller"
[ℹ]  deleted "flux:ServiceAccount/helm"
[ℹ]  deleted "flux:Role.rbac.authorization.k8s.io/tiller-user"
[ℹ]  deleted "kube-system:RoleBinding.rbac.authorization.k8s.io/tiller-user-binding"
[ℹ]  deleted "flux:Service/tiller-deploy"
[ℹ]  deleted "flux:Service/memcached"
[ℹ]  deleted "flux:ServiceAccount/flux-helm-operator"
[ℹ]  deleted "ClusterRole.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  deleted "ClusterRoleBinding.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  deleted "CustomResourceDefinition.apiextensions.k8s.io/helmreleases.helm.fluxcd.io"
[ℹ]  deleted "flux:Deployment.apps/flux"
[ℹ]  deleted "flux:Deployment.apps/memcached"
[ℹ]  deleted "flux:Deployment.extensions/tiller-deploy"
[ℹ]  created "flux:ServiceAccount/flux"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/flux"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/flux"
[ℹ]  created "flux:Deployment.apps/flux-helm-operator"
[ℹ]  created "flux:ConfigMap/flux-helm-tls-ca-config"
[ℹ]  created "flux:ServiceAccount/tiller"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/tiller"
[ℹ]  created "flux:ServiceAccount/helm"
[ℹ]  created "flux:Role.rbac.authorization.k8s.io/tiller-user"
[ℹ]  created "kube-system:RoleBinding.rbac.authorization.k8s.io/tiller-user-binding"
[ℹ]  created "flux:Service/tiller-deploy"
[ℹ]  created "flux:Service/memcached"
[ℹ]  created "flux:ServiceAccount/flux-helm-operator"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/flux-helm-operator"
[ℹ]  created "CustomResourceDefinition.apiextensions.k8s.io/helmreleases.helm.fluxcd.io"
[ℹ]  created "flux:Deployment.apps/flux"
[ℹ]  created "flux:Deployment.apps/memcached"
[ℹ]  created "flux:Deployment.extensions/tiller-deploy"
[ℹ]  Waiting for Helm Operator to start
ERROR: logging before flag.Parse: E0917 19:38:53.621977   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:38:53 socat[27433] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:38:55.652031   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:38:55 socat[27438] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:38:57.681135   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:38:57 socat[27439] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:38:59.714470   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:38:59 socat[27459] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:01.742445   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:01 socat[27460] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:03.768401   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:03 socat[27467] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:05.798583   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:05 socat[27473] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:07.827532   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:07 socat[27474] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:09.857240   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:09 socat[27475] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
ERROR: logging before flag.Parse: E0917 19:39:11.888064   73228 portforward.go:331] an error occurred forwarding 60905 -> 3030: error forwarding port 3030 to pod 72463db39dae7dfd7a825f443e95b2254faa267e78db363f8f96b998401258b8, uid : exit status 1: 2019/09/17 10:39:11 socat[27479] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:60905/healthz: EOF), retrying ...
[ℹ]  Helm Operator started successfully
[ℹ]  see https://docs.fluxcd.io/projects/helm-operator for details on how to use the Helm Operator
[ℹ]  Waiting for Flux to start
[ℹ]  Flux started successfully
[ℹ]  see https://docs.fluxcd.io/projects/flux for details on how to use Flux
[ℹ]  Committing and pushing manifests to git@github.com:marccarre/my-gitops-repo.git
[master 4c30f03] Add Initial Flux configuration
 1 file changed, 38 insertions(+), 38 deletions(-)
 rewrite flux/tiller-ca-cert-configmap.yaml (87%)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.13 KiB | 2.13 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:marccarre/my-gitops-repo.git
   2401b70..4c30f03  master -> master
[ℹ]  Flux will only operate properly once it has write-access to the Git repository
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/my-gitops-repo979274957/my-gitops-repo'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 375 (delta 27), reused 50 (delta 11), pack-reused 306
Receiving objects: 100% (375/375), 151.96 KiB | 314.00 KiB/s, done.
Resolving deltas: 100% (134/134), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  cloning repository "git@github.com:marccarre/eks-quickstart-app-dev.git":master
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/quickstart-942032442'...
remote: Enumerating objects: 190, done.
remote: Total 190 (delta 0), reused 0 (delta 0), pack-reused 190
Receiving objects: 100% (190/190), 48.32 KiB | 301.00 KiB/s, done.
Resolving deltas: 100% (84/84), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[ℹ]  processing template files in repository
[ℹ]  writing new manifests to "/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/my-gitops-repo979274957/my-gitops-repo/base"
[ℹ]  Nothing to commit (the repository contained identical files), moving on
Everything up-to-date
[ℹ]  please configure git@github.com:marccarre/my-gitops-repo.git so that the following Flux SSH public key has write access to it
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCokQQ+tiKTKpAYsCgn/bDP2iDJvtm/k63SqwEtbakI06I/Ub2z6LHWwrbx1y4ZqNd2AXfpfZ+82Ymwu0yy8ZIzzPXnLvf0d8r1ewsORySkavTRAmPmexA+CtprKfAGxv1Nya7L0N/YdOX9Ww3M/7xfus8T6ZQQ158XKttooATJBPQ35Nzv10GGiwdzjgQ0ZQALf+b0mDj4xObDwvzeOK7L90dLRu3F1pGNhA8wxq8+RkVJXBVPlnHcbx9o+fbINNzXtp06OJmi0EQmvEnPzFGW7Qmpcas4raYtIv3DlRfTgFf3x2QJ397RfafJfM7H/ebPKDdC96jlzVWxykjgjtcL
```

Each re-run of the command adds a commit to the configuration repository, e.g.:

- first run: https://github.com/marccarre/my-gitops-repo/commit/2401b70a6e4643b9928307e5408969169f2d9f2c
- second run: https://github.com/marccarre/my-gitops-repo/commit/4c30f038e1abd6b29e2f4030f9e92793df129dcf

as one would expect it.

### CODE REVIEW

File: pkg/ctl/gitops/apply.go [hunk 1]
```diff
@@ -153,7 +141,9 @@ func doApplyGitops(cmd *cmdutils.Cmd, opts options) error {
 	if err != nil {
 		return err
 	}
-	usersRepoDir := filepath.Join(opts.outputPath, usersRepoName)
+	dir, err := ioutil.TempDir("", usersRepoName)
+	logger.Debug("Directory %s will be used to clone the configuration repository and install the profile", dir)
```
Comment (martina-if) [inline pkg/ctl/gitops/apply.go]: I am thinking if it would be better to have it as an Info message instead. I think I would be wondering where it did all the operations.

Comment (marccarre) [reply pkg/ctl/gitops/apply.go]: I specifically didn't want to log it at `Info` level because I thought this is only useful to _debug_ potential issues, and because Git operations are already logged at `Info` level, and do mention the temporary directory, e.g.:
```
Cloning into '/var/folders/24/d3mml6bn20nftpt91cfldq1h0000gn/T/my-gitops-repo979274957/my-gitops-repo'...
```
versus, before (see #1336), e.g.:
```
Cloning into '/Users/marc/dev/src/github.com/weaveworks/eksctl/_test/my-gitops-repo'...
```

**Comment by marccarre** [comment]
No one seemed to have any objection against this PR, see also:

> This PR should only be merged if we decide we no longer want to generate a local clone of the user's configuration repository as an output.

Therefore, I'm merging it.
