### PR TITLE
Fix creating Windows nodegroups in fully-private clusters

### LINKED ISSUE #2752: Cannot create Windows Private Cluster Without Internet
**What happened?**
When creating a private cluster, the Linux Node Group members correctly joins the cluster, but the Windows Node Group members do not join the cluster. This occurs only when internet access is removed from the private subnets the Node Groups are deployed to.

The message is a time out (after 25 minutes) stating no members joined the Windows Node Group.

`
Error: timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "disccluster-windows-ng"
`
**What you expected to happen?**
I expected the Windows Node Group members to join the cluster without internet access enabled.

**How to reproduce it?**
Include the steps to reproduce the bug.
If using a config, include it here, removing any sensitive information!

Attached the configuration file to create the cluster (replace the VPC, Subnet, Role, and SG info)
[disccluster-config-clean.txt](https://github.com/weaveworks/eksctl/files/5391936/disccluster-config-clean.txt)

To create the cluster initially, I added the default route (0.0.0.0/0) to each subnet and created the cluster and everything worked as expected. I also validated internet access worked correctly.

```
$eksctl create cluster -f disccluster-config-clean.txt --install-vpc-controllers  -v 4
$kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-172-22-1-152.ec2.internal   Ready    <none>   57m   v1.17.11-eks-cfdc40
ip-172-22-1-92.ec2.internal    Ready    <none>   53m   v1.17.9-eks-4c6976
ip-172-22-2-117.ec2.internal   Ready    <none>   53m   v1.17.9-eks-4c6976
ip-172-22-2-178.ec2.internal   Ready    <none>   57m   v1.17.11-eks-cfdc40
```

I then deleted the cluster (eksctl delete cluster --name disccluster --region us-east-1). After everything was cleaned up, I removed just the default route. I validated no internet access. I then tried to create the cluster again (see logs attached below):

```
$eksctl create cluster -f disccluster-config-clean.txt --install-vpc-controllers  -v 4
$kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-172-22-1-211.ec2.internal   Ready    <none>   25m   v1.17.11-eks-cfdc40
ip-172-22-2-122.ec2.internal   Ready    <none>   25m   v1.17.11-eks-cfdc40
```

The two nodes that joined are the Linux nodes. The EC2 console shows all of the instances are up and running, but they are not joining the cluster.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

I am using Amazon Linux 2 and downloaded eksctl as stated in the instructions for installation (curl piped to tar and then moved to /usr/local/bin).

My AWS credential are defined at the CLI (environment variables) and I have the AdministratorAccess managed policy associated with my account (and no additional restrictions or SCPs applied).

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.29.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Internet Create Process:**
This is the output of the cluster create process with internet enabled:
[internet-enabled-cluster-create.log](https://github.com/weaveworks/eksctl/files/5392046/internet-enabled-cluster-create.log)

**No-Internet Create Process**
This is the output of the cluster create process without internet enabled:
[internet_disabled.log](https://github.com/weaveworks/eksctl/files/5392066/internet_disabled.log)

### PR DESCRIPTION
**Pull request by cPu1**
### Description

Fixes #2752 

TODO: 

- [x] Fix tests

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/nodebootstrap/windows.go [hunk 1]
```diff
@@ -13,47 +12,105 @@ import (
...
+	userData := base64.StdEncoding.EncodeToString([]byte(strings.Join(bootstrapCommands, "\n")))
+
+	logger.Debug("user-data = %s", userData)
+	return userData, nil
+}
+
+func (b *Windows) makeBootstrapParams() string {
+	params := []keyValue{
+		{
+			key:   "EKSClusterName",
```
Comment (nikimanoledaki) [inline pkg/nodebootstrap/windows.go:53]: code looks good to me! could you provide me with some context on how `userData` is used and why these specific key/value pairs are hardcoded please?

File: pkg/nodebootstrap/windows.go [hunk 2]
```diff
@@ -13,47 +12,105 @@ import (
...
+			value: b.clusterConfig.Metadata.Name,
+		},
+		{
```
Comment (nikimanoledaki) [inline pkg/nodebootstrap/windows.go:56]: are these `b.clusterConfig.X.Y` values always non-nil values? do we need to do any validation to avoid a panic?

File: pkg/nodebootstrap/windows.go [hunk 3]
```diff
@@ -13,47 +12,105 @@ import (
...
+			value: b.clusterConfig.Status.Endpoint,
+		},
+		{
+			key:   "Base64ClusterCA",
+			value: base64.StdEncoding.EncodeToString(b.clusterConfig.Status.CertificateAuthorityData),
+		},
+		{
+			key:   "DNSClusterIP",
+			value: b.ng.ClusterDNS,
+		},
```
Comment (nikimanoledaki) [inline pkg/nodebootstrap/windows.go:67]: are these `b.clusterConfig.X.Y` values always non-nil values? do we need to do any validation to avoid a panic?

Comment (cPu1) [reply pkg/nodebootstrap/windows.go:67]: This codepath is executed after obtaining the cluster's status, so `clusterConfig.Status` here should be non-nil.

File: pkg/nodebootstrap/windows.go (hunk 1 above)
Comment (cPu1) [reply pkg/nodebootstrap/windows.go:53]: `userData` is passed to the launch template, it contains the code required for bootstrapping nodes. The key-value pairs are arguments that are passed to the bootstrap script referenced by `EKSBootstrapScriptFile`, they contain information that's used by the bootstrap script to register itself as a node.

File: pkg/nodebootstrap/windows.go (hunk 3 above)
Comment (nikimanoledaki) [reply pkg/nodebootstrap/windows.go:67]: Right, sounds good. What about `ng.ClusterDNS`?

Comment (nikimanoledaki) [reply pkg/nodebootstrap/windows.go:67]: Ah if it's empty it'll just be ignored, right?

Comment (cPu1) [reply pkg/nodebootstrap/windows.go:67]: >Ah if it's empty it'll just be ignored, right?

Correct.

**Review by Callisto13 — APPROVED** [review]
