### PR TITLE
eksctl {get,delete} fargateprofile now reads the cluster name & region from ClusterConfig

### LINKED ISSUE #1641: Add config file support to `delete fargateprofile` and `get fargateprofile`
today eksctl supports using a config file for creating fargate profiles:

```console
eksctl create fargateprofile -f cluster-config-1.yaml
```

But the config file option is not supported for the other two related commands:

```console
$ eksctl get fargateprofile -f cluster-config-1.yaml 
Error: unknown shorthand flag: 'f' in -f
Usage: eksctl get fargateprofile [flags]
...
```

```console
$ eksctl delete fargateprofile -f cluster-config-1.yaml 
[✖]  invalid Fargate profile name: empty
```

I think those two commands should either say that `-f` is not supported or, preferably, use the config file.

## Related issues

- All commands should have config files (#1126 )

### PR DESCRIPTION
**Pull request by marccarre**
### Description

- `eksctl {create,get,delete} fargateprofile` are now testable (and tested)
- `eksctl {get,delete} fargateprofile -f` now reads the cluster name & region from `ClusterConfig`

Fixes #1641.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`) and target version (e.g. `version/0.12.0`)
- [x] Added note in `docs/release_notes/draft.md` (or relevant release note)

#### `get fargateprofile`

```console
$ ./eksctl get clusters
NAME            REGION
mc-1664-test    ap-northeast-1

$ ./eksctl get fargateprofile
Error: --cluster must be set
Usage: eksctl get fargateprofile [flags]
[...]
Use 'eksctl get fargateprofile [command] --help' for more information about a command.


$ cat <<EOF >mc-1664-test.yaml
> ---
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
>   name: mc-1664-test
>   region: ap-northeast-1
> EOF


$ ./eksctl get fargateprofile -f mc-1664-test.yaml 
NAME		SELECTOR_NAMESPACE	SELECTOR_LABELS	POD_EXECUTION_ROLE_ARN										SUBNETS
fp-bc364107	default			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-dev		dev			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-test		test			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152

$ ./eksctl get fargateprofile -f mc-1664-test.yaml --name fp-dev
NAME	SELECTOR_NAMESPACE	SELECTOR_LABELS	POD_EXECUTION_ROLE_ARN										SUBNETS
fp-dev	dev			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152


$ ./eksctl get fargateprofile --cluster mc-1664-test
NAME		SELECTOR_NAMESPACE	SELECTOR_LABELS	POD_EXECUTION_ROLE_ARN										SUBNETS
fp-bc364107	default			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-dev		dev			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-test		test			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152

$ ./eksctl get fargateprofile --cluster mc-1664-test --name fp-dev
NAME	SELECTOR_NAMESPACE	SELECTOR_LABELS	POD_EXECUTION_ROLE_ARN										SUBNETS
fp-dev	dev			<none>		arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX	subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
```

#### `delete fargateprofile`

```console
$ ./eksctl get clusters
NAME            REGION
mc-1664-test    ap-northeast-1

$ ./eksctl get fargateprofile --cluster mc-1664-test
NAME            SELECTOR_NAMESPACE      SELECTOR_LABELS POD_EXECUTION_ROLE_ARN                                                                          SUBNETS
fp-bc364107     default                 <none>          arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX  subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-dev          dev                     <none>          arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX  subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
fp-test         test                    <none>          arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX  subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152

$ ./eksctl delete fargateprofile
Error: --cluster must be set
Usage: eksctl delete fargateprofile [flags]
[...]
Use 'eksctl delete fargateprofile [command] --help' for more information about a command.

$ cat <<EOF >mc-1664-test.yaml
> ---
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
>
> metadata:
>   name: mc-1664-test
>   region: ap-northeast-1
> EOF

$ ./eksctl delete fargateprofile -f mc-1664-test.yaml --name fp-bc364107
[ℹ]  deleted Fargate profile "fp-bc364107" on EKS cluster "mc-1664-test"

$ ./eksctl delete fargateprofile --cluster mc-1664-test --name fp-test
[ℹ]  deleted Fargate profile "fp-test" on EKS cluster "mc-1664-test"

$ ./eksctl get fargateprofile --cluster mc-1664-test
NAME    SELECTOR_NAMESPACE      SELECTOR_LABELS POD_EXECUTION_ROLE_ARN                                                                          SUBNETS
fp-dev  dev                     <none>          arn:aws:iam::083751696308:role/eksctl-mc-1664-test-cluste-FargatePodExecutionRole-VHHN3M9X5IBX  subnet-01f27f9c008fe197d,subnet-0b42d9d42f7eb92bf,subnet-06de09d669eb78152
```

### CODE REVIEW

File: pkg/ctl/create/fargate.go [hunk 1]
```diff
@@ -49,9 +58,6 @@ func configureCreateFargateProfileCmd(cmd *cmdutils.Cmd) *fargate.CreateOptions
 }
 
 func doCreateFargateProfile(cmd *cmdutils.Cmd, options *fargate.CreateOptions) error {
-	if err := cmdutils.NewCreateFargateProfileLoader(cmd, options).Load(); err != nil {
-		return err
-	}
 	ctl, err := cmd.NewCtl()
```
Comment (martina-if) [inline pkg/ctl/create/fargate.go]: Ideally, it would be nice if we could extract all CLI related things from these functions, so that they are independent from any UI. Not sure how feasible it is at this point... (Not for this PR, I only mention it because I know you are working on refactoring these things)

Comment (marccarre) [reply pkg/ctl/create/fargate.go]: Indeed 👍
