### PR TITLE
Fix bug in supporting non-default branches for gitops repos

### LINKED ISSUE #2240: Flux / GitOps setup fails for non-default git.repo.branch
**What happened?**

Eksctl fails to setup Flux (and the Helm Operator) when a custom (non-`master` / default) `git.repo.branch` is configured.

**What you expected to happen?**

Eksctl creating a new orphan branch as configured, and committing the Flux and Helm Operator manifests to this branch.

**How to reproduce it?**

```sh
cat << EOF | eksctl create cluster -f -
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: custom-flux-branch
  region: eu-north-1
git:
  repo:
    url: "git@github.com:org/example.git"
    branch: custom
EOF
```

yields

```log
...
[!]  flux deployment was not found
[ℹ]  Generating manifests
[ℹ]  Cloning git@github.com:org/example.git
Cloning into '/tmp/eksctl-install-flux-clone-188933638'...
remote: Enumerating objects: 31, done.        
remote: Counting objects: 100% (31/31), done.        
remote: Compressing objects: 100% (28/28), done.        
remote: Total 31 (delta 2), reused 31 (delta 2), pack-reused 0        
Receiving objects: 100% (31/31), 26.37 KiB | 999.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
error: pathspec 'custom' did not match any file(s) known to git
Error: unable to install flux: cannot clone repository git@github.com:org/example.git: exit status 1
```

**Versions**

Please paste in the output of these commands:

```console
$ eksctl version
0.20.0
```

### PR DESCRIPTION
**Pull request by hiddeco**
### Description

Fixes #2240 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

### CODE REVIEW

File: pkg/git/git.go [hunk 1]
```diff
@@ -104,11 +103,7 @@ func (git *Client) cloneRepoInPath(clonePath string, options CloneOptions) error
 		// Switch to target branch
 		args := []string{"checkout", options.Branch}
 		if options.Bootstrap {
-			empty, err := git.isRepoEmpty()
-			if err != nil {
-				return err
-			}
-			if empty {
+			if !git.isRemoteBranch(options.Branch) {
```
Comment (michaelbeaumont) [inline pkg/git/git.go:106]: It's not clear to me why it's important that it not be a remote branch in order to execute `checkout -b`? What happens if it isn't a remote branch but still exists? Why not check existence for the condition?

Comment (hiddeco) [reply pkg/git/git.go:106]: :100:

File: pkg/git/git.go [hunk 2]
```diff
@@ -182,6 +173,9 @@ func (git Client) Commit(message, user, email string) error {
 
 // Push pushes the changes to the origin remote
 func (git Client) Push() error {
+	if err := git.runGitCmd("config", "push.default", "current"); err != nil {
```
Comment (martina-if) [inline pkg/git/git.go:176]: Is it possible to avoid having to touch the local configuration for this? I was planning on avoiding that for the user and the email as well so it would be nice to have. (Although no need to block the pr for that)

**Comment by martina-if** [comment]
Thanks for the fix Hidde!

File: pkg/git/git.go (hunk 2 above)
Comment (hiddeco) [reply pkg/git/git.go:176]: After a couple of experiments this seemed to be the easiest way to cause the push to work without complaints about a missing upstream branch.

The other alternative would be to set the remote tracking branch after checking out, but this did not seem inline with the tactic used for the commit, which applies configuration at the time it is actually required for an action.

**Comment by martina-if** [comment]
@hiddeco can you rebase?

**Comment by hiddeco** [comment]
@martina-if done!
