### PR TITLE
Dump logs to disk on failure

### LINKED ISSUE #3030: Dump logs to disk on failure
**Why do you want this feature?**
When a command fails its not always clear whats caused it, and if you haven't run it at a higher verbosity the information required to fully debug it might be lost.

**What feature/behavior/change do you want?**
eksctl to dump the log output with a higher verbosity upon failure. e.g.
```bash
$ eksctl create cluster --name my-cluster
error: exited 1

$ ls
eksctl-create-cluster-my-cluster-<timestamp>.logs
```

This has the potential to be noisy if commands are failing often

### PR DESCRIPTION
**Pull request by yaash45**
### Description

When commands fail, it can be hard to locate the source of the issue, especially when run with lower verbosity. To increase debugging efficiency, logs are dumped to disk on failure, so that the user can sift through them more easily.

The logs are only dumped to disk only in the event of a failure into a directory titled `logs/`. Furthermore, the logfile is timestamped for better organization and accessibility.

The implementation is simple: write log output to an in-memory io.Writer (a byte buffer in this case), and write the contents of that buffer into a file before calling `os.Exit(1)`. This was fairly easy to implement using the golang `io.MultiWriter`. 

Fixes #3030

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by yaash45** [comment]
Manual testing output:

1. Initial state, where there are no log files dumped to disk


2. Run a failing command:


3. Peek into generated log file after failure:


4. Running a subsequent failing command, so that another unique log file is dumped:

**Comment by aclevername** [comment]
Looking good @yaash45 !

Tagging the rest of the team in to review @nikimanoledaki @Himangini @cPu1 @Skarlso 

Open thoughts:
1. What should we name the file? 
2. Should this be the default behaviour, or opt-in?

File: cmd/eksctl/logger.go [hunk 1]
```diff
@@ -78,3 +83,27 @@ func initLogger(level int, colorValue string) {
 		return out
 	}
 }
+
+func dumpLogsToDisk(logBuffer *bytes.Buffer, errorString string) error {
+	_, err := os.Stat("logs/")
```
Comment (Skarlso) [inline cmd/eksctl/logger.go:88]: In line with the below if.

File: cmd/eksctl/logger.go [hunk 2]
```diff
@@ -78,3 +83,27 @@ func initLogger(level int, colorValue string) {
...
+
+	if os.IsNotExist(err) {
+		err := os.Mkdir("logs/", 0755)
+
+		if err != nil {
+			return err
```
Comment (Skarlso) [inline cmd/eksctl/logger.go:94]: Please wrap the errors with `fmt.Errorf`.

File: cmd/eksctl/logger.go [hunk 3]
```diff
@@ -78,3 +83,27 @@ func initLogger(level int, colorValue string) {
 		return out
 	}
 }
+
+func dumpLogsToDisk(logBuffer *bytes.Buffer, errorString string) error {
+	_, err := os.Stat("logs/")
+
+	if os.IsNotExist(err) {
+		err := os.Mkdir("logs/", 0755)
```
Comment (Skarlso) [inline cmd/eksctl/logger.go:91]: Inline with the below if

File: cmd/eksctl/main.go [hunk 4]
```diff
@@ -90,13 +91,21 @@ func main() {
...
+
 	cobra.OnInitialize(func() {
-		initLogger(*loggerLevel, *colorValue)
+		initLogger(*loggerLevel, *colorValue, logBuffer)
 	})
 
 	rootCmd.SetUsageFunc(flagGrouping.Usage)
 
 	if err := rootCmd.Execute(); err != nil {
+		dumpErr := dumpLogsToDisk(logBuffer, err.Error())
```
Comment (Skarlso) [inline cmd/eksctl/main.go:103]: Inline with the below if.

File: cmd/eksctl/main.go [hunk 5]
```diff
@@ -90,13 +91,21 @@ func main() {
...
+
+		if dumpErr != nil {
+			fmt.Println("Failed to dump logs to disk. Error = " + dumpErr.Error())
```
Comment (Skarlso) [inline cmd/eksctl/main.go:106]: I thought we have a logger for this? 🤔 Am I mistaken?

File: integration/tests/dump_logs/dump_logs_test.go [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+
+func init() {
+	testing.Init()
+	if err := api.Register(); err != nil {
+		panic(errors.Wrap(err, "unexpected error registering API scheme"))
+	}
+	params = tests.NewParams("dump_logs")
+}
+
+func TestDumpLogs(t *testing.T) {
```
Comment (Skarlso) [inline integration/tests/dump_logs/dump_logs_test.go:30]: Please extract this into a suite file.

**Comment by Skarlso** [comment]
Definitely make it opt in, because we don't know how `eksctl` is invoked. It might not actually have any writing rights or access to a disk or anything like that. Also, we don't want to change the default behaviour.

I'm fine with the current name of the logs. :)

**Comment by Himangini** [comment]
> Looking good @yaash45 !
> 
> Tagging the rest of the team in to review @nikimanoledaki @Himangini @cPu1 @Skarlso
> 
> Open thoughts:
> 
> 1. What should we name the file?
> 2. Should this be the default behaviour, or opt-in?

Thanks for opening the PR @yaash45  🎉  

Thoughts from my side:
1. Couple of things. I like the logs folder but I am not a fan of the name. Also, I don't like the idea of having multiple log files for the same day [ it can get outta hand 🙈 ]  I'll suggest if we have a simpler name for one file per day and append all logs in the same file? maybe eg., `/logs/eksctl-21-10-2021.log` should be nice for debugging
2. Agree with @Skarlso should be opt-in and not be enabled by default.

**Comment by Himangini** [comment]
@yaash45 is this still WIP? please let us know if you need help :)

**Comment by yaash45** [comment]
> @yaash45 is this still WIP? please let us know if you need help :)

Sorry for the delay, but I haven't had a chance to make the changes. I'll work on it this week and resubmit for review.

File: integration/tests/dump_logs/dump_logs_test.go (hunk 6 above)
Comment (yaash45) [reply integration/tests/dump_logs/dump_logs_test.go:30]: Could you please show me an example of what you mean? I am not quite sure I understand what a "suite" file is in this context. Thanks!

Comment (Skarlso) [reply integration/tests/dump_logs/dump_logs_test.go:30]: ah sorry, completely missed this ping. :/ In all other folders look for a file ending `suit_test.go`. :) We use that to set up the suit.

File: cmd/eksctl/main.go [hunk 7]
```diff
@@ -90,13 +91,18 @@ func main() {
...
+
 	cobra.OnInitialize(func() {
-		initLogger(*loggerLevel, *colorValue)
+		initLogger(*loggerLevel, *colorValue, logBuffer)
 	})
 
 	rootCmd.SetUsageFunc(flagGrouping.Usage)
 
 	if err := rootCmd.Execute(); err != nil {
+		if dumpErr := dumpLogsToDisk(logBuffer, err.Error()); dumpErr != nil {
```
Comment (Skarlso) [inline cmd/eksctl/main.go:103]: I'm wondering if we should put this in SIGTERM with a signal catcher so it dumps the logs in case eksctl was terminated. Not necessary in this PR, I'm just musing about it. :)

**Review by Skarlso — APPROVED** [review]

**Comment by Himangini** [comment]
@yaash45 feel free to reach out to us for help with this PR. Please make the PR draft in the meantime and request reviews from our team when you're ready with the changes :)

File: integration/tests/dump_logs/dump_logs_test.go (hunk 6 above)
Comment (yaash45) [reply integration/tests/dump_logs/dump_logs_test.go:30]: I am still having trouble finding these `suite_test.go` files you mentioned. I am looking under the `integrations/tests` directory. None of the sub-directories of this path have a `suite_test.go` file as far as I can see. If you could please explain the purpose of this file, I can try to implement it. Thanks!

**Comment by yaash45** [comment]
> > Looking good @yaash45 !
> > Tagging the rest of the team in to review @nikimanoledaki @Himangini @cPu1 @Skarlso
> > Open thoughts:
> > 
> > 1. What should we name the file?
> > 2. Should this be the default behaviour, or opt-in?
> 
> Thanks for opening the PR @yaash45 🎉
> 
> Thoughts from my side:
> 
> 1. Couple of things. I like the logs folder but I am not a fan of the name. Also, I don't like the idea of having multiple log files for the same day [ it can get outta hand 🙈 ]  I'll suggest if we have a simpler name for one file per day and append all logs in the same file? maybe eg., `/logs/eksctl-21-10-2021.log` should be nice for debugging
> 2. Agree with @Skarlso should be opt-in and not be enabled by default.

@Himangini I greatly appreciate your insights! I have made the changes you have requested. The feature is now opt-in, and can be turned on using the `-d` flag. Furthermore, there is only one log file created per day. Please let me know if this works. Thanks!

**Comment by Skarlso** [comment]
@yaash45 Hello!

So we have a new rule that package names and variable names can't have underscore in them. Would you mind renaming the integration test package please? Just remove the `_` or, if you like it too much, add this:

```go
//revive:disable
package dump_logs
```

**Comment by Himangini** [comment]
> @yaash45 Hello!
> 
> So we have a new rule that package names and variable names can't have underscore in them. Would you mind renaming the integration test package please? Just remove the `_` or, if you like it too much, add this:
> 
> ```go
> //revive:disable
> package dump_logs
> ```

@yaash45 any chance you are working on this? would you like us to wrap this up?

File: integration/tests/dump_logs/dump_logs_test.go (hunk 6 above)
Comment (Skarlso) [reply integration/tests/dump_logs/dump_logs_test.go:30]: Ah, never mind, this is fine. :)

**Comment by yaash45** [comment]
> > @yaash45 Hello!
> 
> > 
> 
> > So we have a new rule that package names and variable names can't have underscore in them. Would you mind renaming the integration test package please? Just remove the `_` or, if you like it too much, add this:
> 
> > 
> 
> > ```go
> 
> > //revive:disable
> 
> > package dump_logs
> 
> > ```
> 
> 
> 
> @yaash45 any chance you are working on this? would you like us to wrap this up?

Hi! Sorry I have been away. I will push my changes tomorrow to wrap it up.

**Comment by yaash45** [comment]
> > @yaash45 Hello!
> > So we have a new rule that package names and variable names can't have underscore in them. Would you mind renaming the integration test package please? Just remove the `_` or, if you like it too much, add this:
> > ```go
> > //revive:disable
> > package dump_logs
> > ```
> 
> @yaash45 any chance you are working on this? would you like us to wrap this up?

Done :)

**Comment by yaash45** [comment]
Bumping this PR! Is there some additional work required? Looks like all the CI tests are passing after my last commit. Please let me know if this looks good now. Thanks!

**Comment by Skarlso** [comment]
@yaash45 Thanks! Sorry, this fell off of my radar for some reason! Thank you for the bump. I updated latest and after everything is green it should merge. Thank you for your contribution! :)

**Comment by yaash45** [comment]
> @yaash45 Thanks! Sorry, this fell off of my radar for some reason! Thank you for the bump. I updated latest and after everything is green it should merge. Thank you for your contribution! :) 

No problem at all! I hope that this contribution is helpful 😄

**Comment by Skarlso** [comment]
@yaash45 Of course it is! :)
